### ISSUE TITLE
Config produced is not compliant with ocvalidate utilities from OC 

### ISSUE THREAD

**Issue by junaedahmed** [ic005k/QtOpenCoreConfig#10]
Hi,
I am enjoying your work very much. This is relatively a very small nuances. It would be great if the app could make Config.plist which is fully compliant with ocvalidate utilities.
```
 ocvalidate ./ocvalidate /Volumes/ESP/EFI/OC/Config.plist
OCS: Missing key Delete, context <ACPI>!
OCS: Missing key MmioWhitelist, context <Booter>!
OCS: Missing key Devices, context <Memory>!
Done checking /Volumes/ESP/EFI/OC/Config.plist in 2 ms
```

Regards
Junaed Ahmed

**Comment by ic005k** [comment]
The reason is because you have not set this part of the data. You can refer to SampleCustom.plist to put the relevant data without enabling it. When ocvalidate is checked, these prompts will not appear. However, this is just a reminder and does not affect the correctness of Config.plist.
Thank you for your attention and feedback, and welcome more suggestions. good luck!

**Comment by junaedahmed** [comment]
Thank you for your quick response. I knew that it produced correct Config.plist. I was mentioning it because I thought it should add all mendatory fields either it is enabled/used so that ocvalidate doesn't complain about anything.

**Comment by ic005k** [comment]
Okay, I understand what you think, this feature will be implemented in the next version.

**Comment by ic005k** [comment]
> Thank you for your quick response. I knew that it produced correct Config.plist. I was mentioning it because I thought it should add all mendatory fields either it is enabled/used so that ocvalidate doesn't complain about anything.

This feature has been implemented, please download the latest version.
At the same time, please pay attention to update OC to the latest version: https://github.com/williambj1/OpenCore-Factory/releases

More suggestions are welcome, thanks!

**Comment by junaedahmed** [comment]
Sorry to bother you with this again. Now it is compalining about below fields:
```
➜  ocvalidate ./ocvalidate /Volumes/ESP/EFI/OC/Config.plist
OCS: No schema for TextMode at 6 index, context <Entries>!
OCS: No schema for BlacklistAppleUpdate at 4 index, context <Security>!
OCS: No schema for RealPath at 6 index, context <Tools>!
OCS: No schema for TextMode at 7 index, context <Tools>!
OCS: No schema for RealPath at 6 index, context <Tools>!
OCS: No schema for TextMode at 7 index, context <Tools>!
OCS: No schema for RealPath at 6 index, context <Tools>!
OCS: No schema for TextMode at 7 index, context <Tools>!
Done checking /Volumes/ESP/EFI/OC/Config.plist in 4 ms
```
Although I don't need them they are structural elements of the Config so should also be by default present. I think ocvalidate validation should be integrated to QtOCC so that after each upgrade there is no structural filed left behind.

Regards
Junaed

**Comment by ic005k** [comment]
Oh, ocvalidate has a version distinction, you need to use the ocvalidate in the currently used OC version to check.

**Comment by junaedahmed** [comment]
I am using ocvalidate from 0.6.3 release version. And I am trying to make my config 0.6.3 compatible. However, the new change introduced in 0.6.3 is not required in my system, so they are disabled but should be present. I think some kind of migration system or taging config with version in comment would be a way to go for it. OC from 0.6.3 started to support comment in Config.plist

**Comment by ic005k** [comment]
At the same time, please upgrade OC to the latest version, because the latest version of OC has added new content. If ocvalidate is a file in the previous OC version, when checking the new version of the OC configuration file, some key values will not be recognized.

**Comment by junaedahmed** [comment]
> At the same time, please upgrade OC to the latest version, because the latest version of OC has added new content. If ocvalidate is a file in the previous OC version, when checking the new version of the OC configuration file, some key values will not be recognized.

ohh, I get it. The QtOCC made Config for 0.6.4 and I am trying to make 0.6.3 compatible config. So it complaining of not having those scheme. Thanks for the clarification.
