### ISSUE TITLE
在win中挂载ESP分区失败

### ISSUE THREAD

**Issue by Fateliu** [ic005k/QtOpenCoreConfig#101]
在管理工具中能看到EFI分区 但是在此电脑中不显示
<img src = 'https://s3.bmp.ovh/imgs/2021/12/1559e9607c413fbe.png' />
win10版本21H2 内部版本19044.1415

**Comment by ic005k** [comment]
这是个经典问题，貌似还真没有很好的办法，你可在网上搜索下。
OCAT附带这个文件管理器就是为了方便管理ESP分区，但这不是一个非常直接的办法。
我个人一直认为将OC放到ESP分区是个不太理想的选择，我个人是主张将OC放到另外一个FAT32分区（非ESP分区），这样就可以直接操作它了，无需挂载（包括Mac下）。
坦率地讲，我真不知道其他用户是如何在Win下操作的，你是第一个提出这个问题的用户。

**Comment by ic005k** [comment]
有好的、更直接的办法，请告诉我，谢谢。

**Comment by Fateliu** [comment]
好的 感谢您的解答 我只是强迫症犯了 目前可以用DiskGenius导出配置文件再修改 解决EFI在win下不能访问的问题  曲线救国
