### ISSUE TITLE
Updater does not work / DMG volume name is erroneous

### ISSUE THREAD

**Issue by mackonsti** [ic005k/QtOpenCoreConfig#102]
Hello @ic005k how are you? Thanks for your continuing work on this tool. I have a couple of issues to report.

I am getting a lot of reports via Git Hub notifications for multiple daily updates sometimes and I used to update manually by downloading the DMG, but yesterday I realised the updater doesn't complete its job.

1) When you package the release in the DMG please can you fix the volume name to show something more logical and compliant to OS File naming?

With `OCAT_Mac.dmg` when open we get name `bin/release/OCAuxiliaryTools` in Finder, and this could pose a problem at some point. There is for sure a parameter in your DMG packaging to define "Volume" name, although I am not sure how you package...
```
% pwd
/Volumes
% ls -lAG
drwxr-xr-x   3 mackonsti  staff  170 Dec 20 10:29 bin:release:OCAuxiliaryTools
```
2) On my **Catalina** macOS system, in my recent version of OCAuxiliaryTools namely 0.7.6 build 2021-12-17 when launched, I do get the popup that alerts for a new version; I click to download, the new dialog shows progress but I never get the button to update/replace the application:

macOS running:  **Catalina**
Location of your tool: `~/Applications/`   i.e. **not** in `/Applications/` but in **user's** apps folder (where I usually put some tools)
![Updater Stops Here](https://user-images.githubusercontent.com/1313613/146882470-c1d79b15-042e-437a-a629-67488b47d6e4.png)
I see that in my user's main home folder there is a folder created `~/tempqtiasl` which contains the new DMG but nothing happens. Moreover, the download is damaged? Only 653 bytes?
```
% pwd
/Users/mackonsti/tempqtiasl
% ls -lAG
-rw-r--r--  1 mackonsti  staff  653 Dec 19 15:50 QtiASL_Mac.dmg
```
There seems some problem with your URL?

I do believe your update method needs refinement, in my opinion.

Many thanks.

P.S. Same problem updating **QtiASL** too 😢

**Comment by ic005k** [comment]
It's easy, for OCAT, please select the appropriate proxy in the Preferences.
For QtiASL, select the appropriate proxy in the Help menu.
This will allow you to break GitHub's restrictions, which usually depend on your region.

**Comment by ic005k** [comment]
How to test it?
It's very simple, please select "Download Upgrade Package" in the help menu and if it works, you're good to go. Usually this download process is very fast and takes only 5 to 10 seconds.

**Comment by mackonsti** [comment]
Hi @ic005k thanks for your reply, but _why_ use "proxy"? I have no blocking or any other problems in my region (Europe). I mean, all other software/tools, they update just fine with direct GitHub connection from my region.

Moreover, it is not "proxy" really but "server", correct? I think `Alternative Servers` is the best, correct English menu name I my humble opinion.

Also please, for OCAuxiliaryTools and QtiASL:

* kindly fix the English menu from `CheckUpdate` (no space) to `Update Check` if you want it only in 2 words (otherwise it's `Check for Update`)
* kindly change the English text from `It is currently the latest version!` to `You are currently using the latest version!`
* kindly consider the change of the word proxy to "Alternative Server" as the proxy prompts people to other type of 

**UPDATE:** It seems you have a binary called `aria2c` that does the connection, and this one was blocked by my firewall. Do you confirm that we need to allow `aria2c` to connect freely to the internet for tool updates?

Are _you_ in control of these alternative servers? I do not know the other alternative servers and do not trust them (sorry) as I am not familiar... QtiASL does not download from GitHub, wow can I debug the issue when connecting to first official GitHub server from your list? Is there any LOG file I can share here?

Xie Xie

**Comment by ic005k** [comment]
> It seems you have a binary called `aria2c` that does the connection, and this one was blocked by my firewall. Do you confirm that we need to allow `aria2c` to connect freely to the internet for tool updates?

OCAT uses aria2 as a download tool to download the upgrade package, you can check the OCAT download log for details.
What is aria2? Please Google it.
Thank you for such detailed feedback and suggestions, especially the English menu and other parts, more questions or suggestions are welcome.

**Comment by ic005k** [comment]
> but _why_ use "proxy"? I have no blocking or any other problems in my region (Europe).

Sorry, I'm really not sure about this, but if your network is not blocked in any way, it is possible to access GitHub directly.
But whether you use a proxy or not, it's safe to assume that the links point to, for example, the following address.

https://github.com/ic005k/QtOpenCoreConfig/releases/tag/20220052

**Comment by ic005k** [comment]
OCAT and QtiASL online upgrades are actually an automatic download process done on their release pages, which may be easier to understand when put this way.

**Comment by mackonsti** [comment]
Hello @ic005k thanks for pushing your updates. I saw you closed the ticket, I wanted to ask you to leave it open but it's OK.

Please, I would like to report 3 things:

a) in both QtiASL and **OCAuxiliaryTools** the DMGs have wrong volume name, they are `bin/release/OCAuxiliaryTools` for example and **not the name of the application** ; please can you fix that, not sure what tool you use to package DMG but there is most certainly a parameter to define "Volume Name"...

b) In **OCAuxiliaryTools** I have in Preferences set https://github.com/ as download mirror and it works 100% (with `aria2`) via GitHub API. But in QtiASL the same server is not downloading anything, any idea why is that?

c) Perhaps in your development roadmap you can include in **QtiASL** the same update mechanism as **OCAuxiliaryTools** ? That would be convenient as you could use 1 code-base for this same feature (except the source URLs). Just an idea.

Many thanks, Season Greetings.

P.S. If you allow me another English text fix, in OCAuxiliaryTools -> Preferences, the second tab name you could change the second column from `Url` to `Source URL` and also the button at the bottom to `Open URL in browser` to be more distinct.

In QtiASL -> Preferences a more correct English would be `Misc` to `Miscellaneous` and `WrapWord` to `Line wrapping` or `Word wrapping` instead. Thanks

**Comment by ic005k** [comment]
Oh, sorry, I saw that you didn't reply for a long time (more than 2 days), so I closed the question.
I really appreciate your enthusiasm, and when I have enough free time I will try to continue to improve them.
Thanks again, and more questions or suggestions are welcome.

**Comment by mackonsti** [comment]
Apologies for my delay, I was in transit between countries for the Christmas holidays. I wanted to keep it open so I can check the newer updates and how it worked; so you have my feedback in my previous message. Thank you for listening. Xie Xie

**Comment by ic005k** [comment]
> a) in both QtiASL and **OCAuxiliaryTools** the DMGs have wrong volume name, they are `bin/release/OCAuxiliaryTools` for example and **not the name of the application** ; please can you fix that, not sure what tool you use to package DMG but there is most certainly a parameter to define "Volume Name"...

I didn't have much time to respond to users' questions, but when I saw this, I had to say something.
First of all, it's not a bug, it's a volume name after mounting dmg, this volume name is definable according to your APP's needs, of course you are free to define it, but it's not necessary to be completely consistent with the APP's name.
I really don't know why you are asking this question?
But you raised the issue and wrote such a long post, so I will probably change it in OCAT to the one you want and QtiASL will not make any more changes because it doesn't make any sense.
Thanks again for your enthusiasm, and thanks.

**Comment by ic005k** [comment]
> b) In **OCAuxiliaryTools** I have in Preferences set https://github.com/ as download mirror and it works 100% (with `aria2`) via GitHub API. But in QtiASL the same server is not downloading anything, any idea why is that?

For QtiASL, please choose the mirror server to complete the update download, and it will function properly.
QtiASL is very slow to update and some of the methods used in OCAT may not be used in QtiASL as I don't have much time at all to do that, sorry very much.

**Comment by mackonsti** [comment]
> I didn't have much time to respond to users' questions, but when I saw this, I had to say something. First of all, it's not a bug, it's a volume name after mounting dmg, this volume name is definable according to your APP's needs, of course you are free to define it, but it's not necessary to be completely consistent with the APP's name. I really don't know why you are asking this question? But you raised the issue and wrote such a long post, so I will probably change it in OCAT to the one you want and QtiASL will not make any more changes because it doesn't make any sense. Thanks again for your enthusiasm, and thanks.

Thank you for taking the time to reply. I my long Mac experience, I have not seen such a volume name, so I thought it was a forgotten parameter or something wrong in making the DMG. Of course, I am only pointing to small things, but the use of the / character makes me a little more uneasy, hence my comment about possibly naming it per the application. But as you are the creator, owner and distributor, you have full rights and control 😄 So I leave you choose. It's just that personally I consider this name a little unorthodox, if you understand my point. But thanks again for reading my comment.

> For QtiASL, please choose the mirror server to complete the update download, and it will function properly. QtiASL is very slow to update and some of the methods used in OCAT may not be used in QtiASL as I don't have much time at all to do that, sorry very much.

Sure, I will do that. Your time is valuable and well spent on these tools, we thank you again for sharing them with the community.

So I guess now you are welcome to close the ticket as there is nothing pending, you replied to everything. Thank you again @ic005k

**Comment by ic005k** [comment]
Well, as always, you're welcome to post any questions or suggestions you may have, and as long as I have free time, I'm more than happy to discuss them with you, so thank you again.
