### ISSUE TITLE
希望可以直接访问 EFI 分区

### ISSUE THREAD

**Issue by dfc643** [ic005k/QtOpenCoreConfig#103]
我发现了一个方法可以直接让 OCAT 访问 EFI 分区，希望能帮到需要的人

1. 在 OCAT 的根目录下新建一个 bat 文件
```batch
@echo off
"%~dp0\Database\win\FindESP.exe" -mount:*
"%~dp0\OCAuxiliaryTools.exe"
```
2. 然后右键管理员权限运行 bat
3. 在 OCAT 文件-打开，中可以直接访问 EFI 分区

我用 BAT2EXE 把 bat 转换成 exe 了用起来更方便：
https://dfc643.lanzouo.com/ihIwAy8bsde (放在OCAT根目录双击打开)

**Comment by ic005k** [comment]
厉害，我将在下个版本中集成你提供的这个通过bat转换成的exe文件，欢迎更多的探索与发现。

**Comment by dfc643** [comment]
@ic005k 谢谢作者开发的 OCAT，现在 Windows 里也可以方便修改 OC 配置了! 😸

**Comment by ic005k** [comment]
好，有任何问题或建议，请随时留言。
