### ISSUE TITLE
unwanted software in release 20220071

### ISSUE THREAD

**Issue by yunsongyu** [ic005k/QtOpenCoreConfig#106]
windows security report potentially unwanted software in release 20220071(0.7.7)
![image](https://user-images.githubusercontent.com/27912573/149704172-12e5d60a-27c6-4749-b011-28773a8dff50.png)

**Comment by ic005k** [comment]
This file is a bat converted exe file, please see here for specific functions and details.

https://github.com/ic005k/QtOpenCoreConfig/issues/103
