### ISSUE TITLE
请教一下，界面怎么是英文版的呢？

### ISSUE THREAD

**Issue by k2y1982** [ic005k/QtOpenCoreConfig#109]
我用这样的方式打开就会是英文的
open -a /Applications/OCAuxiliaryTools.app /Volumes/DATA/oc_new/X64/EFI/OC/config.plist
![1](https://user-images.githubusercontent.com/5109711/149853617-873d4393-c47c-4499-abe1-8690608c6638.png)

如果是点ocat的图标，或是直接点config.plist来打开就是中文的，以前的版本就没有这个问题，最近几个更新版本才出现的。

**Comment by ic005k** [comment]
我按照你的方式操作，在我这边没问题，还是中文版的。
无论如何，我会分析一下原因的，感谢反馈。

**Comment by ic005k** [comment]
我是用最新版0072进行测试的。

**Comment by k2y1982** [comment]
搞不清楚了。074也是一样的。我也不纠结了，反正也能看懂，都用了这么久了。
![1](https://user-images.githubusercontent.com/5109711/149867909-3a9806de-47df-4ce9-8c07-6fffee86473d.png)

**Comment by ic005k** [comment]
我会分析一下的。
如果你是通过命令行始终打开同一个配置文件，可在“偏好设置”中选择“自动打开上次的文件”，这样在开启OCAT的时候，就会自动加载你上次关闭OCAT时打开的文件。

**Comment by k2y1982** [comment]
“自动打开上次的文件”并没有勾选。而且我的命令行有3个不同路径的plist。
open -a /Applications/OCAuxiliaryTools.app /Volumes/DATA/OC_res/X64/EFI/OC/config.plist
open -a /Applications/OCAuxiliaryTools.app /Volumes/DATA/oc_new/X64/EFI/OC/config.plist
open -a /Applications/OCAuxiliaryTools.app /Volumes/DATA/OC_xc/X64/EFI/OC/config.plist
3个不同仓库的oc，谁更新了，我就会去修改谁的plist。

**Comment by ic005k** [comment]
会不会跟“终端”的设置有关系？

**Comment by ic005k** [comment]
OCAT关于语言的实现原理是，启动的时候自动检测系统语言环境，如果非中文，则自动切换为英文。
看这个情况的话，好像终端处于英文的环境中？
还有，OCAT一直没有改动或优化这个语言模块，但你之前是正常的，后来变成英文了，是不是你的终端环境有了些变化？

**Comment by ic005k** [comment]
或者你找个老版本的OCAT再测试看看。
