### ISSUE TITLE
多硬盘挂载 ESP 分区问题

### ISSUE THREAD

**Issue by hzx505** [ic005k/QtOpenCoreConfig#11]
多硬盘挂载 ESP 分区问题

共3个硬盘
挂载 ESP 分区，打开的是非引导 EFI 分区 disk2s1（空的 无内容），实际引导是 disk1s1。
请作者 核实下，谢谢。
@ic005k 
================
diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                                                   *500.1 GB   disk0

/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *240.1 GB   disk1
   1:                        EFI EFI                     209.7 MB   disk1s1
   2:                 Apple_APFS Container disk3         120.0 GB   disk1s2
   3:       Microsoft Basic Data BOOTCAMP                119.8 GB   disk1s3

/dev/disk2 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *128.0 GB   disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                  Apple_HFS data HFS                127.7 GB   disk2s2

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +120.0 GB   disk3
                                 Physical Store disk1s2
   1:                APFS Volume macOS - 数据            64.4 GB    disk3s1
   2:                APFS Volume Preboot                 82.2 MB    disk3s2
   3:                APFS Volume Recovery                526.6 MB   disk3s3
   4:                APFS Volume VM                      4.3 GB     disk3s4
   5:                APFS Volume macOS                   10.8 GB    disk3s5

**Comment by ic005k** [comment]
目前程序是挂载所有的ESP分区，你目前是三块硬盘，有两个ESP分区，软件在挂载的时候，会有两次申请权限的过程，如果你取消了其中的一次权限申请，则被取消的那个ESP分区是不会被挂载的。
如果没有取消挂载的权限申请，那么ESP分区全部都会挂载上，这个时候你需要在文件管理器里面看看，多出了哪两个盘，打开你存放EFI的那个盘就可以了。
特别提醒：软件目前不具备自动识别你当前引导的EFI文件夹所在的ESP分区，同时挂载ESP分区之后，也不会自动打开被挂载的盘。
这块的功能，后面会考虑优化，欢迎更多的建议，感谢反馈！

**Comment by hzx505** [comment]
结论：非软件问题！

退出 我的 BOOTCAMP 虚拟机就跪出来了 EFI分区。

不管是 parallels 或 fusion BOOTCAMP、单盘或多盘 、OCC或CLOVER 都是这种情况。
刚好有2部机子 顺便验证一下。

**Comment by ic005k** [comment]
好的，有问题请随时留言。
