### ISSUE TITLE
ACPI add Selection button in context menu is working weirdly

### ISSUE THREAD

**Issue by fabiosun** [ic005k/QtOpenCoreConfig#110]
@ic005k not a great problem but here I have this behaviour for that menu

Grazie

https://user-images.githubusercontent.com/6358373/150165516-4e7ca08f-e0df-4744-8337-f44562a48c6a.mp4

**Comment by ic005k** [comment]
The problem has been fixed.
Feel free to find more problems or suggestions.

**Comment by fabiosun** [comment]
Thank you!
