### ISSUE TITLE
UIScale is set under both NVRAM and UEFI->Output!

### ISSUE THREAD

**Issue by fabiosun** [ic005k/QtOpenCoreConfig#115]
@ic005k 
In order to test your interesting app with as many systems and EFi as possible
I found this problem updating one
![Screenshot 2022-01-23 at 7 31 01 PM](https://user-images.githubusercontent.com/6358373/150692759-8c92d368-e7ad-4296-b84b-6d5dd92ac2bc.png)

Saving config removes all errors except the one indicated in the title
![Screenshot 2022-01-23 at 7 31 23 PM](https://user-images.githubusercontent.com/6358373/150692770-0a100814-c220-49bf-ae1d-84f8ba7623bd.png)

I don't know if it's an app or EFI problem that app does not solve

Thank you

**Comment by ic005k** [comment]
OCAT automatically corrects some low-level errors in the configuration file when saving it, such as whether it contains spaces, just so.
As for other high level errors, you must correct them yourself. OCAT does not do any of this for the user, it just gives you a clear hint that you may need to follow to deal with these problems.
This is part of OCAT's design philosophy.
