### ISSUE TITLE
Replacement Link for USBInjectAll in "Kext Upgrade URL" list

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/QtOpenCoreConfig#119]
Daliansky is continuing the development of `USBInjectAll.kext` with supports for the newest  platforms (500 and 600 series mainboards, etc) as well.

Here's the new link for the kext: https://github.com/daliansky/OS-X-USB-Inject-All

**Comment by ic005k** [comment]
Added. Feel free to provide more upgrade clues, thanks.
