### ISSUE TITLE
2020.12.07 Enabled 问题

### ISSUE THREAD

**Issue by fangf2018** [ic005k/QtOpenCoreConfig#12]
ACPI及Kernel新增条目Enabled状态更改无法保存 概率100%

**Comment by ic005k** [comment]
这个现象我这边目前没有复现，会一直关注这个问题的。在使能这个条目之前，是不是没有选择这个条目？

如论如何，已纳入bug追踪系统，欢迎更多的建议或问题，感谢反馈！

**Comment by fangf2018** [comment]
如何debug反馈数据给您

**Comment by ic005k** [comment]
你只需告诉我复现此问题的操作步骤即可。还有是哪个平台的，win还是mac或者linux？
比如在ACPI里面点击『增加条目』选择一个ACPI文件，此时新增条目的默认Enabled状态是true，此时选择该条目进行Enabled状态的更改，将之改为false，保存。如果打开这个保存的文件，该条目的Enabled还是处于true状态，说明状态更改没有保存。
Enabled的状态更改是实时显示的，勾选就变为true，去掉勾选就变为false。

除非有一种情况，在勾选Enabled时，其状态不变化，那就是你没有用鼠标点击该条目（也就是说选择这个条目），如果条目不被选择，则Enabled找不到主体，它的状态是不会有变化的，即使你来回勾选，Enabled的值也是不变。

关注中......

**Comment by ic005k** [comment]
这部分目前没有设置debug数据，不会有debug数据返回。
