### ISSUE TITLE
Backup EFI to Desktop does not work as expected

### ISSUE THREAD

**Issue by chriswayg** [ic005k/QtOpenCoreConfig#124]
## Backup EFI to Desktop "Backup EFI"  does not work as expected

Thanks for this excellent tool and for the frequent updates! It generally works very well and is easy to learn. I just came across this small issue when wanting to backup my currently active EFI.

[![Screen-Shot](https://i.postimg.cc/rppRZTVy/Screen-Shot-2022-01-28-at-8-00-32-PM.png)](https://postimg.cc/zy9f39H4)

### Reproduce

- Launch OCAuxilaryTools in Monterey (or Mojave)
- Mount ESP Partition and Open Config.plist using OCAuxilaryTools
- Click _Backup EFI to Desktop "Backup EFI"_ button or select from Menu
- nothing happens, no folder or zip file is created, no errors, no log found
- tested on macOS Monterey 12.2 and macOS Mojave 10.14.6
- tested with V202200091

### Expected Result

- A "Backup EFI" folder is created with a zipped up EFI inside
- the EFI to be backed up is expected to be the currently open EFI in OCAuxilaryTools, so it can be backed up before changes are made

### What does work?

- Menu > _Generate EFI on the Desktop_
- Then click _Backup EFI to Desktop "Backup EFI"_ button or select from Menu
- This actually creates a backup in the _Backup EFI_ folder, but not the one I want, just a backup from the newly created EFI on the Desktop

This is either a bug or a problem of lack of documentation (with user expectations being different from developer intentions).

**Comment by ic005k** [comment]
In fact, OCAT has already made a backup for you in the background, it is done silently, you can right click on the "Backup EFI" icon in the toolbar and select "Open backup directory", you will find the files already backed up there.
This backup is done silently, please note!

**Comment by chriswayg** [comment]
>  "Open backup directory", you will find the files already backed up there.

Thanks for your reply! With version V202220094 on **Monterey**, _Backup EFI to Desktop_ actually works and it creates a "Backup EFI" folder with the zipped EFI inside after clicking the button. Therefore, on Monterey this feature now works in the way I would expect. - On the other hand, no backup was created _silently_ without clicking the button first, which I checked with "Open backup directory". - Is there another hidden backup directory?

On **macOS 10.14.6** none of this works:  _"Open backup directory"_ as well as _"Backup EFI to Desktop"_ does nothing at all (just as detailed in my initial bug report). No errors either. Also, **_"Synchronize OC Main Program"_ is greyed out** (see screenshot) and cannot be started. I tried starting the app from the terminal, but still no error messages.

[![OCAT-Bug-Screen-Shot-2022-01-30-at-6-33-31-PM.png](https://i.postimg.cc/sx65B9FP/OCAT-Bug-Screen-Shot-2022-01-30-at-6-33-31-PM.png)](https://postimg.cc/jnfDmfSC)

I understand that this is a well designed GUI application which is mostly self-explanatory. Nevertheless, if you do have some documentation explaining how each feature is expected to work, please link me to it. I think I have read all that there is (linked from the main Readme), but I may have missed something.

**Comment by ic005k** [comment]
> On **macOS 10.14.6** none of this works: _"Open backup directory"_ as well as _"Backup EFI to Desktop"_ does nothing at all (just as detailed in my initial bug report). No errors either. Also, **_"Synchronize OC Main Program"_ is greyed out** (see screenshot) and cannot be started. I tried starting the app from the terminal, but still no error messages.

The reason why you can't backup is that the configuration file you opened is not in a complete EFI directory, so OCAT can't complete the backup.
The prerequisite for an OCAT backup is that the EFI target must be complete, otherwise the backup will not take place.

**Comment by ic005k** [comment]
For details you can refer to this question, which has a description of EFI directory integrity: https://github.com/ic005k/QtOpenCoreConfig/issues/77

**Comment by ic005k** [comment]
Please forgive me for not having much time to write the documentation. In the next version, OCAT will improve this and there will be a prompt telling the user why they can't backup.

**Comment by chriswayg** [comment]
> The reason why you can't backup is that the configuration file you opened is not in a complete EFI directory, so OCAT can't complete the backup. The prerequisite for an OCAT backup is that the EFI target must be complete, otherwise the backup will not take place.

> (Google Translate of #77 ) OCAT will automatically check the integrity of each directory under EFI, otherwise the sync button will be grayed out. Main check: 
    EFI/OC 
    EFI/BOOT 
    EFI/OC/Drivers 
    
Ok, I finally found out why my fully functional and complete OpenCore installation would not backup with OCAT: I used the new **_Launcher Option_** in OpenCore, which does not require a BOOT directory or boot files. Therefore I had deleted the BOOT directory on my main OC booter. Only the debug OC booter still had the boot file and directory.

> If everything is set up correctly, the first boot will have OpenCore create a new boot option in our BIOS (pointing to EFI/OC/OpenCore.efi) and future boots will update the entry making sure it's correct and ensuring it is still present. **This now allows us to remove BOOTx64.efi** and not worry about other OSes overwriting the EFI/BOOT/BOOTx64.efi path.
[Setting up the LauncherOption | OpenCore Post-Install](https://dortania.github.io/OpenCore-Post-Install/multiboot/bootstrap.html#using-launcheroption)

SOLUTION: I recreated the `EFI/BOOT ` directory on my main OC booter, and now OCAT recognises it as valid. 

A user prompt or error message from the UI would definitely be helpful when OCAT cannot find a valid OC directory structure.

**Comment by ic005k** [comment]
The new version of OCAT has excluded EFI/BOOT, so now you don't have to do something extra for EFI/BOOT.
