### ISSUE TITLE
[Feature Request] Add Preset Menu to Kernel > Emulate section

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/QtOpenCoreConfig#128]
SInce certain configurations require Fake a CPU ID, a preset Menu for selecting which CPU should be emulatad would be great . The selected preset will then add the required data to `Cpuid1Data` and `Cpuid1Mask` fields.

**Examples**:

- Emulate Haswell (0x0306C3):
Cpuid1Data: C3 06 03 00 00 00 00 00 00 00 00 00 00 00 00 00 
Cpuid1Mask: FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00

- Emulate Broadwell (0x0306D4):
Cpuid1Data: D4 06 03 00 00 00 00 00 00 00 00 00 00 00 00 00 
Cpuid1Mask: FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00

- Emulate Coffe Lake:
Cpuid1Data: EA 06 09 00 00 00 00 00 00 00 00 00 00 00 00 00
Cpuid1Mask: FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00

- Emulate Comet Lake U42 (0x0806EC): 
Cpuid1Data: EC 06 08 00 00 00 00 00 00 00 00 00 00 00 00 00 
Cpuid1Mask: FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00

- Emulatte Comet Lake (0x0A0655):
Cpuid1Data: 55 06 0A 00 00 00 00 00 00 00 00 00 00 00 00 00 
Cpuid1Mask: FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by ic005k** [comment]
Can you provide complete data? I see how to implement it.

**Comment by ic005k** [comment]
Features have been added, feel free to provide any upgrade clues.

**Comment by 5T33Z0** [comment]
Thanks for adding this feature!

**Addendum**: a list of supported CPUIDs for macOS can be found in the "Intel CPU Support Chart" of the [Dortania's OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html#cpu-support)

But the CPU IDs have to be converted into Little Endian and filled up with zeros so the mask becomes 16 bit (32 digits)

For example: Coffee Lake, CPUID (HEX): 0x0906EA

**Conversion**:

- Drop "0x"
- Create pairs of 2 of the rest: 09 06 EA
- Reorder the pairs from last to first: EA 06 09
- Add zeros until you have 32 digits in total: EA 06 09 00 00 00 00 00 00 00 00 00 00 00 00 00
- `Cpuid1Mask` always addresses the first 4 bits: FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by ic005k** [comment]
I'm sure the users will be very grateful that you have compiled and made this information available.
Please feel free to let me know if any of these are updated and I will update them in OCAT.

**Comment by fabiosun** [comment]
<img width="293" alt="Screenshot 2022-02-02 at 1 01 20 PM" src="https://user-images.githubusercontent.com/6358373/152149960-8dad5522-f49e-4efc-ae72-b453e92f0a7b.png">
a typo in Comet lake Preset

**Comment by 5T33Z0** [comment]
Coffee Lake is spelled wrong as well. It's spelled with Double "e". My bad.

**Comment by 5T33Z0** [comment]
The typos are gone now, but the data for Coffee Lake is missing:

![screenshot](https://user-images.githubusercontent.com/76865553/152290619-7999591f-9112-42b2-96d5-40cf414e022c.png)

**Comment by fabiosun** [comment]
@ic005k 
is it possible to add **Emulate Cascade Lake**:

**Cpuid1Data**: 57 06 05 00 00 00 00 00 00 00 00 00 00 00 00 00
**Cpuid1Mask**: FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00

thank you

**Comment by 5T33Z0** [comment]
Why would you want to emulate a CPU which is not supported by macOS? The whole idea is emulating a newer CPU unsupported by macOS by using a mask of a supported CPU.

**Comment by fabiosun** [comment]
It is useful when you use a VM system with Proxmox or Unraid.

**Comment by fabiosun** [comment]
"Why would you want to emulate a CPU which is not supported by macOS? "
Intel Xeon W-3275
New macPro
