### ISSUE TITLE
OC_ATTR_USE_POINTER_CONTROL新增

### ISSUE THREAD

**Issue by fangf2018** [ic005k/QtOpenCoreConfig#13]
OC_ATTR_USE_POINTER_CONTROL新增

**Comment by ic005k** [comment]
好的，下个版本添加。
在没有添加这个自动计算之前，请直接填入数值，比如17（1 + 16）,16负责OC引导界面的鼠标。
qtocc内置冗余机制，这个自动计算的缺失不会影响到你填入的数字及相应的功能。
欢迎更多的建议，感谢反馈！

**Comment by ic005k** [comment]
> OC_ATTR_USE_POINTER_CONTROL新增

已添加，请下载最新的版本。
