### ISSUE TITLE
可不可以把同版本的opencore也上传

### ISSUE THREAD

**Issue by fangf2018** [ic005k/QtOpenCoreConfig#14]
这样，就避免更新的版本与qtopencore不对应，最近更新频繁，很难找到对应版本

**Comment by ic005k** [comment]
里面内置的数据库就是同版本的OC，你只需打开你的Config.plist文件，选择“在桌面上生成EFI”文件夹即可，如果数据库里面有缺失的东西，你自己补全即可（或者将你的相关文件拷贝到数据库，再生成EFI）。
也就是说升级OC，在QtOCC引进数据库机制之后，现在是非常简单的一件事情。

**Comment by ic005k** [comment]
非常抱歉的是我没太多时间写文档，否则这些功能你们应该很早就知道了。

**Comment by ic005k** [comment]
如果不想使用内置的数据库，可以直接将新版本的OC拷贝到你EFI目录，选择合并（不要替换，否则kext等目录将变成空目录），再用软件保存一下你的Config.plist即可。总之，都是非常简单的事情。

**Comment by fangf2018** [comment]
非常nice
