### ISSUE TITLE
提议：集成OC-Gen-X

### ISSUE THREAD

**Issue by Z-fly** [ic005k/QtOpenCoreConfig#16]
https://github.com/Pavo-IM/OC-Gen-X

**Comment by ic005k** [comment]
感谢建议，其实配置文件数据库里面已经涵盖了OC-Gen-X功能，只需将各种平台的通用配置文件放入数据库即可，只不过目前这些通用配置文件没时间整理。ocat的数据库是完全开放型的，欢迎大家一起来整理各种硬件环境下的配置文件。新年快乐！

**Comment by Z-fly** [comment]
> 感谢建议，其实配置文件数据库里面已经涵盖了OC-Gen-X功能，只需将各种平台的通用配置文件放入数据库即可，只不过目前这些通用配置文件没时间整理。ocat的数据库是完全开放型的，欢迎大家一起来整理各种硬件环境下的配置文件。新年快乐！

集成是有两种概念，一种是外挂，OC-Gen-X直接原文件独立包含进来，这样维护还是直接由OC-Gen-X来做。你说的这种是内嵌OC-Gen-X的功能，但这样要耗费更多的维护精力。

**Comment by ic005k** [comment]
> > 感谢建议，其实配置文件数据库里面已经涵盖了OC-Gen-X功能，只需将各种平台的通用配置文件放入数据库即可，只不过目前这些通用配置文件没时间整理。ocat的数据库是完全开放型的，欢迎大家一起来整理各种硬件环境下的配置文件。新年快乐！
> 
> 集成是有两种概念，一种是外挂，OC-Gen-X直接原文件独立包含进来，这样维护还是直接由OC-Gen-X来做。你说的这种是内嵌OC-Gen-X的功能，但这样要耗费更多的维护精力。

OCAT的最终效果可能是在各个平台能自动检测硬件的型号，并生成EFI，时间允许我会慢慢实现这些。
因为一开始OCAT的设计目标就是多平台、智能化、灵活的模块结构以适应OC的快速迭代等等。
还有，当数据库的样本数量积累得足够多的时候，一切都将变得很容易。
