### ISSUE TITLE
配置文件跨版本升级问题

### ISSUE THREAD

**Issue by Z-fly** [ic005k/QtOpenCoreConfig#17]
https://macx.top/9890.html
OpenCore不同版本基本上无法100%兼容。我不知道现在打开一个0.5的配置文件会不会出错。
所以现在的一个开发点就是，增加一个配置文件升级的功能模块。OCAT智能的显示OpenCore新版本变化，根据Sample.plist智能移植。
![image](https://user-images.githubusercontent.com/10470892/107875038-8eb36b80-6ef8-11eb-9556-0356459592bf.png)
未来OCAT可实现的功能是升级当前EFI所有文件。（参考上面的教程）

**Comment by ic005k** [comment]
OCAT一直具备这个功能，只需打开旧版的配置文件，保存一下即可，再辅以OC验证调整配置文件的部分参数，非常简单的。
当然，如果不使用内置的数据库的话，请自行升级OC到最新版。
总之，一切都非常容易，没那么复杂。

**Comment by Z-fly** [comment]
好吧，未来可以自动从GitHub下载最新kext吗？

**Comment by ic005k** [comment]
你说的升级EFI所有文件，只需在编辑菜单下选择『在桌面上产生EFI文件夹』，OCAT会根据你当前打开的配置文件，自动产生一个全新的EFI，你拷贝这个EFI到你的ESP分区即可（当然请记得备份之前的EFI数据，以防不时之需）。

**Comment by ic005k** [comment]
> 好吧，未来可以自动从GitHub下载最新kext吗？

这个估计近期不会考虑，但我会定期更新数据库，里面的kext基本都是最新版本的。其实每个人都可以自己弄个属于自己的数据库，或者分享，或者私用，都很灵活的。总之，我的初衷是让大家都能参与进来。

**Comment by ic005k** [comment]
一言以蔽之，我是不会主动去解包别人的EFI来补充数据库的内容，没那个精力，如果大家愿意分享，我就补充一下数据库的内容，否则就维持现状，但是我会把台子搭好。

**Comment by Z-fly** [comment]
我想了下，基于不要重复造轮子，现在黑果小兵已经做了配置文件汇总，那可以直接把他汇总好的markdown嵌入到数据库里，然后加个搜索框，匹配不到的跳转到搜索引擎，例如GitHub,Google。

**Comment by Z-fly** [comment]
https://user-images.githubusercontent.com/10470892/107881471-7145c800-6f1f-11eb-83ba-81fb5a18ca63.mp4
发现BUG？

**Comment by Z-fly** [comment]
最后是配置比较，虽然有命令行的工具直接用。
建议做个图形界面的，像ProperTree那样。然后有配置比较这个功能。
![image](https://user-images.githubusercontent.com/10470892/107881852-1d3be300-6f21-11eb-84c7-a792b411b731.png)
OCAT如果能集成这些东西的话，那就有集大成于一体的效果了。

**Comment by Z-fly** [comment]
说这么多有点像产品经理了，这些纯粹是个人建议，你可只做未来规划的参考。

**Comment by ic005k** [comment]
> https://user-images.githubusercontent.com/10470892/107881471-7145c800-6f1f-11eb-83ba-81fb5a18ca63.mp4
> 发现BUG？

看不见里面的内容？全黑的？能否用文字来描述一下？谢谢！

**Comment by ic005k** [comment]
总之，非常感谢你的建议。我会不断完善这个产品。

**Comment by ic005k** [comment]
对了，有时间可以关注一下我另外的两个产品，欢迎多提些建议：
https://www.insanelymac.com/forum/topic/345512-open-source-cross-platform-plist-file-editor-plistedplus/
https://www.insanelymac.com/forum/topic/344860-open-source-cross-platform-dsdtssdt-ide/

**Comment by Z-fly** [comment]
> > https://user-images.githubusercontent.com/10470892/107881471-7145c800-6f1f-11eb-83ba-81fb5a18ca63.mp4
> > 发现BUG？
> 
> 看不见里面的内容？全黑的？能否用文字来描述一下？谢谢！

https://user-images.githubusercontent.com/10470892/107896732-22754e00-6f72-11eb-8f91-70c5cb92d4ab.mp4

**Comment by Z-fly** [comment]
> 对了，有时间可以关注一下我另外的两个产品，欢迎多提些建议：
> https://www.insanelymac.com/forum/topic/345512-open-source-cross-platform-plist-file-editor-plistedplus/
> https://www.insanelymac.com/forum/topic/344860-open-source-cross-platform-dsdtssdt-ide/

我英语不好，国外的论坛就算了

**Comment by ic005k** [comment]
> > > https://user-images.githubusercontent.com/10470892/107881471-7145c800-6f1f-11eb-83ba-81fb5a18ca63.mp4
> > > 发现BUG？
> > 
> > 
> > 看不见里面的内容？全黑的？能否用文字来描述一下？谢谢！
> 
> QQ录制的就是黑屏，还要转码一下才行
> 
>  1.mp4

哦，这个原则上是不允许被拖动的，我回头改下。感谢提供！

**Comment by ic005k** [comment]
> > > https://user-images.githubusercontent.com/10470892/107881471-7145c800-6f1f-11eb-83ba-81fb5a18ca63.mp4
> > > 发现BUG？
> > 
> > 
> > 看不见里面的内容？全黑的？能否用文字来描述一下？谢谢！
> 
> QQ录制的就是黑屏，还要转码一下才行
> 
>  1.mp4

这个问题已修复，请下载最新的版本。我对问题是零容忍，只要发现了问题，我这边就会立马修改。

**Comment by ic005k** [comment]
> 我想了下，基于不要重复造轮子，现在黑果小兵已经做了配置文件汇总，那可以直接把他汇总好的markdown嵌入到数据库里，然后加个搜索框，匹配不到的跳转到搜索引擎，例如GitHub,Google。

感谢提供这么细致的操作。但我可能不会这么做，因为OCAT的思路是通过一个配置文件+ACPI或kext的个性化重命名来完成一个配置的过程，非常简洁。

**Comment by ic005k** [comment]
> 最后是配置比较，虽然有命令行的工具直接用。
> 建议做个图形界面的，像ProperTree那样。然后有配置比较这个功能。
> ![image](https://user-images.githubusercontent.com/10470892/107881852-1d3be300-6f21-11eb-84c7-a792b411b731.png)
> OCAT如果能集成这些东西的话，那就有集大成于一体的效果了。

其实对于普通用户来说，是不会去关心或比较这些不同的内容，他们关心的是能否平稳升级。
还有OC每期都会附带有一个Differences.pdf文件，这个文件就是告诉大家哪些地方发生了变化，而且内容非常详尽。
所以从一开始我就没考虑过文件的比较的问题，更多考虑的是OC升级过程中数据的智能迁移。
