### ISSUE TITLE
有一个小bug

### ISSUE THREAD

**Issue by lingering2019** [ic005k/QtOpenCoreConfig#18]
你好，有一个小bug，就是把空壳的kext文件如USBPorts.kext拖进kernel时，正确的ExecutablePath应该为空的，但实际却是Contents/MacOS/,这样就出错了的。

**Comment by ic005k** [comment]
已更改，请下载最新的版本。感谢反馈！

**Comment by lingering2019** [comment]
多谢，有问题再向你反馈，越来越完美。
