### ISSUE TITLE
CentOS6无法打开，缺少GLIBC

### ISSUE THREAD

**Issue by Z-fly** [ic005k/QtOpenCoreConfig#19]
![image](https://user-images.githubusercontent.com/10470892/109259980-43725480-7838-11eb-9273-4178b3c36111.png)

**Comment by Z-fly** [comment]
因为是老电脑上的，如果针对其编译维护成本过高，那就算了吧

**Comment by Z-fly** [comment]
补充说明：CentOS6最高是GLIBC_2.17，我刚刚尝试自己编译GLIBC_2.27，然后缺少各种依赖

**Comment by Z-fly** [comment]
如果有编译文档的话，我试试自行编译

**Comment by ic005k** [comment]
这个问题很简单，我发一个没有打包成AppImage的原始Linux包，你重新找下依赖看看：https://github.com/ic005k/QtOpenCoreConfig/releases/download/20210226/OC.Auxiliary.Tools-Linux.tar.xz

**Comment by ic005k** [comment]
或者重新下载个GLIBC_2.17的包试试：https://pkgs.org/download/libc.so.6(GLIBC_2.27)(64bit)

**Comment by ic005k** [comment]
如果你需要重新编译APP，可以在这里尝试下载Qt https://download.qt.io/archive/qt/ ，然后对OCAT的源码进行编译。我不确定哪个Qt版本适合你的系统，所以你需要尝试下不同的Qt版本。

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/109441529-6e46ed80-7a70-11eb-9158-c0fa1585db44.png)

**Comment by Z-fly** [comment]
CentOS6安装不了GLIBC_2.27

**Comment by Z-fly** [comment]
QT环境太难配了

**Comment by ic005k** [comment]
嗯嗯，等忙完这阵子，一起来想想办法

**Comment by Z-fly** [comment]
你现在三种客户端是分别在不同平台编译的吗？

**Comment by Z-fly** [comment]
最好的解决办法就是在centos6上搭建QT开发环境，然后在上面开发

**Comment by ic005k** [comment]
> 你现在三种客户端是分别在不同平台编译的吗？

是的，但Linux我只是使用了乌班图的最新版进行构建，也没有那么多闲置的机器和时间在其它Linux上构建。

**Comment by ic005k** [comment]
> 最好的解决办法就是在CentOS6上搭建QT开发环境，然后在上面开发

这个等我有足够的时间倒是可以考虑。不过你也可以考虑将CentOS6升级到7，我会继续关注这个问题的。

**Comment by Z-fly** [comment]
> > 最好的解决办法就是在CentOS6上搭建QT开发环境，然后在上面开发
> 
> 这个等我有足够的时间倒是可以考虑。不过你也可以考虑将CentOS6升级到7，我会继续关注这个问题的。

你说下这个项目的所有依赖库吧，我自己看看能否搭建开发环境

**Comment by ic005k** [comment]
> 你说下这个项目的所有依赖库吧，我自己看看能否搭建开发环境

这个项目不依赖任何第三方的库，也就是说只要你安装好Qt的开发环境，能编译Qt自带的demo，就可以编译这个项目了。
但有一点我不能肯定的是，目前我是基于Qt5.15编写和调试的代码，至于在较低的Qt版本上（比5.9.9更低，5.9.9经过测试，没问题），会不会存在语法错误，这个不能确定。

**Comment by Z-fly** [comment]
https://download.qt.io/archive/qt/5.9/5.9.9/qt-opensource-linux-x64-5.9.9.run
有什么好办法下这个文件，，

**Comment by ic005k** [comment]
> 有什么好办法下这个文件

在win或mac下用迅雷下载，拷贝到linux里面安装即可

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/109901752-87e86f00-7cd4-11eb-8b2e-3982b16e1fb9.png)

**Comment by Z-fly** [comment]
我安装一下GCC7.5再试试

**Comment by ic005k** [comment]
Qt安装完成之后，直接通过Qt的IDE Qt Creator打开项目的工程文件OC Auxiliary Tools.pro进行编译。
之前请确保能编译Qt自带的例子，就说明配置环境没问题了。

**Comment by Z-fly** [comment]
经过测试，CentOS6上安装Qt5.9.9，无法使用Qt Creator

**Comment by Z-fly** [comment]
使用命令行编译，报以下错误。
[root@development QtOpenCoreConfig]# make
/home/Qt5.9.9/5.9.9/gcc_64/bin/uic aboutdialog.ui -o ui_aboutdialog.h
/home/Qt5.9.9/5.9.9/gcc_64/bin/uic dlgdatabase.ui -o ui_dlgdatabase.h
/home/Qt5.9.9/5.9.9/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h
mainwindow.ui: Warning: The name 'layoutWidget' (QWidget) is already in use, defaulting to 'layoutWidget1'.
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../Qt5.9.9/5.9.9/gcc_64/include -I../Qt5.9.9/5.9.9/gcc_64/include/QtWidgets -I../Qt5.9.9/5.9.9/gcc_64/include/QtGui -I../Qt5.9.9/5.9.9/gcc_64/include/QtXml -I../Qt5.9.9/5.9.9/gcc_64/include/QtNetwork -I../Qt5.9.9/5.9.9/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../Qt5.9.9/5.9.9/gcc_64/mkspecs/linux-g++ -o aboutdialog.o aboutdialog.cpp
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../Qt5.9.9/5.9.9/gcc_64/include -I../Qt5.9.9/5.9.9/gcc_64/include/QtWidgets -I../Qt5.9.9/5.9.9/gcc_64/include/QtGui -I../Qt5.9.9/5.9.9/gcc_64/include/QtXml -I../Qt5.9.9/5.9.9/gcc_64/include/QtNetwork -I../Qt5.9.9/5.9.9/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../Qt5.9.9/5.9.9/gcc_64/mkspecs/linux-g++ -o commands.o commands.cpp
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../Qt5.9.9/5.9.9/gcc_64/include -I../Qt5.9.9/5.9.9/gcc_64/include/QtWidgets -I../Qt5.9.9/5.9.9/gcc_64/include/QtGui -I../Qt5.9.9/5.9.9/gcc_64/include/QtXml -I../Qt5.9.9/5.9.9/gcc_64/include/QtNetwork -I../Qt5.9.9/5.9.9/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../Qt5.9.9/5.9.9/gcc_64/mkspecs/linux-g++ -o dlgdatabase.o dlgdatabase.cpp
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../Qt5.9.9/5.9.9/gcc_64/include -I../Qt5.9.9/5.9.9/gcc_64/include/QtWidgets -I../Qt5.9.9/5.9.9/gcc_64/include/QtGui -I../Qt5.9.9/5.9.9/gcc_64/include/QtXml -I../Qt5.9.9/5.9.9/gcc_64/include/QtNetwork -I../Qt5.9.9/5.9.9/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../Qt5.9.9/5.9.9/gcc_64/mkspecs/linux-g++ -o main.o main.cpp
main.cpp: 在函数‘int main(int, char**)’中:
main.cpp:15:22: 错误：‘setHighDpiScaleFactorRoundingPolicy’不是‘QGuiApplication’的成员
     QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:15:62: 错误：‘Qt::HighDpiScaleFactorRoundingPolicy’尚未声明
     QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/109943946-a8361f00-7d10-11eb-8229-f930f372b496.png)
为了手动编译Qt Creator，我下了各种依赖，还是不行，

**Comment by ic005k** [comment]
> main.cpp:15:62: 错误：‘Qt::HighDpiScaleFactorRoundingPolicy’尚未声明
> QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);

哦，这个跟不支持HiDPI有关（特别是老系统上），你将main.cpp里面的14、15行注释掉，再编译看看，就是下面的两行：

qputenv("QT_ENABLE_HIGHDPI_SCALING", "1");
QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);

**Comment by Z-fly** [comment]
编译完成，但无法执行
![image](https://user-images.githubusercontent.com/10470892/109947107-ee40b200-7d13-11eb-817a-7d5dee146b79.png)

**Comment by Z-fly** [comment]
https://superuser.com/questions/1451321/qt-startup-error-symbol-lookup-error-libqt5xcbqpa-so-5-undefined-symbol-ft-g

**Comment by Z-fly** [comment]
http://download.savannah.gnu.org/releases/freetype/freetype-2.10.3.tar.xz
手动编译这个安装后，还是报同样错

**Comment by Z-fly** [comment]
https://blog.csdn.net/u010168781/article/details/89681674

看了这篇的，我想基本上宣告无解吧，还有希望吗？

**Comment by ic005k** [comment]
> https://blog.csdn.net/u010168781/article/details/89681674
> 
> 看了这篇的，我想基本上宣告无解吧，还有希望吗？

这个也不好说，有时间的话，你可再研究看看，总之有结果，告知一声

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/110076824-14bc2700-7dc0-11eb-996e-f0347ab991fb.png)
QT5.1好像可以用

**Comment by Z-fly** [comment]
![Uploading image.png…]()

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/110077218-b5aae200-7dc0-11eb-9810-e21c6308c80a.png)
普通的Demo可以用

**Comment by ic005k** [comment]
能打开ocat的项目文件吗？

**Comment by Z-fly** [comment]
> 能打开ocat的项目文件吗？

![image](https://user-images.githubusercontent.com/10470892/110086643-96ff1800-7dcd-11eb-9057-02c36eb11a65.png)

**Comment by Z-fly** [comment]
编译不了

**Comment by Z-fly** [comment]
@ic005k 我感觉有戏

**Comment by ic005k** [comment]
> 我感觉有戏

好，等你的好消息

**Comment by Z-fly** [comment]
> > 我感觉有戏
> 
> 好，等你的好消息

我是已经卡在这了，它报代码的错，那要看你能不能解决，如果是pyqt5我还懂点，c++我也不懂

**Comment by ic005k** [comment]
> 它报代码的错

估计这个错误可能跟Qt的版本太低有关系，不支持一些新的行为

**Comment by ic005k** [comment]
实在不行就先不弄了，毕竟是老系统了。
