### ISSUE TITLE
Cannot modify <data>

### ISSUE THREAD

**Issue by Tandem91** [ic005k/QtOpenCoreConfig#2]
Hi, when I try to modify Data, the old value come back

**Comment by ic005k** [comment]
Can you be more specific? Modify data in ACPI or NVRAM?

**Comment by Tandem91** [comment]
DeviceProperties
example audio
PciRoot(0x0)/Pci(0x1b,0x0)
 - layout-id | Data | 01000000

**Comment by ic005k** [comment]
ok, I understand. DataClass can only be entered manually at present. The next version will be placed in a drop-down list box, which can be freely selected, eliminating the need for manual input.

**Comment by ic005k** [comment]
Your problem has been resolved, please download the latest version.

**Comment by Tandem91** [comment]
Thanks! 
It's work now
