### ISSUE TITLE
[enhancement] Bitfield values better seen as hex ones (0x.....) instead of decimal

### ISSUE THREAD

**Issue by nms42** [ic005k/QtOpenCoreConfig#21]
Some of values in config.plist actually are bits. It would be better to see that as hex.

**Comment by ic005k** [comment]
Could you please elaborate on this, for example, by giving an example? Thank you.

**Comment by nms42** [comment]
Well,
For example, Misc/Debug/Target is not a number, rather list of bits. To align that fact with documentation it would be better to show it in hex. Decimal 67 ==> 0x43.

**Comment by nms42** [comment]
There are some other values with such property too.

**Comment by ic005k** [comment]
Okay, understood. In a later release, I will add a hex edit box next to the decimal edit box, so that the two can be edited simultaneously. Thanks for the feedback and more suggestions are welcome.

**Comment by ic005k** [comment]
> Some of values in config.plist actually are bits. It would be better to see that as hex.

This feature has been added, please download the latest version.
