### ISSUE TITLE
本来是0.6.6版本，编辑保存了一下，开机报错了。

### ISSUE THREAD

**Issue by einsqing** [ic005k/QtOpenCoreConfig#22]
我看到好像oc 0.6.7是新增了3个属性，能优化一下这个么？

**Comment by ic005k** [comment]
目前已经支持了0.6.7正式版。你光是保存了配置文件（相当于只升级了配置文件），而没有升级OC，那肯定是会报错的。你必须将OC升级到0.6.7才不会报错，这样配置文件和OC才是一个完整的统一。

**Comment by ic005k** [comment]
关于如何升级OC，你可以参考下面的这个：https://github.com/ic005k/QtOpenCoreConfig/issues/14

**Comment by k2y1982** [comment]
开发板更新到0.6.8了吗？支持不？

**Comment by ic005k** [comment]
> 开发板更新到0.6.8了吗？支持不？

只要OC验证通过，就支持。这个和OC的版本没有任何关系，有关系的仅仅是OC是否增加或删除了一些选项。
比如OC升级到了1.0，但没有增加或删除任何新的选项，目前的OCAT依然适用。

所以你只需打开0.6.8的配置文件SampleCustom.plist，用OC验证看看有没有新的东西添加，如果没有，则OCAT就支持0.6.8的编辑。
