### ISSUE TITLE
bug报告及建议

### ISSUE THREAD

**Issue by lingering2019** [ic005k/QtOpenCoreConfig#23]
在编辑某一项目时，如光标不是在最后的任意位置，按删除键时，则光标自动跳到最后的位置，这显然是有问题的。在可编辑的任何项目上，均是如此。另外，撤销功能的，建议不是按单个字符一个一个的恢复，而是整项恢复，PlistEdit Pro中的undo功能就是这样的，更方便。特意对比了PlistEDPlus中对应的功能，编辑项目时光标则无以上自动跳转问题，且撤销功能是整项恢复的。

**Comment by ic005k** [comment]
下个版本修复这个问题，感谢反馈。至于撤消，后面也会有优化的。

**Comment by ic005k** [comment]
问题已修复，撤消也采用整体的方式，同时用回车来确认修改（通常的做法）。
明天发布，今天有些晚了。
我对问题是零容忍，欢迎发现更多的问题。

**Comment by lingering2019** [comment]
多谢多谢。
