### ISSUE TITLE
热更新功能

### ISSUE THREAD

**Issue by Z-fly** [ic005k/QtOpenCoreConfig#24]
现在每次更新都要下完整的压缩包，这样不是很方便

建议写一个启动器，检查网络上的最新版，获取并覆盖本地文件。效果就和OpenCore Configurator一样。
中国大陆境内可用加速下载地址：https://ghproxy.com

**Comment by ic005k** [comment]
后面有精力的话，完全可以考虑这个。因为OCAT是跨平台的，如果采用增量更新，涉及到的方方面面会稍微多些。
目前软件处于迅速迭代期，等功能完善了，估计也就是两三个月甚至半年更新一次（主要看OC的配置文件是否增减内容）。
但如论如何，OCAT将会朝着越来越好的方向发展。感谢建议。
