### ISSUE TITLE
强烈建议把OpenCore开发版与正式版区分开

### ISSUE THREAD

**Issue by Z-fly** [ic005k/QtOpenCoreConfig#25]
OpenCore Configurator这点就做得很好，编辑器提供了个选项，可以手动指定我要编辑哪个版本。
现在相当于只能编辑开发版的配置文件，我拿0.6.7的配置编辑后它就变0.6.8的格式了。
![image](https://user-images.githubusercontent.com/10470892/110484601-c3949600-8125-11eb-8d65-093ca29c2dcb.png)

结果就报错了
![image](https://user-images.githubusercontent.com/10470892/110484972-20904c00-8126-11eb-99c2-a8d6c0fddcf0.png)

**Comment by Z-fly** [comment]
我是觉得可以像OpenCore Configurator那样集成两个OpenCore版本（开发版与正式版）更新，因为我是一直使用正式版的OpenCore对我的机型更新维护。

这么一想还是网页版的编辑器最符合需求，把不同时期的网页版归档就行。
https://galada.gitee.io/opencoreconfiguratoronline/
这个issues先开在这，看看其他人还有没有更好的想法

**Comment by ic005k** [comment]
其实在Mac下，你可以完全使用OCC，它做的非常细致，包括区分OC版本，OC的修改版都支持，而且是老牌的配置器，从18年就开始了，也非常成熟。

我一开始的重心其实是放在QtiASL上面，这是一个有技术含量的东西。配置器这类东西确实没什么技术含量，纯体力活，后来没办法，特么的只能硬着头皮做下去，所以才有了后来的搜索等功能，总之OCAT必须带点技术含量，才有做下去的意义。

我最近在PlistEDPlus里面增加了对OC的支持，感兴趣的话，你可以试用一下。

至于网页版，也是一个非常有用的补充，甚至DSDT的编辑都有网页版的。
总之，我是非常欢迎各种类似的软件和实现形式出现，大家可以互相学习和提高。
