### ISSUE TITLE
感觉这个描述怪怪的

### ISSUE THREAD

**Issue by w19996** [ic005k/QtOpenCoreConfig#27]
![截屏2021-03-16 上午11 01 47](https://user-images.githubusercontent.com/54472022/111250197-e18f5880-8647-11eb-8351-7eefa224d88a.png)
双重否定

**Comment by ic005k** [comment]
哦，这个翻译有点滞后，也一直没时间来检查和更新。我查了下最新的说明书，内容已更改为：

Note: While the option is not expected to harm unaffected firmware, its use is recommended only when specifically required.

翻译如下：
注意：虽然预计该选项不会损害未受影响的固件，但只建议在特别需要时使用。

**Comment by ic005k** [comment]
坦率地讲，这些翻译要逐一检查和更新，确实需要花费很大的精力和时间，特别是在OC还在不断变化和完善的过程中。欢迎你们提供线索，我来更改。
感谢反馈。

**Comment by ic005k** [comment]
坦率地讲，这些翻译要逐一检查和更新，确实需要花费很大的精力和时间，特别是在OC还在不断变化和完善的过程中。欢迎你们提供线索，我来更改。
感谢反馈。

**Comment by w19996** [comment]
只是突然发现了就反馈了一下,不过没有什么影响,还是感谢您写了这么好的程序

**Comment by ic005k** [comment]
这个翻译已更新，下个版本发布
