### ISSUE TITLE
希望能加入不同OC版本的切换

### ISSUE THREAD

**Issue by ssrkaze** [ic005k/QtOpenCoreConfig#30]
我目前使用的OC版本是0.6.8，在使用20210420的OC Auxiliary Tools打开OC配置文件，OC验证就会变红，提示

> OCS: Failed to parse string field as value with type boolean and <Auto> contents, context <CustomDelays>!
   OCS: Missing key ForgeUefiSupport, context <Quirks>!
   OCS: Missing key ReloadOptionRoms, context <Quirks>!

接着，工具会在保存时自动加入ForgeUefiSupport、ReloadOptionRoms这两个选项，然后在开机时，OC就会报错：

> OCS: No schema for ForgeUefiSupport at 3 index, context <Quirks>!
    OCS: No schema for ReloadOptionRoms at 6 index, context <Quirks>!

我查了下附在OpenCore-0.6.8-RELEASE中的文档，发现并没有这两个选项，这才发现是在 20210416 版本加入的属于OC 0.6.9的新条目。

这里有个小小的建议，希望能在工具中切换当前编辑的文件所属的OC版本，针对不同版本显示与隐藏一些条目，同时使用不同版本所拥有的条目来进行OC验证，或者是将适配不同版本的OC作为不同的branch来进行发布，然后在master分支的readme文档中加入跳转链接。

**Comment by ic005k** [comment]
这个问题我之前也回答过：https://github.com/ic005k/QtOpenCoreConfig/issues/25

遇到这种情况，首先建议你通过“升级OC主程序”的功能将OC升级到最新版。如果你不愿意升级到最新版，只能下载旧版的针对0.6.8的进行编辑了，我在每个发行版本下面都明确注明了OC的版本。比如0.6.8的最后版本在这里：https://github.com/ic005k/QtOpenCoreConfig/releases/tag/20210415，再往上走，就是0.6.9了。

其实我也想做个版本的区分，这个都非常简单，但实属没必要，因为OC一直在变化中，使用最新的OC是最佳选择（问题更少、性能更好）。
所以后面可能也不会考虑区分OC的版本，会一如既往地保持和最新的OC完全同步。
同时，工作之余能利于的零碎时间也非常有限，所以目前暂时只能这样了，感谢建议，同时欢迎更多的想法和创意。

**Comment by ic005k** [comment]
对了，OCAT新加入的一键升级功能“升级OC主程序”是一个非常便利的升级OC工具，你可试下。
