### ISSUE TITLE
请同步更新

### ISSUE THREAD

**Issue by lingering2019** [ic005k/QtOpenCoreConfig#31]
查阅官方最新的Configuration.pdf中40-41页，PickerAttributes下有增加一项：0x0040 — OC_ATTR_USE_MINIMAL_UI, use minimal UI display, no Shutdown or Restart buttons, affects OpenCanopy and builtin picker。我在OCAT中设置PickerAttributes为64，实际也是可以去掉启动界面中的关机和重启按钮的。请及时更新OCAT。

**Comment by ic005k** [comment]
好的，感谢并欢迎随时提供更新线索。
