### ISSUE TITLE
ACPI条目临时禁用，然后保存无效

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#32]
下面图片中的ACPI条目我想取消勾选，然后点保存【不想删除，只是想临时禁用一下】，重新打开配置文件，条目仍被勾选，没有生效【取消了对勾，右侧字母没有同步变成False】，我是直接从优盘中打开的配置文件
![4](https://user-images.githubusercontent.com/6350504/116831639-7224e800-ab65-11eb-8e7b-6b3b56d10e23.png)

另外有个建议：
在右键中添加一个选项：添加数据库中的SSDT，单击后出现数据库ACPI中所有SSDT文件的选单，可以直接单选或多选SSDT文件，这样非常方便，目前只能一步一步浏览到软件的ACPI文件夹里添加

**Comment by ic005k** [comment]
> 取消了对勾，右侧字母没有同步变成False

这是因为你没有选择表中的条目，只需选择表中的任意条目即可。
在后面的版本里，我将改进一下。

**Comment by ic005k** [comment]
> 在右键中添加一个选项：添加数据库中的SSDT

其实更简单的方法是：选择工具栏上的“打开数据库目录”，将EFI里面的aml或者efi等需要的文件单选或多选后拖到表里即可。
OCAT所有的表均支持拖拽打开文件。打开plist文件同样可以拖拽。

**Comment by kyjdp** [comment]
嗯, 拖放已经试过是OK的,

但是不同的CPU平台,需要选择不同的通用的SSDT, 建议在右键弹出菜单中能分类显示一下,可以让用户根据自己的CPU来选择,或者直接检测当前电脑的CPU,自动推荐选择通过的SSDT文件,这样对一般用户更友好


非常感谢您花时间和精力开发和维护几个非常不错的黑苹果工具

**Comment by ic005k** [comment]
> 但是不同的CPU平台,需要选择不同的通用的SSDT, 建议在右键弹出菜单中能分类显示一下,可以让用户根据自己的CPU来选择,或者直接检测当前电脑的CPU,自动推荐选择通过的SSDT文件,这样对一般用户更友好

这个问题之前就有考虑过，但是因为“算不准”而放弃，硬件真的是千差万别，而且ssdt不仅仅和cpu有关。
