### ISSUE TITLE
打开旧版配置文件,直接保存,会被修改

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#33]
刚发现一个问题, 我直接用软件打开旧版的或其它地方下载的配置文件, 不何任何操作,直接保存, 然后用对比软件比较发现如下问题:
1. 新版OC的一些功能条目自动被添加了, 建议: 能否自动弹出提示进行选择是否更新功能条目? 这个问题不解决,对于一般用户,使用软件后产生的问题就更多了
2. 很多原有的一些条目,位置变了,建议: 能否保持条目原有位置
3. Data条目由一行分成了三行, 有的被分成了多行, 我MAC版和WIN交叉用过, 建议:能否不要分行?
本人经常使用对比软件来定位一些条目的更改, 现在的情况如果不改善,对比更改不太直观了
不自动添加条目,只修改配置中有的条目,也就变相一并解决了前面有朋友问的问题https://github.com/ic005k/QtOpenCoreConfig/issues/30

![3](https://user-images.githubusercontent.com/6350504/116872045-d029fc00-ac47-11eb-87b9-965d576e55ee.png)
![4](https://user-images.githubusercontent.com/6350504/116872454-7b3ab580-ac48-11eb-80f7-3acf500bb1c7.png)
![1](https://user-images.githubusercontent.com/6350504/116872056-d3bd8300-ac47-11eb-8cf7-4d91326ca735.png)
![2](https://user-images.githubusercontent.com/6350504/116872064-d61fdd00-ac47-11eb-9405-6996cd3b54b2.png)
测试文件下载:
https://gofile.io/d/zXZR4c

**Comment by ic005k** [comment]
> 1. 建议: 能否自动弹出提示进行选择是否更新功能条目?

应该不会考虑这个功能，我始终觉着而且经验也告诉我们完全没有必要使用旧版本的OC，软件还是新的好，特别是类似OC这样的底层软件。
你完全可以通过工具栏上的“升级OC主程序”将旧版的OC升级到最新版。

**Comment by ic005k** [comment]
> 2. 很多原有的一些条目,位置变了,建议: 能否保持条目原有位置

软件在保存文件的时候，会自动进行排序。这个可能是大多数plist编辑软件所具有的特征。不过你可以试用下我写的另外一个纯粹的plist编辑器PlistEDPlus，目前保存文件是不自动排序的。
其实我一直不太理解，为什么要采用这么原始的对比方式来增加或删除条目？

**Comment by ic005k** [comment]
> 3\. Data条目由一行分成了三行

这个真的是没有刻意地去分行，你可以用个文本编辑器打开OCAT保存过的文件，应该是没有分行的。

**Comment by ic005k** [comment]
> 3\. 本人经常使用对比软件来定位一些条目的更改, 现在的情况如果不改善,对比更改不太直观了

其实我不太理解这种操作方式，我回头体验一下对比更改的方式之后，可能会对OCAT做出一些调整。

**Comment by ic005k** [comment]
感谢建议和反馈，有想法请随时留言。

**Comment by kyjdp** [comment]
感谢细致的回复!
我是这样想的, 
1.最新的OC版本, 不一定是最好的, 尤其是对于一些旧硬件, OC开发时,一般不会过多的向下兼容, 很多新版本会舍掉一些老硬件的支持功能
2.有时用软件只是想图方便的修改某些选项, 不想动其它的设置, 修改一下, 就连带把别的都改了, 感觉增加了操作难度, 群里很多人也反馈,用了软件后,报错的问题, 找不到原因, 其它就是因为某些新条目添加了,但是OC核心驱动什么的没有更新, 没改前还能用, 改后干脆就罢工了, 所以还是尽可少的改动原文件为佳
