### ISSUE TITLE
检查出了错误,但是选择选项后,无法保存

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#34]
如题, 录了视频演示, https://gofile.io/d/0Nz6ba

另外,想问一下,在软件检查出错误后, 怎样自动更改为推荐的设置? 必须要手动去一项一项的去改吗?

**Comment by ic005k** [comment]
你在选择选项之前，当前的数据表是否获得焦点（是否有目标条目被选择）？
关于自动更改为推荐的设置，这个可以在后面的版本中逐步实现，可能也需要OC官方格式化错误的输出，以便OCAT解析这些错误。

**Comment by kyjdp** [comment]
其它的地方可以直接选了就生效, 只有这个地方好像不行

**Comment by ic005k** [comment]
> 其它的地方可以直接选了就生效, 只有这个地方好像不行

这可能是个bug，下个版本将修复它。

**Comment by ic005k** [comment]
或者你下载这个开发版，看看是否存在同样的问题：https://github.com/ic005k/QtOpenCoreConfig/suites/2653950900/artifacts/58358871
