### ISSUE TITLE
建议可以保存窗口大小设置

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#35]
很多笔记本默认的分辨率是1366*768,打开软件后,
1.窗口下边框部分被任务栏遮盖, 默认高度减40就合适了
2.窗口右边框部分没有充满桌面,有空余, 每次都要点最大化窗口或手调窗口, 下次启动时也不能保存上次的窗口设置, 
如果实现能保存上次窗口设置就好了
![1](https://user-images.githubusercontent.com/6350504/117074624-2c833d80-ad66-11eb-8c16-9d272934ed40.png)

**Comment by ic005k** [comment]
这个在后面的版本里可以逐步优化和调整，感谢反馈。
