### ISSUE TITLE
20230016 没法获取到最新版本的 OpenCore

### ISSUE THREAD

**Issue by LisonFan** [ic005k/QtOpenCoreConfig#353]
现在最新版本是 0.8.9，我点击获取 OpenCore 最新新版一直都停留在 0.8.5
![](https://cdn.jsdelivr.net/gh/xJDt9eAR6K/DgBngiez@mosZckVF/6f683184e510b6e58421363fd6a304b9/1676554916894.png)

**Comment by ic005k** [comment]
> 希望能加个提示之类的

最新版的OCAT已做了相应的处理，欢迎发现更多的问题或建议。

**Comment by geekbb** [comment]
一样，都是为更新oc发愁，能上github就说明本来可以科学上网，Github API 自动勾选，又无法取消，一直更新不了，开全局不行，关了梯子，又说Github API每小时60次访问，呵呵

**Comment by ic005k** [comment]
> Github API 自动勾选，又无法取消

目前只有这一种访问途径有效，所以无所谓能否取消

**Comment by ic005k** [comment]
> 开全局不行，关了梯子，又说Github API每小时60次访问

尝试更换镜像服务器试试看？如果施展了轻功的话，将镜像服务器设为https://github.com/看看（关闭镜像服务器）？
