### ISSUE TITLE
关于数据库建议

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#36]
数据库功能非常不错,也有强大的搜索功能,但是放置到里面的文件能否启用文件夹来管理?
例如:
可以自行创建文件夹, 如+ASUS,然后把华硕主板相关的配置放到里面,在软件上显示时,可以展开或折叠
这样可以更加方便的分类管理
建议: 如果文件夹的名字前带+号, 则识别为分类的文件夹,在软件的数据库窗口中可以屏开折叠,文件夹这样分类区分也很醒目

**Comment by ic005k** [comment]
在后面的版本里可以考虑这些功能，感谢建议和反馈。

**Comment by Z-fly** [comment]
不同主板见SSDT存在同文件名但不同内容的情况，所以建议是每块主板建立对应的SSDT文件夹，或者SSDT文件名加上主板后缀

**Comment by Z-fly** [comment]
不同主板间SSDT存在同文件名但不同内容的情况，所以建议是每块主板建立对应的SSDT文件夹，或者SSDT文件名加上主板后缀

**Comment by ic005k** [comment]
> 不同主板间SSDT存在同文件名但不同内容的情况

这个可以通过个性化ssdt的命名来区分。不过数据库这块人们不是很热衷，所以目前我仅仅拿它来作为升级OC的一个辅助渠道和测试APP而已。
