### ISSUE TITLE
关于搜索功能建议

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#37]
搜索功能很不错,在有多个搜索结果的情况下,有个建议:
输入关键后,第一次回车,显示了有多个搜索结果, 
第二次回车,定位到第二个,第三次回车定位到第三个,以此类推, 
这样可以不用去鼠标点那个  下一个  按钮了, 方便不少

**Comment by ic005k** [comment]
好的，后面的版本会完善这些功能的。
