### ISSUE TITLE
添加SSDTs, KEXTS, Drivers时, 能弹出常用列表

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#38]
在ACPI模块中点击+号, 添加SSDTs时
在Kernel模块中点击+号, 添加Kexts时
在UEFI模块中点击+号, 添加Drivers时
都能弹出一个窗口,里面列表了OC官方对应文件夹中的文件, 还有对每个文件的使用说明, 可以勾选来多选, 这样会非常不错, 使用门槛降低很多
另外,Kexts的列表中, 建议添加一列, 显示Kext的版本号, 并有链接, 点击可以直达驱动的下载地址

**Comment by ic005k** [comment]
好的，有任何想法，可以随时留言。回头我会整理一下，逐一来完善。

不过，我还是建议你使用拖拽来添加文件，方便快捷。

**Comment by kyjdp** [comment]
建议在没有实现这前,点击+号后,打开的对话框,分别定位到如下的目录, 以方便选择, 感觉更理一些!
\Database\EFI\OC\ACPI
\Database\EFI\OC\Kexts
\Database\EFI\OC\Drivers
\Database\EFI\OC\Tools

**Comment by kyjdp** [comment]
另外, 在NVRAM模块, 点+号后,建议也能弹出常用的GUID列表[好像常用的GUID只有几个],选择后,右边是一些默认的参数,  方便直接修改, 现在点击后, 是左右都是空的,全部要全新输入

**Comment by ic005k** [comment]
> 建议在没有实现之前,点击+号后,打开的对话框,分别定位到如下的目录, 以方便选择, 更合理一些!

我可能会直接加一个按钮打开数据库中的相关目录，之后再拖拽文件到表中即可。可能不会搞得很复杂。

**Comment by ic005k** [comment]
> 在NVRAM模块, 点+号后,建议也能弹出常用的GUID列表[好像常用的GUID只有几个],选择后,右边已经有了一些常用和默认的参数, 方便直接修改, 现在点击后, 是左右都是空的,全部要全新输入

这个模块有部分内容已实现，你需要在“+”按钮上点鼠标右键即可。7C436110-AB2A-4BBB-A880-FE41995C9F82是比较完善的，其它的还没有做，后面根据情况再完善，其实这部分内容很简单，只需将OC例子当前的相关内容复制、粘贴过来就可以了。

**Comment by kyjdp** [comment]
要在“+”按钮上点鼠标右键即可

这个不错, 建议其它的也搞成这样:
1.单击+ 可直接创建空条目, 右击+创建常用的, 预置的条目
2.当鼠标移到+上时, 能悬浮一个提示, 内容就是上面的
3.常用的, 预置的条目, 分成几列, 有每行项目的解释\版本等信息就更好了

**Comment by ic005k** [comment]
以上内容已记录，慢慢来吧，总之APP会不断地完善和更新。

**Comment by btwise** [comment]
@kyjdp 
这些都是occ的功能，增加预设数据就可以😁
