### ISSUE TITLE
最大化窗口的情况下, 使用搜索窗口会自动向右扩展,隐藏了窗口右上角的按钮

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#39]
如下图所示
![dr](https://user-images.githubusercontent.com/6350504/117269657-0efbc400-ae8b-11eb-946d-7eaf9a61afda.png)

**Comment by ic005k** [comment]
这个情况我会调整一下APP的宽度，之前的最小宽度可能不小于1366而导致的。

**Comment by ic005k** [comment]
可能高度也需要调整，以适应1366x768的分辨率。
