### ISSUE TITLE
A few of points raised for QtOpenCoreConfig 0.7.1

### ISSUE THREAD

**Issue by mackonsti** [ic005k/QtOpenCoreConfig#40]
Hello @ic005k thanks for releasing your tool QtOpenCoreConfig. I thought of trying it out and wanted to report the following points for your information.

1. When opend an existing working PLIST and saved it, I saw that you are adding the not-found or not-used anymore key:

ACPI > Quirks > **SyncTableIds** as FALSE

I could not find this in OpenCore documentation of 0.6.9 or 0.7.0 so is this part of the unreleased OpenCore 0.7.1 ?

2. Same issue where other keys are added in sections that I can not make reference to, today:

Kernel > Quirks > **ProvideCurrentCpuInfo** as FALSE
also
Misc > Security > **AllowToggleSip** as FALSE
and others...

I assume these is part of OpenCore 0.7.0 or the unreleased 0.7.1 version, correct?

3. Thus a good visual UI reference would be to indicate WHICH OpenCore version your tool will be saving...

Is your versioning in the window title bar, following the OpenCore releases versioning?

It would be perhaps a good idea to not only mention it in the About window but if you want to mention it in the main window title bar, perhaps consider saying **OC Auxiliary Tools X.Y.Z for OpenCore 0.A.B** ?

**X.Y.Z** = your version
**0.A.B** = OpenCore supported
...and the date we see today in the window title bar, you can only have it in About... what do you think?

4. The saved PLIST file after any changes, is replacing TAB character with 4 SPACE characters. Is this something you can control? The resulting **config.plist** file gets almost double in bytes, for no real reason 😢 

5. Please consider adding the Window zoom or Font Size so that larger screens can display nicely visible text sizes?

6. Same as with your QtIASL tool, please add Command+W support to close the window?

7. Just like the QtiASL tool when discussed, can you consider removing the Qt component "bearer" if not really needing it?

**/Contents/PlugIns/bearer**

Remember the points raised in QtiASL 😄 

Thank you!

**Comment by ic005k** [comment]
Yes, thank you very much for your feedback. I will reply one by one later.

**Comment by ic005k** [comment]
> I assume these is part of OpenCore 0.7.0 or the unreleased 0.7.1 version, correct?

OCAT is always kept up to date with the latest version of OC, so it is currently 0.7.1.

**Comment by ic005k** [comment]
> It would be perhaps a good idea to not only mention it in the About window but if you want to mention it in the main window title bar, perhaps consider saying **OC Auxiliary Tools X.Y.Z for OpenCore 0.A.B** ?

This is a good idea, the next release will be formatted like this, thanks.

**Comment by ic005k** [comment]
> 1. The saved PLIST file after any changes, is replacing TAB character with 4 SPACE characters. Is this something you can control? The resulting **config.plist** file gets almost double in bytes

For more information on this subject, see here.

https://www.insanelymac.com/forum/topic/344752-open-source-cross-platform-opencore-auxiliary-tools/page/6/

**Comment by ic005k** [comment]
> Please consider adding the Window zoom or Font Size so that larger screens can display nicely visible text sizes?

Actually, the default font size can already accommodate most of the display effects, can you please take a screenshot to see the display anomalies on your side?

**Comment by ic005k** [comment]
> 3\. Same as with your QtIASL tool, please add Command+W support to close the window?

OCAT does not have multiple tabs, so please just use Alt + Q to exit the program.

**Comment by ic005k** [comment]
> 4\. Just like the QtiASL tool when discussed, can you consider removing the Qt component "bearer" if not really needing it?

For now, binaries are automatically built and packaged for upload through Github ACtions, not manually. But I will consider if it is possible to remove "bearer" during automatic packaging, I will try it.

**Comment by ic005k** [comment]
More questions and suggestions are welcome and much appreciated.
