### ISSUE TITLE
建议: 能否可选以前的UI界面

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#41]
有些日子不使用软件了, 最近闲着没事儿, 想更新一下OC, 但是发现软件更改UI了,

个人感觉, 还是以前的工具栏主副级形式的,并且搭配中英文的OC项目显示, 更加一目了然, 更大气一些

现在的UI, 改什么大项, 通过左侧小图标不能一下子识别, 我几乎没次都要把所有的图标, 从上向下点一遍, 可能也是本人太菜了

如果能有个选项, 能切换两种UI就好了

**Comment by ic005k** [comment]
之所以要改成目前的样式，主要是考虑到之前的UI占用了太多的垂直空间，导致在一些低分辨率的情况下（比如WinPE
等环境）没法正常完整地显示某些内容。
目前的UI，当你将鼠标放到图标上的时候，会显示提示，简洁明了，估计暂时不会再考虑调整UI了，后面有时间了我会不断地进行优化包括UI，总之有任何问题或想法，请随时留言，感谢反馈。

**Comment by kyjdp** [comment]
哦, 感谢回复, 原来是这样, 低分辨率情况[winpe]有点少见, 感觉能照顾大多数情况就可以了, 用小图标有点不实用

**Comment by ic005k** [comment]
好的，会不断完善的，清关注软件的后续升级

**Comment by k2y1982** [comment]
DeviceProperties设置界面，左边那个框太大了，右边的值如果长了根本就看不全。NVRAM设置界面至少还可以拖动。

还有个小小的建议，粘贴值的时候能不能不按回车也能复制进去啊。

**Comment by ic005k** [comment]
> DeviceProperties设置界面，左边那个框太大了，右边的值如果长了根本就看不全。NVRAM设置界面至少还可以拖动。
> 
> 还有个小小的建议，粘贴值的时候能不能不按回车也能复制进去啊。

小事情，待我有空再慢慢优化它，感谢反馈。

**Comment by ic005k** [comment]
> DeviceProperties设置界面，左边那个框太大了，右边的值如果长了根本就看不全。NVRAM设置界面至少还可以拖动。
> 
> 还有个小小的建议，粘贴值的时候能不能不按回车也能复制进去啊。

相应的功能已改进和添加，请下载最新的版本。有任何想法和问题，请随时留言。

**Comment by kyjdp** [comment]
@ic005k
你好,关于横向和竖向显示工具条的问题, 如果真只是为了PE分辨率低而把方向改了, 能否加个判断, 当前分辨率小于某个值,则自动竖向显示, 否则横向显示, 感觉还是横向显示一目了然, 并且在论坛和软件描述中,都是基于横向工具栏说明的,例如下图, 当前竖向图标也没有文字标题,只能去悬停看,
![2](https://user-images.githubusercontent.com/6350504/125208963-4f7f2000-e2c8-11eb-91cb-0bdfdb401e98.png)

**Comment by ic005k** [comment]
当然是完全没有问题的，只不过我不想在这个上面再花太多精力而已，时间有限。再次感谢建议。
或许使用一段时间，你就熟悉现在的UI了，总共也只有8个大项。
但是如果程序有bug或者其它功能需要增强，我会义无反顾地去改进、去完善，至于UI，暂时先这样了，请原谅我的懒惰。。。

**Comment by kyjdp** [comment]
感谢回复, 现在理解了, 本人对编程不太懂, 不知道更改这些很麻烦, 站在一个纯小白角度提的建议,&nbsp;以后使用软件, 最多就是升级一下OC主程序和驱动,其它选项什么的好像不用更改, 先这样吧, 再次感谢

**Comment by kyjdp** [comment]
@ic005k
不好意思,又来请教您了
我想自行修改软件界面左侧的图标, 【主要是想在图片下部添加说明文本】, 但我对编程不太懂, 我只知道软件是开源的， 如何自行编译源码，很麻烦吗？ 能否指点一二，非常感谢

**Comment by ic005k** [comment]
> @ic005k
> 不好意思,又来请教您了
> 我想自行修改软件界面左侧的图标, 【主要是想在图片下部添加说明文本】, 但我对编程不太懂, 我只知道软件是开源的， 如何自行编译源码，很麻烦吗？ 能否指点一二，非常感谢

这个非常简单的，因为这些图片是放在源码的资源文件里面，如果你了解Qt框架，是完全可以自行修改的，即使没有编程基础，你也可以学习下，也不是很难的事情。

还有，你可以放上你设计的图标，我可以将它替换，说实话，我手头正好差一个图标设计师，你可能会发现OCAT的图标都是拼凑而来的，不是来自图标设计师之手，期待你的优秀设计。

**Comment by kyjdp** [comment]
感谢回复，本人编程和设计都非常入门，只是感觉有时文字比图像看的更清楚一些，图+文就更锦上添花了，我业余留意多留意找几个相关的图标，到时候发您看下

**Comment by ic005k** [comment]
我在新版的OCAT里面临时增加了文字（在图标下面），你可下载最新的版本看看。

**Comment by kyjdp** [comment]
好的, 感谢

**Comment by kyjdp** [comment]
这次好多了,
建议
DP改为DevPro
PI改为Platform

**Comment by kyjdp** [comment]
建议exe文件名前默认加个_ 这样解压后直接就看到了,方便了一些
![123](https://user-images.githubusercontent.com/6350504/125620004-c68d4b62-9ff5-426e-962e-edf024f8a935.png)

**Comment by kyjdp** [comment]
建议,ctrl+shift+s 另存为默认位置在桌面, 目前是在文件夹,而且没有记忆

**Comment by ic005k** [comment]
> 建议
> DP改为DevProp
> PI改为Platform

目前还是采用头之母进行缩写，标准一些

**Comment by ic005k** [comment]
> 建议exe文件名前默认加个_ 这样解压后直接就看到了,方便了一些

这不是标准的可执行文件的命名方式，虽然没有任何问题。
其实升级OCAT是很简单的事情，只需将整个文件夹覆盖旧的文件夹就可以了，可执行文件在桌面建个快捷方式或者固定到任务栏，不用对单个文件进行操作。

**Comment by ic005k** [comment]
> 建议,ctrl+shift+s 另存为默认位置在桌面, 目前是在文件夹,而且没有记忆

这个倒是可以考虑，之前由于这个另存的使用率非常低，几乎用不到另存，所以一直没有优化它，只是有这个功能而已。
旧的配置文件打开后直接保存，就自动升级了，另存其实是个多余的功能，没有适用的场景。

**Comment by kyjdp** [comment]
嗯, 其实另存是想做个备份,
或者变个方式,建议打开旧版配置后,如果直接保存,则自动生成旧版的备份,即原文件名后加-bak,然后再保存,这个有点必要,因为有时升级后就不能引导了,做个备份以防万一

**Comment by kyjdp** [comment]
> > 建议
> > DP改为DevProp
> > PI改为Platform
> 
> 目前还是采用头之母进行缩写，标准一些

DP 和PI 可能对国外的朋友产生成歧义, 
最后那项info建议改为HwInfo
