### ISSUE TITLE
Using Snapcraft instead of AppImage

### ISSUE THREAD

**Issue by iMonZ** [ic005k/QtOpenCoreConfig#42]
Consider switching to Snapcraft from the AppImage.

The greatest advantages are easier to install and more reliable update options (like updating over the package manager instead of manually downloading a file)

I can write a GitHub Action for that.

**Comment by ic005k** [comment]
Considering that OCAT will be upgraded less and less frequently, no other adjustments will be made at this time, thank you very much for your suggestion.
