### ISSUE TITLE
Creating a Homebrew tap

### ISSUE THREAD

**Issue by iMonZ** [ic005k/QtOpenCoreConfig#43]
A good way for this tool is to add this to the Homebrew repo

But the Homebrew repo isn't accepting small projects like this (this project is still fresh, so its normal)

That's why an own tap with the latest version of this tool would be very great!

People could have an automatic update option and an easy and safe way to install.

I could create this tap in less than an hour, It's pretty straight forward

**Comment by ic005k** [comment]
There is no need to do so for the time being, because OCAT is a multi-platform app. As OC continues to improve, OCAT will be upgraded very infrequently, possibly only once every six months or a year, thanks to feedback.
