### ISSUE TITLE
从065升级到071后,开机启动时无法显示图形化UI

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#44]
情况是这样的, 我的电脑一直使用065版引导,启动时可以显示图形化UI, 但是使用OCAT升级成最新的071后,就无法显示图形化UI了,只能是最原始的命令行菜单引导了, 尝试了很多办法, 甚至把065的OpenCanopy.efi驱动也替换过来了,还是不行

升级过程:
用OCAT打开065的config, 会提示错误, 然后另存为新的config, 然后打开它,就不再有错误, 然后同时打开065和071config,对比不同之处,并与原065的选项保持一致, 最后开机测试

个人感觉也有可能是引导本身的问题,不知道有没有朋友遇到这样的情况, 欢迎任何建议, 提前感谢!
两个版本config文件链接如下:
https://www99.zippyshare.com/v/Aq5RKPd8/file.html
https://www99.zippyshare.com/v/U4pHfRp0/file.html

**Comment by ic005k** [comment]
其实升级是非常非常简单的事情，如下：
打开你现在的0.7.1配置文件，OCAT的工具栏上点击“在桌面上产生EFI文件夹“，将产生的EFI文件夹OC里面的”Resources"目录覆盖你现有的“Resources”目录（可以先删除你的在拷贝新的Resources），完事。
同时注意：PickerMode选中External、PickerVariant选中Auto或其它，同时确保UEFI驱动OpenRuntime.efi存在且处于使能状态。

使用OCAT一切都变得非常简单，OCAT还有“升级OC主程序”等便捷的OC自动升级工具等。

**Comment by ic005k** [comment]
以上PickerMode等关键词，如果不知道在哪个选项里面，可使用OCAT的搜索功能来查找它们。

**Comment by kyjdp** [comment]
感谢你的回复,这几个选项都试过了, 还是不显示GUI


&nbsp;现在065和071的两个配置文件中所有选项对照完全一样,启动到MAC也没有问题, 但就是无法显示GUI引导界面, 真是奇怪了,

**Comment by ic005k** [comment]
> 感谢你的回复,这几个选项都试过了, 还是不显示GUI &nbsp;现在065和071的两个配置文件中所有选项对照完全一样,启动到MAC也没有问题, 但就是无法显示GUI引导界面, 真是奇怪了,

OC主程序是否升级到了0.7.1呢？否则肯定是不行的。

**Comment by ic005k** [comment]
对了，你可以直接在github的问题里面附加你的配置文件，而不必通过外链来转存。

**Comment by ic005k** [comment]
[Config.plist.zip](https://github.com/ic005k/QtOpenCoreConfig/files/6798214/Config.plist.zip)

你可以看下我这边有关PickerMode的设置。

**Comment by kyjdp** [comment]
你好, 为了验证问题, 我又把以前给朋友装的黑苹果的配置,升级了一下, 图形化引导也消失了, 看来哪里有更改, 但是实在不知道去找哪里, 对比软件,很多位置也改了

**Comment by kyjdp** [comment]
我旧版升级的过程:
打开旧版Config, 有错误, 我就另存为新的, 然后再打开新的, 没有错误, 然后在桌面生成EFI, 然后放到EFI分区下, 开机后, 图形界面就没有了, 但是所有的文件都更新了, 因为没有提示缺文件什么的, 
目前三台电脑都有这个问题, 都是升级时出现的

**Comment by ic005k** [comment]
放上你的配置文件，我帮你看看，你上次放在外链上的配置文件，我这边没法下载

**Comment by kyjdp** [comment]
好的,稍后我录个HDMI屏录

**Comment by kyjdp** [comment]
你好, 相关文件和操作演示已经上传国内的网盘, 链接:
https://www.wenshushu.cn/f/5wco6581ygg

**Comment by ic005k** [comment]
很明显的一个问题，在你的配置文件中：PickerVariant的值为BsxDarkFenceBlue1_，这个可能是你自定义的值，你设为Auto就可以了，我前面有说过

**Comment by ic005k** [comment]
请注意，OC的PickerVariant值在版本迭代中发生了很多次更改，你先使用Auto完成UI的显示，再逐渐摸索如何自定义UI。
其实OCAT可以在这里统一改成Auto，但会影响熟练用户的自定义值，所以这个值需要用户自行确认。

**Comment by kyjdp** [comment]
你好，感谢回复，
我试过了Auto了，自定义值是我想用这个主题，另外，用默认的主题也不行的，都试过了

**Comment by kyjdp** [comment]
百度上能搜索到解决方法都试过了，仍然没解决，真是郁闷了

**Comment by ic005k** [comment]
这我也不清楚了，应该是非常简单的事情，你用下我帮你生成的EFI看看？
[EFI.zip](https://github.com/ic005k/QtOpenCoreConfig/files/6812352/EFI.zip)

**Comment by kyjdp** [comment]
大侠威武，真成了， 但是是默认的主题， 能指点一下修改了哪些地方吗？

**Comment by ic005k** [comment]
很简单，就是我前面说的，将PickerVariant改为Auto，再生成一个EFI文件夹即可，我是在Mac下生成的，但应该和OCAT的版本无关，你在Win下也可以试下。
至于自定义UI，这个我真没研究过，因为OC一直在改这块，它的自定义规则总是在发生变化，你可以看下OC的说明书，研究看看。

**Comment by kyjdp** [comment]
再次尝试，得出结论：
升级后用默认主题，值设为Auto或主题名  ----结果OK
升级后用原来主题，值设为Auto或主题名  ----结果NO

**Comment by ic005k** [comment]
> 升级后用原来主题，值设为Auto或主题名 ----结果NO

OC的自定义规则有变化的，和Resources里面的文件分布都有关系的，自定义UI要符合它的规则，否则肯定不成，至于目前OC自定义UI的规则，我也不十分清楚，总之它一直在改动，你可以查下说明书自行研究看看

**Comment by kyjdp** [comment]
好的，再次感谢耐心回复！
对比了一下两个Resources文件夹
没有区别，只老版文件夹Image下添加了几个BsxDarkFenceBlue1_前缀的图标文件，必须要删除它们才行，否则设Auto不行

**Comment by btwise** [comment]
新版的oc图形界面资源文件结构和尺寸都有新的要求，可以使用最新的occ来解决主题问题！

**Comment by kyjdp** [comment]
@btwise
感谢提醒， 对OCC使用不太熟，有时间再试试
