### ISSUE TITLE
复制并粘贴过来的条目无法重命名

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#45]
有时我需要从另一个配置文件中,复制一个条目, 然后粘贴过来:
如果当前已经有该条目, 新条目的名字后面会添加-数字, 而我想把原条目也保留,就在其前加上前缀#, 但是新条目就无法重命名了, 始终带有后缀了, 即使删除原条目也不行了
WIN和MAC版都有相同的问题
表达的不太清楚, 有视频演示 https://ws28.cn/f/5wcr581cwpx

顺便反馈几个细节问题
1.在使用中, 经常出现即使按了CTRL+S保存了, 但是关闭软件时还会提醒已经修改
2.有时打开配置文件后, 只切换几个标签并没有修改, 但是关闭时,仍会提示文件已经修改
3.删除条目能否使用Del键?

**Comment by ic005k** [comment]
以上内容已记录，请关注OCAT的后续升级，感谢反馈。

**Comment by ic005k** [comment]
> 在使用中, 经常出现即使按了CTRL+S保存了, 但是关闭软件时还会提醒已经修改

这个现象，回头会重新构建内容被修改之后的保存提示策略。其他的问题均已修复，请下载最新的版本。

**Comment by kyjdp** [comment]
你好,刚试了一下,
使用del删子条目, 会把主条目给删了,如下图
撤消的快键使用多下些, 建议改成大多软件使用的ctrl+z 目前是ctrl+1
![123](https://user-images.githubusercontent.com/6350504/125626459-e092bfd9-3c62-4b49-9b80-3598c80c6480.png)

**Comment by ic005k** [comment]
> 使用del删子条目

这个快捷键是Ctrl+Delete

**Comment by ic005k** [comment]
> 撤消的快键使用多下些, 建议改成大多软件使用的ctrl+z

会和文本里面的撤消快捷键冲突，所以才另外定义

**Comment by k2y1982** [comment]
左边的- 是删主键，右边的 - 是删子建，不会是点错了吧。

**Comment by ic005k** [comment]
> 1.在使用中, 经常出现即使按了CTRL+S保存了, 但是关闭软件时还会提醒已经修改
> 2.有时打开配置文件后, 只切换几个标签并没有修改, 但是关闭时,仍会提示文件已经修改

这个问题已修复，请下载最新的版本。
