### ISSUE TITLE
功能增强建议: 修改配置文件,添加Kexts或Drivers条目后,当保存时,自动添加文件

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#46]
如题, 再描述具体一点:

有时, 我想修改EFI分区下的OC配置文件,就将Config文件拖到OCAT软件图标上打开它, 然后在相关的选项卡中添加了Kexts或Drivers条目, 然后保存配置, 但是还需要手动拷贝OCAT中的Kexts或Drivers文件,到OC对应的文件夹, 这有点麻烦, 能否来个一步到位, 在保存时, 软件就自动把添加的条目文件复制到相关的文件夹?

我目前知道有个办法: 在桌面重新生成EFI文件夹, 但是仍然需要拷贝文件到EFI分区, 仍然不够方便

**Comment by ic005k** [comment]
这个之前也有想到过，后来并没有实现它，原因如下：
1.不是所有的用户都想使用数据库中的文件，特别是OC的熟练用户。
2.有部分用户对文件版本有个性化需求，如果直接从数据库中覆盖，实无必要。
3.目前OCAT的数据库只是完成并实现了一个基本的OC框架，其里面的相关文件，比如kext等等并没有搜集完善，也没有精力去搜集，所以数据库目前对我来说，更多的只是为了测试OCAT，对于OC的熟练用户，可能根本都不会用到数据库。
4.数据库里面的文件更新可能会比较滞后，比如kext等，所以对于一个OC玩家来说，数据库基本是可以忽略的。

基于以上几点，这个功能应该暂时不会添加。

**Comment by kyjdp** [comment]
感谢回复！
能否加个预置功能，在预置功能里，添加一些偏好选项，例如上面说的，但默认不勾选
关于kext、Drivers, 能有一个按钮就好了，点击后，可以一键进行版本检测、GT源下载，解压等

**Comment by ic005k** [comment]
> 能否加个预置功能，在预置功能里，添加一些偏好选项，例如上面说的，但默认不勾选
> 关于数据库中的kext、Drivers, 能有一个按钮就好了，点击后，可以一键进行版本检测、GT源下载，解压等

这些都可以考虑，完全没有技术上的任何问题，只不过OCAT的定位是保持和OC的理念一致，基本是属于“手动档”，自动化程度不要太高，每一个操作对用户来说，都要保持透明。
总之，后面会慢慢优化的，会不断升级和改进。

**Comment by k2y1982** [comment]
我倒是有个想法，因为我一般是从官方版开始配置，drv kexts 都会复制到相应的文件夹，如果ocat能像propertree的 OC snapshot,一键扫描oc目录中的drv kexts tool,并添加到plist的对应位置，这样就不用手动拖到ocat里了。

**Comment by ic005k** [comment]
我之前也有想过，这个其实也不是什么很炫的功能，OCAT采用批量（多选文件）拖拽文件到ACPI、kext、UEFI驱动，其实也非常迅捷，看情况吧，后面如果大家的呼声比较高，也可以实现这个功能

**Comment by kyjdp** [comment]
> > 能否加个预置功能，在预置功能里，添加一些偏好选项，例如上面说的，但默认不勾选
> > 关于数据库中的kext、Drivers, 能有一个按钮就好了，点击后，可以一键进行版本检测、GT源下载，解压等
> 
> 这些都可以考虑，完全没有技术上的任何问题，只不过OCAT的定位是保持和OC的理念一致，基本是属于“手动档”，自动化程度不要太高，每一个操作对用户来说，都要保持透明。
> 总之，后面会慢慢优化的，会不断升级和改进。

感谢解释,
可能我没有说清楚:
我添加K和D的时候,没点+号,点的是浏览,然后就打开数据库的对应文件夹了,我把K或D拖到列表中,然后列表就有条目了,然后我保存, 但是,保存后,添加条目的K或D没有拷贝到我修改的配置文件下的对应的文件夹中, 我还要去复制粘贴,这实在不太方便

我上面的操作,没有涉及到K或D的版本问题, 只是想添加数据库中的K或D

**Comment by kyjdp** [comment]
或者, 拖到K或D到列表添加条目后,会自动弹个对话框: 是否将K或D拷到对应的目录中?

**Comment by ic005k** [comment]
通常的做法是这样的：
先组织你的EFI，将各种所需的kext等文件放到你的EFI中，打开你的EFI目录将里面的kext等需要加载的文件多选或者单选拖到OCAT的相关页面即可。
你的思路是比较依赖OCAT的数据库，其实这个数据库除了OC主程序之外，其他文件都是很滞后的，比如里面的kext我都好久没更新了等等。数据库只是提供了一个比较便捷的组织OC的途径，但它可能永远不是最新的。
其实当初我设计数据库的初衷是为了集合各种配置文件，但事与愿违，用户的积极性并不高，所以我后面除了维护OC的主程序之外，其他内容基本都不会再花时间去维护，而且后面的版本我会去掉那些很长时间都没有维护的配置文件，只保留OC的两个例子配置文件和我自用的两个配置文件（为了测试数据库）。
所以，这部分的功能目前应该是不考虑再加强什么的，后面再根据情况做些调整。
