### ISSUE TITLE
OC开机引导时, 显示一个配置错误, 但在软件对应的选项卡没有选项

### ISSUE THREAD

**Issue by kyjdp** [ic005k/QtOpenCoreConfig#48]
如下图所示, 不知道是BIOS设置问题, 还是OC设置问题,
![2](https://user-images.githubusercontent.com/6350504/126234213-47f1dcdc-2170-417e-99c9-25219b838983.jpg)
![1](https://user-images.githubusercontent.com/6350504/126234218-109de3ca-53f2-4a5a-9520-7acc00d15da2.png)

**Comment by ic005k** [comment]
你使用的是针对0.7.1OC版本的OCAT来编辑0.7.2的OC，肯定是不匹配的，请下载最新的针对0.7.2的OCAT，打开你的配置文件，保存一下就可以了。

**Comment by ic005k** [comment]
OCAT的版本可以在软件的标题栏或关于里面查看，比如：OC Auxiliary Tools   V20210719 for OpenCore 0.7.2
V20210719是OCAT的版本
OpenCore 0.7.2是OC的版本
很容易理解的。

一个更简单的办法是：你可以使用任意版本的OCAT，只需打开你的配置文件，点击工具栏上的“升级OC主程序”，即可使OCAT的版本和OC的版本保持统一，这样开机就不会出现任何提示了。

**Comment by kyjdp** [comment]
感谢回复, 我正在用OCAT071的版本改OC071的配置, 以前好像就有提示, 只是一闪而过

**Comment by ic005k** [comment]
> 以前好像就有提示, 只是一闪而过

出现这个现象的根本原因是：OC版本和config.plist配置文件不匹配。你降级OC到0.7.1就可以了。

**Comment by kyjdp** [comment]
感谢回复, 我正在用OCAT071的版本改OC071的配置, 以前好像就有提示, 只是一闪而过

**Comment by kyjdp** [comment]
本身就是OC071版本, 升级072也一样, 怪了

**Comment by ic005k** [comment]
你需要先确认下OC的实际版本，在OC的引导界面都会有版本显示，比如OC引导图形界面右下角会有日期、版本（比如072等）显示。
之后，再使用针对这个版本的OCAT保存一下你的Config.plist即可，这没什么复杂的，很简单。
或者使用任意版本的OCAT在桌面上产生一个EFI文件夹，使用这个EFI看看有没有开机错误提示。
