### ISSUE TITLE
Can we use tab instead of space?

### ISSUE THREAD

**Issue by 1900forever** [ic005k/QtOpenCoreConfig#49]
The same config file that is saved by OCAuxiliaryTools is about 13KB larger than the one generated by ProperTree or OCC.

**Comment by ic005k** [comment]
Hello, in fact, we have explored this issue a lot before, why later have been using spaces instead of TAB for indentation, see the following post for details.

https://www.insanelymac.com/forum/topic/344752-open-source-cross-platform-opencore-auxiliary-tools/?do=findComment&comment=2753995
