### ISSUE TITLE
建议将每次更新记录都保留

### ISSUE THREAD

**Issue by char98k** [ic005k/QtOpenCoreConfig#5]
谢谢大佬的贡献，让初学者有更直观的界面进行修改。建议将每次更新记录都保留。另外对应opencore版本是否向下兼容？最后祝大佬越做越好！

**Comment by ic005k** [comment]
1.在发行页面，每次的更新都有记录的：https://github.com/ic005k/QtOpenCoreConfig/releases
2.向下兼容，但最好是升级oc到最新版，否则可能在引导界面出现之前，会跑几行字符，别的无碍。
