### ISSUE TITLE
自定义内存功能缺失

### ISSUE THREAD

**Issue by SpecN997** [ic005k/QtOpenCoreConfig#50]
![Untitled](https://user-images.githubusercontent.com/13669961/133604372-974daa3e-5cb2-44fb-9697-9d6fd583cbdf.jpg)
红框内原始信息在保存后会丢失。手动填入的话也不会保存。

Opencore 0.7.3 / OCAT 0.7.3 - 20210916 / Big Sur 11.6

**Comment by ic005k** [comment]
无论在什么情况下只要选上“保留Datahub等数据”即可，包括你仅仅是采用“Automatic”来获取机型信息。

之前这些信息都是自动保留的，后来有用户建议，如果采用“Automatic”，则可以选择是否保留这些数据（通过选择“保留Datahub等数据“来决定）。

**Comment by SpecN997** [comment]
> 无论在什么情况下只要选上“保留Datahub等数据”即可，包括你仅仅是采用“Automatic”来获取机型信息。
> 
> 之前这些信息都是自动保留的，后来有用户建议，如果采用“Automatic”，则可以选择是否保留这些数据（通过选择“保留Datahub等数据“来决定）。

今天下午升级前在用的0.7.2的旧版默认没勾上重启直接卡住折腾半天才发现是内存的信息被清了，但CustomMemory还勾着，另外也有点想当然被Keep data such as **Datahub**的名字误导到了。谢谢！
