### ISSUE TITLE
保存- UEFI-驱动 的时候闪退，0922版。

### ISSUE THREAD

**Issue by k2y1982** [ic005k/QtOpenCoreConfig#52]
保存- UEFI-驱动 的时候闪退，0922版。

**Comment by k2y1982** [comment]
OCS: Missing key Comment, context <Drivers>!
OCS: Missing key Comment, context <Drivers>!
OCS: Missing key Comment, context <Drivers>!
Serialisation returns 3 errors!

Completed validating /Volumes/EFI/EFI/OC/config.plist in 1 ms. Found 3 issues requiring attention.

用别的编辑器后，再打开会提示这个。

**Comment by ic005k** [comment]
0.7.4的最新版OC在UEFI驱动里面新增了“注释Comment”字段，你重点检查下这个字段。

**Comment by k2y1982** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>ACPI</key>
        <dict>
            <key>Add</key>
            <array>
                <dict>
                    <key>Comment</key>
                    <string>Read the comment in dsl sample</string>
                    <key>Enabled</key>
                    <true/>
                    <key>Path</key>
                    <string>SSDT-PMC.aml</string>
                </dict>
                <dict>
                    <key>Comment</key>
                    <string>SSDT-AWAC.aml</string>
                    <key>Enabled</key>
                    <true/>
                    <key>Path</key>
                    <string>SSDT-AWAC.aml</string>
                </dict>
                <dict>
                    <key>Comment</key>
                    <string>SSDT-EC-USBX-DESKTOP.aml</string>
                    <key>Enabled</key>
                    <true/>
                    <key>Path</key>
                    <string>SSDT-EC-USBX-DESKTOP.aml</string>
                </dict>
                <dict>
                    <key>Comment</key>
                    <string>SSDT-PLUG-DRTNIA.aml</string>
                    <key>Enabled</key>
                    <true/>
                    <key>Path</key>
                    <string>SSDT-PLUG-DRTNIA.aml</string>
                </dict>
            </array>
            <key>Delete</key>
            <array/>
            <key>Patch</key>
            <array/>
            <key>Quirks</key>
            <dict>
                <key>FadtEnableReset</key>
                <false/>
                <key>NormalizeHeaders</key>
                <false/>
                <key>RebaseRegions</key>
                <false/>
                <key>ResetHwSig</key>
                <false/>
                <key>ResetLogoStatus</key>
                <false/>
                <key>SyncTableIds</key>
                <false/>
            </dict>
        </dict>
        <key>Booter</key>
        <dict>
            <key>MmioWhitelist</key>
            <array/>
            <key>Patch</key>
            <array/>
            <key>Quirks</key>
            <dict>
                <key>AllowRelocationBlock</key>
                <false/>
                <key>AvoidRuntimeDefrag</key>
                <true/>
                <key>DevirtualiseMmio</key>
                <true/>
                <key>DisableSingleUser</key>
                <false/>
                <key>DisableVariableWrite</key>
                <false/>
                <key>DiscardHibernateMap</key>
                <false/>
                <key>EnableSafeModeSlide</key>
                <true/>
                <key>EnableWriteUnprotector</key>
                <false/>
                <key>ForceBooterSignature</key>
                <false/>
                <key>ForceExitBootServices</key>
                <false/>
                <key>ProtectMemoryRegions</key>
                <false/>
                <key>ProtectSecureBoot</key>
                <false/>
                <key>ProtectUefiServices</key>
                <false/>
                <key>ProvideCustomSlide</key>
                <true/>
                <key>ProvideMaxSlide</key>
                <integer>0</integer>
                <key>RebuildAppleMemoryMap</key>
                <true/>
                <key>SetupVirtualMap</key>
                <true/>
                <key>SignalAppleOS</key>
                <false/>
                <key>SyncRuntimePermissions</key>
                <true/>
            </dict>
        </dict>
        <key>DeviceProperties</key>
        <dict>
            <key>Add</key>
            <dict/>
            <key>Delete</key>
            <dict/>
        </dict>
        <key>Kernel</key>
        <dict>
            <key>Add</key>
            <array>
                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>Lilu.kext</string>
                    <key>Comment</key>
                    <string>Patch engine</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/Lilu</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string>8.0.0</string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>
                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>VirtualSMC.kext</string>
                    <key>Comment</key>
                    <string>SMC emulator</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/VirtualSMC</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string>8.0.0</string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>
                <dict>
                    <key>Arch</key>
                    <string>x86_64</string>
                    <key>BundlePath</key>
                    <string>WhateverGreen.kext</string>
                    <key>Comment</key>
                    <string>Video patches</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/WhateverGreen</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string>10.0.0</string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>
                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>AppleALC.kext</string>
                    <key>Comment</key>
                    <string>Audio patches</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/AppleALC</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string>8.0.0</string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>
                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>BlueToolFixup2.6.0.kext</string>
                    <key>Comment</key>
                    <string>BlueToolFixup2.6.0.kext</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/BlueToolFixup</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string>21.0.0</string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>
                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>RealtekRTL8111.kext</string>
                    <key>Comment</key>
                    <string>RealtekRTL8111.kext</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/RealtekRTL8111</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string></string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>
                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>SMCProcessor.kext</string>
                    <key>Comment</key>
                    <string>SMCProcessor.kext</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/SMCProcessor</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string></string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>
                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>SMCSuperIO.kext</string>
                    <key>Comment</key>
                    <string>SMCSuperIO.kext</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/SMCSuperIO</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string></string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>
                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>USBInjectAll_0.7.7.kext</string>
                    <key>Comment</key>
                    <string>USBInjectAll_0.7.7.kext</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/USBInjectAll</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string></string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>
            </array>
            <key>Block</key>
            <array/>
            <key>Emulate</key>
            <dict>
                <key>Cpuid1Data</key>
                <data></data>
                <key>Cpuid1Mask</key>
                <data></data>
                <key>DummyPowerManagement</key>
                <false/>
                <key>MaxKernel</key>
                <string></string>
                <key>MinKernel</key>
                <string></string>
            </dict>
            <key>Force</key>
            <array/>
            <key>Patch</key>
            <array/>
            <key>Quirks</key>
            <dict>
                <key>AppleCpuPmCfgLock</key>
                <true/>
                <key>AppleXcpmCfgLock</key>
                <true/>
                <key>AppleXcpmExtraMsrs</key>
                <false/>
                <key>AppleXcpmForceBoost</key>
                <false/>
                <key>CustomSMBIOSGuid</key>
                <false/>
                <key>DisableIoMapper</key>
                <true/>
                <key>DisableLinkeditJettison</key>
                <true/>
                <key>DisableRtcChecksum</key>
                <false/>
                <key>ExtendBTFeatureFlags</key>
                <false/>
                <key>ExternalDiskIcons</key>
                <false/>
                <key>ForceSecureBootScheme</key>
                <false/>
                <key>IncreasePciBarSize</key>
                <false/>
                <key>LapicKernelPanic</key>
                <false/>
                <key>LegacyCommpage</key>
                <false/>
                <key>PanicNoKextDump</key>
                <true/>
                <key>PowerTimeoutKernelPanic</key>
                <true/>
                <key>ProvideCurrentCpuInfo</key>
                <false/>
                <key>SetApfsTrimTimeout</key>
                <integer>-1</integer>
                <key>ThirdPartyDrives</key>
                <false/>
                <key>XhciPortLimit</key>
                <true/>
            </dict>
            <key>Scheme</key>
            <dict>
                <key>CustomKernel</key>
                <false/>
                <key>FuzzyMatch</key>
                <true/>
                <key>KernelArch</key>
                <string>Auto</string>
                <key>KernelCache</key>
                <string>Auto</string>
            </dict>
        </dict>
        <key>Misc</key>
        <dict>
            <key>BlessOverride</key>
            <array/>
            <key>Boot</key>
            <dict>
                <key>ConsoleAttributes</key>
                <integer>0</integer>
                <key>HibernateMode</key>
                <string>None</string>
                <key>HideAuxiliary</key>
                <true/>
                <key>LauncherOption</key>
                <string>Disabled</string>
                <key>LauncherPath</key>
                <string>Default</string>
                <key>PickerAttributes</key>
                <integer>17</integer>
                <key>PickerAudioAssist</key>
                <false/>
                <key>PickerMode</key>
                <string>External</string>
                <key>PickerVariant</key>
                <string>Acidanthera\Syrah</string>
                <key>PollAppleHotKeys</key>
                <true/>
                <key>ShowPicker</key>
                <true/>
                <key>TakeoffDelay</key>
                <integer>0</integer>
                <key>Timeout</key>
                <integer>5</integer>
            </dict>
            <key>Debug</key>
            <dict>
                <key>AppleDebug</key>
                <false/>
                <key>ApplePanic</key>
                <false/>
                <key>DisableWatchDog</key>
                <false/>
                <key>DisplayDelay</key>
                <integer>0</integer>
                <key>DisplayLevel</key>
                <integer>2147483650</integer>
                <key>SerialInit</key>
                <false/>
                <key>SysReport</key>
                <false/>
                <key>Target</key>
                <integer>3</integer>
            </dict>
            <key>Entries</key>
            <array/>
            <key>Security</key>
            <dict>
                <key>AllowNvramReset</key>
                <true/>
                <key>AllowSetDefault</key>
                <true/>
                <key>AllowToggleSip</key>
                <true/>
                <key>ApECID</key>
                <integer>0</integer>
                <key>AuthRestart</key>
                <false/>
                <key>BlacklistAppleUpdate</key>
                <true/>
                <key>DmgLoading</key>
                <string>Signed</string>
                <key>EnablePassword</key>
                <false/>
                <key>ExposeSensitiveData</key>
                <integer>6</integer>
                <key>HaltLevel</key>
                <integer>2147483648</integer>
                <key>PasswordHash</key>
                <data></data>
                <key>PasswordSalt</key>
                <data></data>
                <key>ScanPolicy</key>
                <integer>0</integer>
                <key>SecureBootModel</key>
                <string>Disabled</string>
                <key>Vault</key>
                <string>Optional</string>
            </dict>
            <key>Tools</key>
            <array/>
        </dict>
        <key>NVRAM</key>
        <dict>
            <key>Add</key>
            <dict>
                <key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
                <dict>
                    <key>DefaultBackgroundColor</key>
                    <data>AAAAAA==</data>
                    <key>UIScale</key>
                    <data>AQ==</data>
                </dict>
                <key>4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102</key>
                <dict>
                    <key>rtc-blacklist</key>
                    <data></data>
                </dict>
                <key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
                <dict>
                    <key>ForceDisplayRotationInEFI</key>
                    <integer>0</integer>
                    <key>SystemAudioVolume</key>
                    <data>Rg==</data>
                    <key>boot-args</key>
                    <string>alcid=11 npci=0x3000 -v</string>
                    <key>csr-active-config</key>
                    <data>AAAAAA==</data>
                    <key>prev-lang:kbd</key>
                    <data>emgtSGFuczoyNTI=</data>
                    <key>run-efi-updater</key>
                    <string>No</string>
                </dict>
            </dict>
            <key>Delete</key>
            <dict>
                <key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
                <array>
                    <string>UIScale</string>
                    <string>DefaultBackgroundColor</string>
                </array>
                <key>4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102</key>
                <array>
                    <string>rtc-blacklist</string>
                </array>
                <key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
                <array>
                    <string>boot-args</string>
                    <string>ForceDisplayRotationInEFI</string>
                </array>
            </dict>
            <key>LegacyEnable</key>
            <false/>
            <key>LegacyOverwrite</key>
            <false/>
            <key>LegacySchema</key>
            <dict>
                <key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
                <array>
                    <string>EFILoginHiDPI</string>
                    <string>EFIBluetoothDelay</string>
                    <string>LocationServicesEnabled</string>
                    <string>SystemAudioVolume</string>
                    <string>SystemAudioVolumeDB</string>
                    <string>SystemAudioVolumeSaved</string>
                    <string>bluetoothActiveControllerInfo</string>
                    <string>bluetoothInternalControllerInfo</string>
                    <string>flagstate</string>
                    <string>fmm-computer-name</string>
                    <string>fmm-mobileme-token-FMM</string>
                    <string>fmm-mobileme-token-FMM-BridgeHasAccount</string>
                    <string>nvda_drv</string>
                    <string>prev-lang:kbd</string>
                </array>
                <key>8BE4DF61-93CA-11D2-AA0D-00E098032B8C</key>
                <array>
                    <string>Boot0080</string>
                    <string>Boot0081</string>
                    <string>Boot0082</string>
                    <string>BootNext</string>
                    <string>BootOrder</string>
                </array>
            </dict>
            <key>WriteFlash</key>
            <true/>
        </dict>
        <key>PlatformInfo</key>
        <dict>
            <key>Automatic</key>
            <true/>
            <key>CustomMemory</key>
            <false/>
            <key>Generic</key>
            <dict>
                <key>AdviseFeatures</key>
                <false/>
                <key>MLB</key>
                <string>C029049024NKGQGCB</string>
                <key>MaxBIOSVersion</key>
                <false/>
                <key>ProcessorType</key>
                <integer>0</integer>
                <key>ROM</key>
                <data>ESIzRFVm</data>
                <key>SpoofVendor</key>
                <true/>
                <key>SystemMemoryStatus</key>
                <string>Auto</string>
                <key>SystemProductName</key>
                <string>iMac19,1</string>
                <key>SystemSerialNumber</key>
                <string>C02Y50XPJWDW</string>
                <key>SystemUUID</key>
                <string>05A695E4-8636-4215-9B6D-25FCBAAEA47B</string>
            </dict>
            <key>UpdateDataHub</key>
            <true/>
            <key>UpdateNVRAM</key>
            <true/>
            <key>UpdateSMBIOS</key>
            <true/>
            <key>UpdateSMBIOSMode</key>
            <string>Create</string>
            <key>UseRawUuidEncoding</key>
            <false/>
        </dict>
        <key>UEFI</key>
        <dict>
            <key>APFS</key>
            <dict>
                <key>EnableJumpstart</key>
                <true/>
                <key>GlobalConnect</key>
                <false/>
                <key>HideVerbose</key>
                <true/>
                <key>JumpstartHotPlug</key>
                <false/>
                <key>MinDate</key>
                <integer>0</integer>
                <key>MinVersion</key>
                <integer>0</integer>
            </dict>
            <key>AppleInput</key>
            <dict>
                <key>AppleEvent</key>
                <string>Builtin</string>
                <key>CustomDelays</key>
                <false/>
                <key>GraphicsInputMirroring</key>
                <true/>
                <key>KeyInitialDelay</key>
                <integer>50</integer>
                <key>KeySubsequentDelay</key>
                <integer>5</integer>
                <key>PointerSpeedDiv</key>
                <integer>1</integer>
                <key>PointerSpeedMul</key>
                <integer>1</integer>
            </dict>
            <key>Audio</key>
            <dict>
                <key>AudioCodec</key>
                <integer>0</integer>
                <key>AudioDevice</key>
                <string>PciRoot(0x0)/Pci(0x1b,0x0)</string>
                <key>AudioOut</key>
                <integer>0</integer>
                <key>AudioSupport</key>
                <false/>
                <key>MinimumVolume</key>
                <integer>20</integer>
                <key>PlayChime</key>
                <string>Auto</string>
                <key>ResetTrafficClass</key>
                <false/>
                <key>SetupDelay</key>
                <integer>0</integer>
                <key>VolumeAmplifier</key>
                <integer>0</integer>
            </dict>
            <key>ConnectDrivers</key>
            <true/>
            <key>Drivers</key>
            <array>
                <dict>
                    <key>Arguments</key>
                    <string></string>
                    <key>Comment</key>
                    <string></string>
                    <key>Enabled</key>
                    <true/>
                    <key>Path</key>
                    <string>OpenRuntime.efi</string>
                </dict>
                <dict>
                    <key>Arguments</key>
                    <string></string>
                    <key>Comment</key>
                    <string></string>
                    <key>Enabled</key>
                    <true/>
                    <key>Path</key>
                    <string>OpenCanopy.efi</string>
                </dict>
                <dict>
                    <key>Arguments</key>
                    <string></string>
                    <key>Comment</key>
                    <string>OpenHfsPlus.efi</string>
                    <key>Enabled</key>
                    <true/>
                    <key>Path</key>
                    <string>OpenHfsPlus.efi</string>
                </dict>
            </array>
            <key>Input</key>
            <dict>
                <key>KeyFiltering</key>
                <false/>
                <key>KeyForgetThreshold</key>
                <integer>5</integer>
                <key>KeySupport</key>
                <true/>
                <key>KeySupportMode</key>
                <string>Auto</string>
                <key>KeySwap</key>
                <false/>
                <key>PointerSupport</key>
                <false/>
                <key>PointerSupportMode</key>
                <string>ASUS</string>
                <key>TimerResolution</key>
                <integer>50000</integer>
            </dict>
            <key>Output</key>
            <dict>
                <key>ClearScreenOnModeSwitch</key>
                <false/>
                <key>ConsoleMode</key>
                <string>Max</string>
                <key>DirectGopRendering</key>
                <false/>
                <key>ForceResolution</key>
                <false/>
                <key>GopPassThrough</key>
                <string>Disabled</string>
                <key>IgnoreTextInGraphics</key>
                <false/>
                <key>ProvideConsoleGop</key>
                <true/>
                <key>ReconnectOnResChange</key>
                <false/>
                <key>ReplaceTabWithSpace</key>
                <false/>
                <key>Resolution</key>
                <string>Max</string>
                <key>SanitiseClearScreen</key>
                <false/>
                <key>TextRenderer</key>
                <string>BuiltinGraphics</string>
                <key>UgaPassThrough</key>
                <false/>
            </dict>
            <key>ProtocolOverrides</key>
            <dict>
                <key>AppleAudio</key>
                <false/>
                <key>AppleBootPolicy</key>
                <false/>
                <key>AppleDebugLog</key>
                <false/>
                <key>AppleEg2Info</key>
                <false/>
                <key>AppleFramebufferInfo</key>
                <false/>
                <key>AppleImageConversion</key>
                <false/>
                <key>AppleImg4Verification</key>
                <false/>
                <key>AppleKeyMap</key>
                <false/>
                <key>AppleRtcRam</key>
                <false/>
                <key>AppleSecureBoot</key>
                <false/>
                <key>AppleSmcIo</key>
                <false/>
                <key>AppleUserInterfaceTheme</key>
                <false/>
                <key>DataHub</key>
                <false/>
                <key>DeviceProperties</key>
                <false/>
                <key>FirmwareVolume</key>
                <false/>
                <key>HashServices</key>
                <false/>
                <key>OSInfo</key>
                <false/>
                <key>UnicodeCollation</key>
                <false/>
            </dict>
            <key>Quirks</key>
            <dict>
                <key>ActivateHpetSupport</key>
                <false/>
                <key>DisableSecurityPolicy</key>
                <false/>
                <key>EnableVectorAcceleration</key>
                <false/>
                <key>ExitBootServicesDelay</key>
                <integer>0</integer>
                <key>ForceOcWriteFlash</key>
                <false/>
                <key>ForgeUefiSupport</key>
                <false/>
                <key>IgnoreInvalidFlexRatio</key>
                <true/>
                <key>ReleaseUsbOwnership</key>
                <false/>
                <key>ReloadOptionRoms</key>
                <false/>
                <key>RequestBootVarRouting</key>
                <true/>
                <key>TscSyncTimeout</key>
                <integer>0</integer>
                <key>UnblockFsConnect</key>
                <false/>
            </dict>
            <key>ReservedMemory</key>
            <array/>
        </dict>
    </dict>
</plist>

**Comment by k2y1982** [comment]
<key>Drivers</key>
            <array>
                <dict>
                    <key>Arguments</key>
                    <string></string>
                    <key>Comment</key>
                    <string></string>
                    <key>Enabled</key>
                    <true/>
                    <key>Path</key>
                    <string>OpenRuntime.efi</string>
                </dict>
                <dict>
                    <key>Arguments</key>
                    <string></string>
                    <key>Comment</key>
                    <string></string>
                    <key>Enabled</key>
                    <true/>
                    <key>Path</key>
                    <string>OpenCanopy.efi</string>
                </dict>
                <dict>
                    <key>Arguments</key>
                    <string></string>
                    <key>Comment</key>
                    <string>OpenHfsPlus.efi</string>
                    <key>Enabled</key>
                    <true/>
                    <key>Path</key>
                    <string>OpenHfsPlus.efi</string>
                </dict>
            </array>

**Comment by k2y1982** [comment]
我一般是把原始的都删掉，再重新拖入自己需要的efi，然后保存的时候就会闪退。

**Comment by ic005k** [comment]
> 把原始的都删掉，再重新拖入自己需要的efi，然后保存的时候就会闪退

这个是个bug，我一会修复下，感谢发现。

**Comment by ic005k** [comment]
问题已修复，请更新。欢迎发现更多的问题。
