### ISSUE TITLE
Can the "Mount ESP partition" window close automatically?

### ISSUE THREAD

**Issue by 1900forever** [ic005k/QtOpenCoreConfig#53]
Aftet the ESP partition be mounted successfully, can it be closed automatically? For now I have to close it manually every time.

**Comment by ic005k** [comment]
Sure, and the next release will implement it.
More suggestions or questions are welcome.

**Comment by Asgardsurfer** [comment]
Hello @ic005k, OCAT is making our lives so much easier, many thanks!
Here is a minor request.
When mounting the ESP, it would be nice if OCAT could locate the mounted EFI and default to the config file when we do a "file open". 
OpenCore Configurator has that behaviour. It just makes thing flow faster. 
Thanks!

**Comment by Asgardsurfer** [comment]
Just tried your new implementation, works great thank you!
