### ISSUE TITLE
可否加入ESP已挂载的判断？

### ISSUE THREAD

**Issue by 1900forever** [ic005k/QtOpenCoreConfig#56]
现在的设置是无论ESP分区是否已挂载，都会要求输入管理员密码。
另外，在文件-打开的时候，能否记住上一次打开文件的地址？比如我的config文件在EFI目录下有多个备份，我的编辑都在这里进行，而目前的设置是每次都会打开驱动器列表目录。
辛苦了～

**Comment by ic005k** [comment]
这判断早就有的，你点“取消”就能直接打开了，如果之前已经挂载过了。

> 能否记住上一次打开文件的地址？
这些打开文件的历史记录一直是被保存的，只不过对于ESP分区来说，当这个分区消失的时候（没有被挂载），跟它相关的路径会一起消失。工具栏上的“打开目录”可直接打开任何被打开的plist文件所在的目录。

不过对于OC等引导来说，人们现在几乎都不使用ESP分区了，它比较麻烦，每次都需要挂载等等。目前的主流做法是划分一个普通的FAT32分区用来放OC的EFI目录，ESP分区留给Win使用即可。

**Comment by ic005k** [comment]
比如我一直将OC的EFI放在一个500M的单独的普通FAT32里面，非常省事。

**Comment by 1900forever** [comment]
等等，我在装系统的时候，给我的硬盘直接格式化成AFPS格式，这一步不会生成EFI分区吗？虽然在软件里被叫成ESP分区，我有点迷惑了……

**Comment by ic005k** [comment]
这是不会生成EFI分区的，通俗地讲，一块硬盘只允许有一个ESP分区，这个分区主要是用来安装Windows的引导文件。
至于OC或者是Clover等等，你只要找个FAT32的硬盘分区，将它们的EFI文件夹放到这个分区，BIOS设置里面将这个盘作为第一个引导盘就可以了。

**Comment by ic005k** [comment]
其实有很多教程要求将OC的EFI放到ESP分区，当然也是可以的，但完全没必要，对于调试OC来说很麻烦，每次都要挂载ESP分区。

**Comment by ic005k** [comment]
OCAT的挂载ESP分区功能，只是为了解决历史遗留问题，就是有小部分人群仍将OC的EFI放在了ESP里面。

**Comment by ic005k** [comment]
> 现在每次使用挂载ESP分区并打开config文件功能时，输入密码并挂载ESP分区后，Finder会自动跳出EFI文件夹。 能不能不跳出，挂载完毕后自动回到config编辑窗口呢？

这个功能后面会优化一下，感谢反馈。
