### ISSUE TITLE
加入kext后，排列顺序为首字母排列？

### ISSUE THREAD

**Issue by k2y1982** [ic005k/QtOpenCoreConfig#58]
Kernel->Add[4] discovers SMCProcessor.kext, but its Parent (VirtualSMC.kext) is either placed after it or is missing!
Kernel->Add[5] discovers SMCSuperIO.kext, but its Parent (VirtualSMC.kext) is either placed after it or is missing!
Kernel->Add[0] discovers AppleALC.kext, but its Parent (Lilu.kext) is either placed after it or is missing!
现在需要自己调整一下kext的顺序。。。

**Comment by ic005k** [comment]
抱歉，最近正在调整和优化这块的功能，可能最近的一个版本会有这个现象（添加kext不进行排序）。
下个版本就好了，感谢反馈。下个版本会加入自动感知功能，比如你拷贝一个新文件到kexts目录，则config.plist上会自动加入这个kext等等。同时Lilu.kext的排序等功能也会恢复。
新功能已开发完成，等测试之后就可以发布了。

**Comment by ic005k** [comment]
如果你对体验新版感兴趣，可以在此下载：https://github.com/ic005k/QtOpenCoreConfig/suites/3994549004/artifacts/100665524

**Comment by ic005k** [comment]
新版本的版本号为：20211010

**Comment by ic005k** [comment]
> 20211012也出这个问题了。

这个是bug，下个版本修复。
感谢反馈，同时欢迎发现任何其它问题。

**Comment by ic005k** [comment]
> Kernel->Add[4] discovers SMCProcessor.kext, but its Parent (VirtualSMC.kext) is either placed after it or is missing! Kernel->Add[5] discovers SMCSuperIO.kext, but its Parent (VirtualSMC.kext) is either placed after it or is missing! Kernel->Add[0] discovers AppleALC.kext, but its Parent (Lilu.kext) is either placed after it or is missing! CheckKernel returns 3 errors!
> 
> 20211012也出这个问题了。

问题已修复，请升级到最新版，欢迎发现更多的问题。

**Comment by ic005k** [comment]
目前OCAT项目除了基本的编码需要人工进行，其它均为全自动化。所以从发现问题到修复问题到产品发布，是一个很迅捷的过程。
我非常希望你们找到更多的问题，以提高OCAT的产品质量。
