### ISSUE TITLE
Skip upgrade this version

### ISSUE THREAD

**Issue by Asgardsurfer** [ic005k/QtOpenCoreConfig#59]
Hello ic005k!
You have mentioned several times that you like suggestions for the app. Latest update shows a prompt if there is an update, that is a nice feature. What would be very useful would be the ability to see the update window but have an option to not update this version (skip this version always). That way, if I want to stay on 0.7.4, it would not upgrade to 0.7.5 and would disable upgrade prompts. If the update is clicked in the menu bar, then the updates would appear. Small detail but I think it would be useful.￼￼ Many thanks!
Your app is truly the Swiss Army knife of OC!

**Comment by ic005k** [comment]
Ok, will consider adding this feature in the next version, thanks for the suggestion. More suggestions or questions are welcome, thanks.
