### ISSUE TITLE
同时运行两个程序会出现显示bug

### ISSUE THREAD

**Issue by NineTwoMay1st** [ic005k/QtOpenCoreConfig#6]
两个窗口对于不同的config.plist，一个配置窗口可能显示另一个配置的内容。

**Comment by ic005k** [comment]
收到，我这边跟踪一下这个问题，感谢反馈。

**Comment by ic005k** [comment]
问题已修复，请下载最新版本：https://github.com/ic005k/QtOpenCoreConfig/releases/tag/20201010
