### ISSUE TITLE
加入本地KEXT更新/远程KEXT下载

### ISSUE THREAD

**Issue by llity** [ic005k/QtOpenCoreConfig#60]
希望能更新本地KEXT，但是KEXT确实很多，工作量较大。

**Comment by llity** [comment]
能否记住我上次未勾选的呢？这些驱动不同步数据库里面的，每次我去掉勾选同步，打开又是默认勾选
![image](https://user-images.githubusercontent.com/11771112/139570152-e1ea1615-7db4-49a6-844a-7adb16f97e41.png)

**Comment by ic005k** [comment]
> 能否记住我上次未勾选的呢？

好的，已记录，后面会优化这块的功能。

**Comment by llity** [comment]
嗯，这样就不同多次更新驱动了

**Comment by llity** [comment]
白名单可以批量添加和删除吗？
![image](https://user-images.githubusercontent.com/11771112/139681825-5f119730-70de-43ec-9b20-8ce3beb9ae74.png)

**Comment by ic005k** [comment]
> 白名单可以批量添加和删除吗？

不可以，因为这是一个个位数的操作，一个配置文件里头不想升级的kext可能只有一个、两个的，不是大批量的。
白名单是不准确的说法，后来我改了名称：kext升级除外，这样就不会引起歧义了，更容易理解。

**Comment by llity** [comment]
或者鼠标放上去显示一个删除按钮
![image](https://user-images.githubusercontent.com/11771112/139815408-dbe95b32-e43b-4c06-a748-255b7cb0f6cb.png)

**Comment by ic005k** [comment]
> 或者鼠标放上去显示一个删除按钮

好的，一有时间我就来研究下，感谢建议。

**Comment by llity** [comment]
嗯，驱动更新功能很完善了，可以考虑一键备份功能:)

**Comment by ic005k** [comment]
> 一键备份功能

能否具体一点？

**Comment by llity** [comment]
> > 一键备份功能
> 
> 能否具体一点？

一般可以分为备份OC目录，驱动目录和config配置文件，进行版本修改控制。我看有很多出现修改配置文件后无法进系统。

**Comment by ic005k** [comment]
收到，后面会考虑这个功能的。
