### ISSUE TITLE
UI 优化建议

### ISSUE THREAD

**Issue by llity** [ic005k/QtOpenCoreConfig#64]
1. quircks等待选框的项目建议放到底部，方便选择减少tab。
![image](https://user-images.githubusercontent.com/11771112/139531837-000139ef-632e-4bc2-8954-2930d3c1bf81.png)

2. 没有 file close 菜单

3. 可以考虑把左边栏稍微加宽，项目名称显示完整
![image](https://user-images.githubusercontent.com/11771112/139531899-c30a0a9c-0a25-4c29-8291-4186af6aab7f.png)

4. 末尾的列可以不要
![image](https://user-images.githubusercontent.com/11771112/139531952-34d1433f-db6e-490e-9504-8a03b52b3ace.png)

5. 按钮 hover 是圆角，现在是方角
![image](https://user-images.githubusercontent.com/11771112/139531974-ddf7326b-4a07-4cd3-b194-dbd80bcd3bfb.png)

6. 可以把文字都换成图标
![image](https://user-images.githubusercontent.com/11771112/139532026-38c45645-a48d-4d83-8ab6-c4f0b022ccb5.png)

7. light模式可以把bar的渐变去掉
![image](https://user-images.githubusercontent.com/11771112/139532071-299f5fb3-8c84-48c2-9799-9e145dd0e8e7.png)

8. 红框加一个items？
![image](https://user-images.githubusercontent.com/11771112/139532166-dd530e9b-2320-408b-9db4-956d8c07177b.png)

建议参考吧

**Comment by ic005k** [comment]
好的，有空闲的时间，我会不断完善的。
目前还是以夯实功能为主，非常感谢建议，同时欢迎更多的建议或想法或问题。

**Comment by llity** [comment]
9. 设备属性注入无法排序
![image](https://user-images.githubusercontent.com/11771112/139569967-a507e75b-b0b2-4d17-a225-36af4fd58480.png)

**Comment by ic005k** [comment]
> 1. 设备属性注入无法排序

这个在保存之后是自动排序的，无需手动排序。

**Comment by llity** [comment]
10. 这个改回这种怎么样呢
![image](https://user-images.githubusercontent.com/11771112/139843839-af2dc804-0b8b-40ed-8b50-5ee6b3e8d4b3.png)

**Comment by ic005k** [comment]
> 1. 这个改回这种怎么样呢
>    ![image](https://user-images.githubusercontent.com/11771112/139843839-af2dc804-0b8b-40ed-8b50-5ee6b3e8d4b3.png)

之前是下图的样式，但是在macOS10.12及以下的系统里面会显示不正常，所以改用目前的样式。后面有时间的话，再找找原因。

**Comment by llity** [comment]
好的，QT能更原生就好了

**Comment by ic005k** [comment]
> 好的，QT能更原生就好了

对于工具软件来说，性能和功能最重要，UI其次。
