### ISSUE TITLE
NVRAM -> Add，子节点都是一样的

### ISSUE THREAD

**Issue by zcgg2zhmm** [ic005k/QtOpenCoreConfig#65]
![image](https://user-images.githubusercontent.com/29967092/139566131-be660833-2854-4a31-837e-3b4fa084d0c7.png)

**Comment by ic005k** [comment]
请问你目前使用的OCAT版本，或者能否提一下操作步骤，看我这边能否复现这个问题？
请尽量地提供一些比较详细的信息，便于我查找和分析这个问题，谢谢。

**Comment by ic005k** [comment]
还有，是这个文件里面的数据之前都是一样的，还是经过OCAT打开后出现的这个问题？
能否提供一下原始文件？

**Comment by zcgg2zhmm** [comment]
> 请问你目前使用的OCAT版本，或者能否提一下操作步骤，看我这边能否复现这个问题？ 请尽量地提供一些比较详细的信息，便于我查找和分析这个问题，谢谢。

谢谢您的回复！
主要步骤：数据库 -> 配置文件列表 -> 双击Sample.plist -> 桌面EFI文件夹 -> 用properTree打开config.plist

![image](https://user-images.githubusercontent.com/29967092/139567092-a4f2ed04-28ef-469d-893f-87e2f50b49a0.png)

**Comment by ic005k** [comment]
这是一个奇怪的现象，我现在在Linux下，按照你的步骤，一切正常。
我切换到Mac下看看。

**Comment by ic005k** [comment]
我切换到Mac下也是正常的，这是什么原因导致的呢？
![add](https://user-images.githubusercontent.com/25247437/139567446-9f521ec2-ad02-451d-9825-3a1b7a9b9ae1.png)

**Comment by zcgg2zhmm** [comment]
> 我切换到Mac下也是正常的，这是什么原因导致的呢？ ![add](https://user-images.githubusercontent.com/25247437/139567446-9f521ec2-ad02-451d-9825-3a1b7a9b9ae1.png)

真的是太奇怪了

**Comment by ic005k** [comment]
> 真的是太奇怪了

所以我们要找出这个现象的原因，随时欢迎你提供更多的线索。

**Comment by llity** [comment]
我也是正常的

**Comment by ic005k** [comment]
请升级OCAT至最新版，看是否出现同样的问题。

**Comment by zcgg2zhmm** [comment]
> 请升级OCAT至最新版，看是否出现同样的问题。

厉害了！！！可以了~~
