### ISSUE TITLE
DeviceProperties -> Add，子节点不论怎么切换，右边都不变

### ISSUE THREAD

**Issue by zcgg2zhmm** [ic005k/QtOpenCoreConfig#66]
如图，在用您的可视化工具的时候，切到DP这一项的add下面，PCI List切换，但是右边的详情都是一样的：

![image](https://user-images.githubusercontent.com/29967092/139566260-a3fdbd34-d286-4c15-aec9-42d3d8240c12.png)

properTree看到的如下图：

![image](https://user-images.githubusercontent.com/29967092/139566888-a1580504-9025-4681-a5cd-42be873c1ba3.png)

感觉好像修改了我之前的plist，不知道是不是我哪里使用不当，请您指明，谢谢~

**Comment by ic005k** [comment]
能否说下操作步骤，最好能提供原始文件，我这边分析看看？

**Comment by zcgg2zhmm** [comment]
> 能否说下操作步骤，最好能提供原始文件，我这边分析看看？

再次感谢您的回复~
步骤如下：
原始config.plist -> ocat打开 -> 保存（或者，修改点东西，再保存） -> 再用properTree打开 -> 出现如题目图片所示的问题

**Comment by ic005k** [comment]
我打开了你提供的文件，保存之后也是非常正常的。看来这个问题，在你那边是始终存在的，不管打开哪个配置文件，均会出现这个问题。

**Comment by ic005k** [comment]
我会分析一下这个现象的，如果你那边有其他任何线索，请及时提供，谢谢。

**Comment by zcgg2zhmm** [comment]
> 我会分析一下这个现象的，如果你那边有其他任何线索，请及时提供，谢谢。

和我提供的另一个问题，感觉是类似的，应该有关联~
同样也感谢你的回复~
我也回持续观察的~

**Comment by ic005k** [comment]
> 我也会持续观察的~

好的。对了，你之前使用OCAT有出现这个现象吗？如果这个现象没找到原因的话，请暂停使用OCAT，等找到原因再启用。

**Comment by zcgg2zhmm** [comment]
> > 我也会持续观察的~
> 
> 好的。对了，你之前使用OCAT有出现这个现象吗？如果这个现象没找到原因的话，请暂停使用OCAT，等找到原因再启用。

不得不承认ocat很好用，排错很人性化，驱动下载很方便，对于第一次使用的我来说，真的很惊艳。
哎，可惜第一次使用就遇到这两个问题~
我暂时用回oc和properTree吧~
感谢~~~~

**Comment by ic005k** [comment]
请下载或升级成最新版的OCAT试用看看，是否出现同样的问题。

**Comment by zcgg2zhmm** [comment]
> 请下载或升级成最新版的OCAT试用看看，是否出现同样的问题。

解决了~~厉害厉害！！
