### ISSUE TITLE
不明白预设值文件是怎么用的

### ISSUE THREAD

**Issue by k2y1982** [ic005k/QtOpenCoreConfig#67]
如题

**Comment by ic005k** [comment]
就是事先定义好的一些内容，可以在这些内容的基础上添加或修改成自己的东西，或者供自己在配置OC时参考。
在预置界面中双击预置条目，即可添加到相应的表中。
OCAT的预置是完全开放性的，谁都可以编辑或修改它，在“编辑”菜单中打开预置文件即可进行编辑和修改。
