### ISSUE TITLE
进程合并，打开新文件打开新进程，而不是覆盖已打开的配置文件进程。

### ISSUE THREAD

**Issue by llity** [ic005k/QtOpenCoreConfig#69]
进程图标能合并吧？打开新配置文件是默认在第一个进程中打开，可以改为新建进程打开。尽管我已新建了一个进程也是在第一个进程中打开。
![image](https://user-images.githubusercontent.com/11771112/139816313-5d5c18d8-8ca0-47b2-a66b-0e3f663770f8.png)

**Comment by ic005k** [comment]
这个功能我会好好考虑下，觉着不是很必要，显得非常乱，你打开一个文件就会开一个新窗口，这样窗口会越来越多。
其实设计打开另外一个新进程，完全是为两个配置文件进行对比或数据交换，没别的意图。

**Comment by ic005k** [comment]
OCAT的设计目标是足够简洁、简单、清晰、易于使用，我回头可能还会减掉一些东西，否则太凌乱了。

**Comment by ic005k** [comment]
还有，如果时间允许的话，OCAT将会设计得足够精致。欢迎任何建议或想法，我都会认真看的。

**Comment by ic005k** [comment]
> 进程图标能合并

用鼠标选择窗口时，会多增加一下鼠标点击次数。在win10下倒是自动合并的，觉着用鼠标切换窗口非常不方便，特别是在小屏幕的笔电上，如果屏幕足够大，那倒是无所谓，可以在屏幕上多排布几个窗口。

**Comment by ic005k** [comment]
对了，OCAT不是一个原生的macOS程序，你不能用macOS原生程序的那种展现方式来体验它，它是一个跨平台、几乎能适应各种分辨率环境和PE、Linux live cd等等环境的一个工具软件，OCAT作为一个工具软件，几乎能在所有的桌面环境下正常运行。

**Comment by llity** [comment]
> 对了，OCAT不是一个原生的macOS程序，你不能用macOS原生程序的那种展现方式来体验它，它是一个跨平台、几乎能适应各种分辨率环境和PE、Linux live cd等等环境的一个工具软件，OCAT作为一个工具软件，几乎能在所有的桌面环境下正常运行。

好的，但在已打卡一个配置文件的情况下，再从文件夹打开一个配置文件建议在新进程中打开。现在会覆盖已打开的文件，或者要先打开一个进程，再把配置文件拖到软件里才行。

**Comment by ic005k** [comment]
> 但在已打卡一个配置文件的情况下，再从文件夹打开一个配置文件建议在新进程中打开。现在会覆盖已打开的文件，或者要先打开一个进程，再把配置文件拖到软件里才行。

好的，已记录，后面慢慢完善。
