### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by btwise** [ic005k/QtOpenCoreConfig#7]
1.主分类标签卡建议采用竖排大标签，小分类做横排
2.SMBIOS信息可以使用单独plist加载，也可以加入在线导入补丁等信息的功能

**Comment by ic005k** [comment]
收到，请关注软件后续的升级，感谢反馈

**Comment by btwise** [comment]
> 收到，请关注软件后续的升级，感谢反馈

可以参考OCC或CCG的界面布局和功能

**Comment by btwise** [comment]
左侧的大分类区域不要割裂，用图片控件做分类点击元素，右侧的TAB选项卡和容器不要割裂，在做些效果美化这样是不是好一些

**Comment by ic005k** [comment]
好的，我又发了一版，看看是不是你说的这种效果。至于图片按钮，目前因为时间的关系，暂时不考虑。
至于在线资源等内容，后续会搜集并考虑如何集成到软件里面。
总之，QtOpenCoreConfig将会成为黑苹果引导领域的一部活字典，有关引导相关的资源，都可以从该软件获得。当然这只是我的一点想法而已，需要时间来逐一实现。
欢迎提供任何建议！

**Comment by btwise** [comment]
> 好的，我又发一版，看看是不是你说的这种效果。至于图片按钮，目前因为时间的关系，暂时不考虑。
> 至于在线资源等内容，后续会搜集并考虑如何集成到软件里面。
> 总之，QtOpenCoreConfig将成为黑苹果引导领域的一部活字典，有关引导相关的资源，都可以从该软件获得。当然这只是我的一点想法而已，需要时间来逐一实现。
> 欢迎提供任何建议！

是的，不应该只是单纯的编辑器，而应该成为一个全能的工具软件，OCC的后期版本功能创意大多数都是我构思的，然后由mackie100来完成编程的:)

**Comment by btwise** [comment]
一些地方建议：
1、所有的条目区域，ACPI-Add,KERNEL-Add,UEFI-Drivers，条目不能批量进行操作，比如多个选择一次删除，不能进行拖拽添加或拖拽移动顺序，所有条目应该可以一次性或多个选择添加，支持拖拽等
2、在一些选项，应当添加自动计算功能，比如MISC-Security-ScanPolic,可以给出自动计算结果，让用户选择，而不必要自己手动计算，容易出错
3、在UEFI部分内容比较少的区域，选项布局应该紧凑，而不要太过散乱
4、Quirks区域用分割线和标题区分出来，每个区域都放置固定位置
5、机型设置部分，UpdateSMBIOSMode下拉选择里，是否是用Auto还是TryOverwrite?
6、机型设置部分，如果选择Automatic选项，应当在配置文件里只出现Generic部分内容，而不包含其他部分内容，是否应当加以控制？
7、所有功能提示，不应按照PDF文档翻译，应该使用通俗易懂的中文语言来翻译，大量专业术语对普通用户并没有太大意义，也浪费编译者时间

**Comment by ic005k** [comment]
> 一些地方建议：
> 1、所有的条目区域，ACPI-Add,KERNEL-Add,UEFI-Drivers，条目不能批量进行操作，比如多个选择一次删除，不能进行拖拽添加或拖拽移动顺序，所有条目应该可以一次性或多个选择添加，支持拖拽等
> 2、在一些选项，应当添加自动计算功能，比如MISC-Security-ScanPolic,可以给出自动计算结果，让用户选择，而不必要自己手动计算，容易出错
> 3、在UEFI部分内容比较少的区域，选项布局应该紧凑，而不要太过散乱
> 4、Quirks区域用分割线和标题区分出来，每个区域都放置固定位置
> 5、机型设置部分，UpdateSMBIOSMode下拉选择里，是否是用Auto还是TryOverwrite?
> 6、机型设置部分，如果选择Automatic选项，应当在配置文件里只出现Generic部分内容，而不包含其他部分内容，是否应当加以控制？
> 7、所有功能提示，不应按照PDF文档翻译，应该使用通俗易懂的中文语言来翻译，大量专业术语对普通用户并没有太大意义，也浪费编译者时间

好的，后面会逐一完善，感谢建议！

**Comment by btwise** [comment]
@ic005k 
自定义内存如果为false时，内存信息的数据应该为不可编辑状态，也不必在config里写入

**Comment by btwise** [comment]
![(USA81L(61(VP6H7}6ESZQV](https://user-images.githubusercontent.com/38809560/97268997-bf976400-1867-11eb-83f1-3b5d1fb16fc0.png)

**Comment by ic005k** [comment]
> @ic005k
> 自定义内存如果为false时，内存信息的数据应该为不可编辑状态，也不必在config里写入
> 
> 如果打开旧版本的config文件，保存后发现一些失效的选项或移动位置的选项还保留在config里，不能正确保存为新版本的config

好的，问题已记录，已纳入bug追踪系统。你说的这个问题应该不会存在，因为QtOpenCoreConfig写入文件的机制，不是采用增量的方式，而是采用全新写入的方式。也就是说旧版的config.plist进来后，如果保存的话，会全新以QtOpenCoreConfig的现存的有效数据进行写入，会覆盖所有的旧数据。

**Comment by ic005k** [comment]
关于自定义内存，即便用户设置为false，也不能抹去用户之前既定的数据，以便用户后面启用『自定义内存』的时候，可以复用这些数据。如果CustomMemory为false，OC会忽略这一块的数据，我认为完全没有必要清除内存自定义的这块数据。

**Comment by btwise** [comment]
> > @ic005k
> > 自定义内存如果为false时，内存信息的数据应该为不可编辑状态，也不必在config里写入
> > 如果打开旧版本的config文件，保存后发现一些失效的选项或移动位置的选项还保留在config里，不能正确保存为新版本的config
> 
> 好的，问题已记录，已纳入bug追踪系统。你说的这个问题应该不会存在，因为QtOpenCoreConfig写入文件的机制，不是采用增量的方式，而是采用全新写入的方式。也就是说旧版的config.plist进来后，如果保存的话，会全新以QtOpenCoreConfig的现存的有效数据进行写入，会覆盖所有的旧数据。

我会在详细测试的，之前好像是有这个问题的！

**Comment by btwise** [comment]
> 关于自定义内存，即便用户设置为false，也不能抹去用户之前既定的数据，以便用户后面启用『自定义内存』的时候，可以复用这些数据。如果CustomMemory为false，OC会忽略这一块的数据，我认为完全没有必要清除内存自定义的这块数据。

随着OC选项越来越多，config会越来越大，增加阅读时间，而且很多用OC的都是强迫症，尽管写入config并不影响使用，我只是一个建议
