### ISSUE TITLE
驱动更新疑问

### ISSUE THREAD

**Issue by llity** [ic005k/QtOpenCoreConfig#71]
自定义的驱动也会出现，有的驱动又没有。
同样的版本号，MD5值不一样
数据库里面和本地同时存在的驱动才会出现在这里吗？
![image](https://user-images.githubusercontent.com/11771112/140247151-12298274-c85a-4d8d-a4ae-5287704634c7.png)

**Comment by llity** [comment]
我自定义驱动链接，没有显示怎么更新。

**Comment by ic005k** [comment]
这个更新的规则马上就会补上，请稍等一下，忙完手头的事情就会升级一下kext的更新规则。

**Comment by llity** [comment]
> 这个更新的规则马上就会补上，请稍等一下，忙完手头的事情就会升级一下kext的更新规则。

好的，谢谢 :)

**Comment by ic005k** [comment]
更新以推送，GitHub的服务器正在编译中，估计6～7分钟完成编译，你那边就可以收到更新了。再次感谢关注。

**Comment by llity** [comment]
已收到。很多驱动source file没有显示红色是什么意思，USBMap也没有却显示绿色。可以在不勾选的状态下多一个检查更新功能，在勾选后更新，发现有的驱动最新版并不一定好用，可以先检查更新。
![image](https://user-images.githubusercontent.com/11771112/140249772-228fddd9-927d-4edc-bfa6-8cd7042911b5.png)

**Comment by ic005k** [comment]
目前更新kext的方法是，只要你勾选了该kext，就会更新它到最新版，没有其它的任何远程检测。

有考虑过远程检测，但每个kext的开发者在gtihub的发布页面都有自己个性化的版本描述，没有标准的格式供你识别版本号，而且这个版本描述也可能kext的作者会下一个版本发布时更改它，一句话，这是个非标准化的内容。

唯一能准确识别版本号的途径是直接检测kext文件本身，这样你就没法远程检测了，必须下载到本地，这个过程还不如直接更新它来得直接。

如果你有更好的创意，请随时留言告诉我，谢谢。

**Comment by ic005k** [comment]
其实在在线更新kext这块我个人也没什么好的创意，直至昨天国外的网友提出他的解决方案和用户交互样式，就是目前的这种方式。我相信你们会有更好的想法，一起来完善它。

**Comment by llity** [comment]
这样集中更新可以，目前这里面已经罗列所有KEXT目录的驱动，建议先CHECK更新，标红，再勾选需要的驱动更新？
![image](https://user-images.githubusercontent.com/11771112/140257026-8d73ec14-09e4-405b-9132-bb5ede469658.png)

**Comment by ic005k** [comment]
> 不知道同步后TOOLS的文件是否也更新了呢

是的，更新了，只要你打了对勾。其实规则很简单：凡是打对勾的都会被同步或者更新。

**Comment by ic005k** [comment]
> 建议先CHECK更新，标红，再勾选需要的驱动更新？

建议已收集，我会综合其他用户的想法，不断完善它。

**Comment by ic005k** [comment]
你可以将EFI文件夹拷贝到其他地方，比如文档里面，这样就可以随便测试OCAT了。

**Comment by ic005k** [comment]
OCAT的使用可以在任何具有OC EFI结构的地方进行，不一定非要在ESP分区里面才能使用。

**Comment by llity** [comment]
> > 建议先CHECK更新，标红，再勾选需要的驱动更新？
> 
> 建议已收集，我会综合其他用户的想法，不断完善它。

嗯，没有定义更新源的建议标记为灰色

**Comment by llity** [comment]
> 目前在线更新kext的方法是，只要你勾选了该kext，就会更新它到最新版，没有其它的任何远程检测。
> 
> 有考虑过远程检测，但每个kext的开发者在gtihub的发布页面都有自己个性化的版本描述，没有标准的格式供你识别版本号，而且这个版本描述也可能kext的作者会下一个版本发布时更改它，一句话，这是个非标准化的内容。
> 
> 唯一能准确识别版本号的途径是直接检测kext文件本身，这样你就没法远程检测了，必须下载到本地，这个过程还不如直接更新它来得直接。
> 
> 如果你有更好的创意，请随时留言告诉我，谢谢。

我看hachintool可以实现，不知道是什么方法。
![image](https://user-images.githubusercontent.com/11771112/140299828-073ea757-e86e-464e-9d4e-5faa3d56bcec.png)

**Comment by ic005k** [comment]
> 我看hachintool可以实现，不知道是什么方法。

这种检测方法针对标准化的tagName是可以的，但是也容易误检，比如下面的图：
最好的办法就对kext文件本身进行检测。
![ver](https://user-images.githubusercontent.com/25247437/140300958-af2c0eb7-fdc8-4336-b28b-4982342f9026.png)

**Comment by llity** [comment]
那就难以实现了

**Comment by ic005k** [comment]
> 那就难以实现了

没事，我来想办法

**Comment by Asgardsurfer** [comment]
Found a typo in the online Documentation
In the "OpenCore" list, select the OpenCore files, drivers you want to update and click on _**"Star Sync"**_. The same color coding applies!

**Comment by ic005k** [comment]
> Found a typo in the online Documentation
Please submit directly on the author page of the document, your feedback is greatly appreciated.

**Comment by llity** [comment]
第二次检测，卡住了，stop点击没反应。
![image](https://user-images.githubusercontent.com/11771112/140457574-e2ecb1df-17d6-4cf6-97eb-998a237248da.png)

**Comment by llity** [comment]
就检测一次更新，没有做任何更改，怎么需要保存呢？
![image](https://user-images.githubusercontent.com/11771112/140457847-5852917e-dcc6-4ebf-9d6b-a2c44f1179b5.png)

**Comment by llity** [comment]
完美运行，感谢！

**Comment by ic005k** [comment]
> 第二次检测，卡住了，stop点击没反应。

你设置成“爬取网页源代码”来检测更新（数据库界面的杂项里面），这样就没有次数限制，访问GitHub的API是有次数限制的，每个IP每小时60次，如果对方做了认证的话，每小时5000次，但kext的开发者一般都没有做这个认证。

**Comment by ic005k** [comment]
> 就检测一次更新，没有做任何更改，怎么需要保存呢？

检测完成后，会自动刷新一次版本号，在Kernel的Add表里。此时会有个写入表的动作，所以需要提醒保存，同时也为了那些刚接触OCAT只是点击了同步而没有更新配置文件的用户提供了更新配置文件的动作（保存）。

**Comment by llity** [comment]
哦，这样合理。我发现检测更新后，即使驱动版本一样，点击更新也会替换掉所有勾选的项。可以加个select outdated？去掉其他不用更新的吗？当然手动勾选也没什么问题。

**Comment by ic005k** [comment]
> 完美运行，感谢！

同时也谢谢你提供了这个思路，很好的创意，一举多得
1.解决了精确检测kext版本的问题
2.解决了更新数据库的问题，因为在检测更新的时候，会自动更新数据库，所以以后GitHub服务器端的OCAT数据库我可以不用维护了
3.你只需关注标红的项目，这个是需要升级的项目
4.没有提供kext升级网址的项目进行标灰，也是不错创意
OCAT基本差不多了，同时欢迎更多的创意和发现更多的问题

**Comment by ic005k** [comment]
> 也会替换掉所有勾选的项

是的，这个就不在做更多的逻辑判断了，这个过程很短，就是拷贝几个文件而已

**Comment by llity** [comment]
对的，国内开源软件不多，也是我学习的榜样。
现在就打磨细节了。再次感谢！

**Comment by ic005k** [comment]
好，有时间，我会不断完善的
