### ISSUE TITLE
不能挂载EFI

### ISSUE THREAD

**Issue by zcgg2zhmm** [ic005k/QtOpenCoreConfig#72]
如图，挂载efi分区没有效果

![image](https://user-images.githubusercontent.com/29967092/140464208-a8fc1e80-cba7-48d1-bec9-23baac30c77b.png)

**Comment by llity** [comment]
测试可以，建议给已挂载的硬盘加个打开按钮。
![image](https://user-images.githubusercontent.com/11771112/140465844-c002d1b6-a8a8-4b1e-9d35-73a53de8c42d.png)

**Comment by ic005k** [comment]
> 没有效果

具体是指？点击“挂载”按钮没反应？

**Comment by ic005k** [comment]
> 发现很多硬盘检测不到，也有重复

OCAT只挂载ESP分区，一般来说一块硬盘只有一个ESP分区。其它的所谓EFI分区，其实就是个普通分区，直接就可以打开，不用挂载。
至于有重复，我先记录下来，回头会关注的。

**Comment by ic005k** [comment]
> 有重复

你回头运行下：diskutil list
将结果贴出来，我分析看看。

**Comment by llity** [comment]
查看

> `❯ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *2.0 TB     disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                 Apple_APFS Container disk6         2.0 TB     disk0s2

/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk1
   1:                        EFI EFI                     209.7 MB   disk1s1
   2:                 Apple_APFS Container disk5         1.0 TB     disk1s2

/dev/disk2 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk2
   1:                        EFI NO NAME                 314.6 MB   disk2s1
   2:           Linux Filesystem                         999.9 GB   disk2s2

/dev/disk3 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *8.0 TB     disk3
   1:       Microsoft Basic Data Hub                     8.0 TB     disk3s1

/dev/disk4 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *512.1 GB   disk4
   1:           Windows Recovery                         554.7 MB   disk4s1
   2:                        EFI NO NAME                 104.9 MB   disk4s2
   3:         Microsoft Reserved                         16.8 MB    disk4s3
   4:       Microsoft Basic Data                         510.8 GB   disk4s4
   5:           Windows Recovery                         606.1 MB   disk4s5

/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +1.0 TB     disk5
                                 Physical Store disk1s2
   1:                APFS Volume DateSea                 455.0 GB   disk5s1

/dev/disk6 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +2.0 TB     disk6
                                 Physical Store disk0s2
   1:                APFS Volume macOS - Data            1.8 TB     disk6s1
   2:                APFS Volume Preboot                 691.0 MB   disk6s2
   3:                APFS Volume Recovery                1.1 GB     disk6s3
   4:                APFS Volume VM                      3.2 GB     disk6s4
   5:                APFS Volume macOS                   15.7 GB    disk6s5
   6:              APFS Snapshot com.apple.os.update-... 15.7 GB    disk6s5s1

/dev/disk7 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk7
   1:       Microsoft Basic Data                         1.1 GB     disk7s1
   2:           Linux Filesystem                         499.0 GB   disk7s2

/dev/disk8 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *3.0 TB     disk8
   1:           Linux Filesystem                         3.0 TB     disk8s1

/dev/disk9 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk9
   1:                        EFI EFI                     209.7 MB   disk9s1
   2:       Microsoft Basic Data data                    1000.0 GB  disk9s2

/dev/disk10 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *30.8 GB    disk10
   1:       Microsoft Basic Data Ventoy                  30.7 GB    disk10s1
   2:       Microsoft Basic Data VTOYEFI                 33.6 MB    disk10s2

/dev/disk11 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk11
   1:                        EFI EFI                     209.7 MB   disk11s1
   2:                 Apple_APFS Container disk12        1.0 TB     disk11s2

/dev/disk12 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +1.0 TB     disk12
                                 Physical Store disk11s2
   1:                APFS Volume Liang                   1.0 TB     disk12s1`

**Comment by llity** [comment]
> > 发现很多硬盘检测不到，也有重复
> 
> OCAT只挂载ESP分区，一般来说一块硬盘只有一个ESP分区。其它的所谓EFI分区，其实就是个普通分区，直接就可以打开，不用挂载。 至于有重复，我先记录下来，回头会关注的。

确实Windows分区和Linux分区，仓库盘重复。有一定随机性，上次是2T的重复，这次是1T的重复

**Comment by llity** [comment]
最近打开也有重复，能记住没有挂载EFI分区的文件路径吗？
![image](https://user-images.githubusercontent.com/11771112/140499669-53d5bb03-ae76-467b-a7d9-6a0207535908.png)

**Comment by ic005k** [comment]
> 最近打开也有重复，能记住没有挂载EFI分区的文件路径吗？

好的，已记录。

**Comment by ic005k** [comment]
> 缺少Windows分区和Linux分区，仓库盘重复。有一定随机性，上次是2T的重复，这次是1T的重复

已记录

**Comment by ic005k** [comment]
> 能记住没有挂载EFI分区的文件路径吗？

目前不行，因为OCAT会在下次打开的时候自动过滤掉不存在的路径。
你们为什么还是喜欢用旧式的方式来引导OC呢，你将OC放在一个普通的FAT32分区里面，既不用挂载ESP，编辑修改OC也容易，OCAT也能记住这个路径。你把OC放到ESP分区里面，这是非常古老的方式，相当麻烦，每次都需要挂载ESP，对于修改OC来说相当折磨人。

**Comment by ic005k** [comment]
@llity 其实挂载ESP是个历史遗留，是为极少数人准备的，貌似在黑苹果领域，已经没人使用ESP分区了，ESP分区是留给Windows用的。

**Comment by llity** [comment]
> @llity 其实挂载ESP是个历史遗留，是为极少数人准备的，貌似在黑苹果领域，已经没人使用ESP分区了，ESP分区是留给Windows用的。

应该是安装系统后，直接软件挂载生产的分区。这样分区平时就被隐藏。你的意思是硬盘分区一个FAT32和系统盘即可。FAT32随时可见？在Linux什么是一个boot分区，然后挂载到系统盘文件夹下面。

**Comment by ic005k** [comment]
> 硬盘分区一个FAT32

对，比如500M的大小，在机器的BIOS里面把这个分区放到第一位就可以了。我截图你看看
![分区](https://user-images.githubusercontent.com/25247437/140518955-9b6da11b-e710-4386-a323-5ab120be5dd2.png)

**Comment by ic005k** [comment]
你看看我上面的截图，根本就不用ESP分区，ESP是留给Win10用的。OC所在的分区随时可见，修改什么非常便利。

**Comment by llity** [comment]
> 你看看我上面的截图，根本就不用ESP分区，ESP是留给Win10用的。OC所在的分区随时可见，修改什么非常便利。

这样确实方便，只是系统默认都是隐藏的，Linux安装建议也是通过挂载到一个目录，也不知道这样做的目的是什么。

**Comment by ic005k** [comment]
> 最近打开也有重复，能记住没有挂载EFI分区的文件路径吗？ ![image](https://user-images.githubusercontent.com/11771112/140499669-53d5bb03-ae76-467b-a7d9-6a0207535908.png)

我查了下代码，没有问题。后来仔细看图，发现你这两个文件并没有重复，Config一个是大写的C一个是小写的c，是两个不同的文件。
另外建议你将ESP分区的卷标重新命名一下，比如ESP1、ESP2等等，便于区分。你目前所有的卷标都是“EFI”。

**Comment by llity** [comment]
是同一个文件，不知道为什么会出现大小写，本地文件是小心。

**Comment by llity** [comment]
大写也能打开
![image](https://user-images.githubusercontent.com/11771112/140706451-6baf3a5a-37ca-4b01-9dbb-2d51597e22e6.png)

**Comment by llity** [comment]
这里没有加载所有主题文件夹
![image](https://user-images.githubusercontent.com/11771112/140706824-37c9f954-89d3-46dd-a0c0-aa2098c52742.png)

**Comment by llity** [comment]
> > 最近打开也有重复，能记住没有挂载EFI分区的文件路径吗？ ![image](https://user-images.githubusercontent.com/11771112/140499669-53d5bb03-ae76-467b-a7d9-6a0207535908.png)
> 
> 我查了下代码，没有问题。后来仔细看图，发现你这两个文件并没有重复，Config一个是大写的C一个是小写的c，是两个不同的文件。 另外建议你将ESP分区的卷标重新命名一下，比如ESP1、ESP2等等，便于区分。你目前所有的卷标都是“EFI”。

可以判断已挂载的盘吗？不用输入密码，直接打开。

**Comment by ic005k** [comment]
> 这里没有加载所有主题文件夹

这里本身也没有做自动识别，因为之前OC的主题规则一直在改变，所以此处由用户自行输入即可。

**Comment by ic005k** [comment]
> 是同一个文件，不知道为什么会出现大小写，本地文件是小写。

可能来自不同的卷，目前看不出来是来自哪个卷，因为你ESP所有的卷标都一样，都是“EFI”。
你改下卷标，就可以判断是不是同一个文件了。

**Comment by llity** [comment]
> > 是同一个文件，不知道为什么会出现大小写，本地文件是小写。
> 
> 可能来自不同的卷，目前看不出来是来自哪个卷，因为你ESP所有的卷标都一样，都是“EFI”。 你改下卷标，就可以判断是不是同一个文件了。

真一样，打开一模一样

**Comment by ic005k** [comment]
> 真一样，打开一模一样

这就有点奇怪了，总之找到原因后，告知一声。

**Comment by ic005k** [comment]
> 需要加个清除历史记录功能

好的，已记录。

**Comment by llity** [comment]
栏目tabs强烈建议这种式样，减少线条和白底
![image](https://user-images.githubusercontent.com/11771112/140722294-80b1f9d2-c4c0-47a6-b433-5ac867bdabe1.png)

**Comment by ic005k** [comment]
> 栏目tabs强烈建议这种式样，减少线条和白底

这个工作量就大了，我先记下来，有时间再规划下。

**Comment by llity** [comment]
> > 栏目tabs强烈建议这种式样，减少线条和白底
> 
> 这个工作量就大了，我先记下来，有时间再规划下。

对啊，UI打磨就是很费神。加油💪🏻

**Comment by btwise** [comment]
虽然FAT32分区对于UEFI引导是可以识别的，但黑苹果很多时候在一个硬盘里有多个操作系统，共用一个EFI分区，所以规范GPT ESP格式是有必要的，不要随意暴露引导分区

**Comment by llity** [comment]
> 虽然FAT32分区对于UEFI引导是可以识别的，但黑苹果很多时候在一个硬盘里有多个操作系统，共用一个EFI分区，所以规范GPT ESP格式是有必要的，不要随意暴露引导分区

看archwiki，有必要。

**Comment by ic005k** [comment]
> 这里没有加载所有主题文件夹

这个细节回头会完善它，如果你知道规则，请随时告诉我，谢谢。
我确实没有太多时间去折腾OC的主题，你只需告诉我如何做就可以了。

**Comment by zcgg2zhmm** [comment]
其实把esp改成efi就行了

**Comment by zcgg2zhmm** [comment]
> 其实把esp改成efi就行了

改正一下，我的是双系统是在同一块固态上的。我发现，如果esp分区在第一个，第二个是mac系统分区，就能挂载成功。
