### ISSUE TITLE
检测更新 -> 网络错误，貌似涉及到联网的，都是网络错误

### ISSUE THREAD

**Issue by zcgg2zhmm** [ic005k/QtOpenCoreConfig#73]
![image](https://user-images.githubusercontent.com/29967092/140464403-44d2bdec-fffd-4223-9706-92b39c8a62ed.png)

![image](https://user-images.githubusercontent.com/29967092/140464423-83436852-8815-45c5-baa3-34fc6523ea25.png)

**Comment by llity** [comment]
在数据库里面设置一下代理？

**Comment by ic005k** [comment]
对，设置下代理

**Comment by zcgg2zhmm** [comment]
> 对，设置下代理

设置代理是什么意思？是这样吗？换？好像换了几个都不行，请赐教~~~

![image](https://user-images.githubusercontent.com/29967092/140672303-b1118e8b-3c62-4d6f-b965-5f26a2006ff7.png)

**Comment by ic005k** [comment]
是的，选一个最快的代理，比如我这边https://download.fastgit.org/非常快，下载更新只需几秒钟。

**Comment by ic005k** [comment]
> 好像换了几个都不行

你点击“测试”按钮后稍等3～5秒，看看有没有反应，与服务器握手需要一些时间的。

**Comment by ic005k** [comment]
如果列表中所有的代理都无法使用的话，你也可以直接在上面输入你自己的代理，这都非常灵活的。

**Comment by zcgg2zhmm** [comment]
> 如果列表中所有的代理都无法使用的话，你也可以直接在上面输入你自己的代理，这都非常灵活的。

okay~ get! thanks very much~
