### ISSUE TITLE
您好，工具很好用，但能否添加一个版本选择的功能？

### ISSUE THREAD

**Issue by jackge0323** [ic005k/QtOpenCoreConfig#74]
比如我只想用opencore 0.7.5稳定版，不想升级到最新版，但是现在工具默认保存就会保存成最新版的配置文件，能否添加一个版本选择的功能，或者选择稳定版或最新版的功能，oc没升级到最新版，配置文件升级了，开机会有提示，让我比较苦恼。

**Comment by ic005k** [comment]
很简单，有两种途径：
1.下载最新的0.7.5版本的OCAT，在“帮助”菜单下关闭”自动检查更新“。
2.继续使用最新版本的OCAT，在工具栏的”同步OC主程序“里面同步一下OC到最新版。
很明显，我建议你采用第二个途径，将OC升级到最新版，请相信最新版本的OC是可靠的、安全的、更好的。

**Comment by ic005k** [comment]
OC作为引导程序，它不同于其它APP，它的特点是永远都是最新的最好，它解决了之前版本的一些问题。所以，OCAT不会增加一个版本选择的功能，因为实在是没有必要为一个旧版本而停留脚步。感谢反馈，同时欢迎更多的建议和发现更多的问题。

**Comment by llity** [comment]
> > 加个开关兼顾正式版和开发版更新？
> 
> 这不是简单的加个开关的问题，它涉及到底层逻辑和数据库，你需要为每个版本做一个底层逻辑判断和数据库，这样就非常庞大了，实际意义不大，谁又会长期的去用一个旧版的OC呢？

肯定新的好，不过确实有不想更新最新版的需求。

**Comment by llity** [comment]
加个开关兼顾正式版和开发版更新？

**Comment by ic005k** [comment]
> 肯定新的好，不过确实有不想更新最新版的需求。

你也可以思考下，关于这个问题，看看有没有更好的创意。

**Comment by llity** [comment]
> > 加个开关兼顾正式版和开发版更新？
> 
> 这不是简单的加个开关的问题，它涉及到底层逻辑和数据库，你需要为每个版本做一个底层逻辑判断和数据库，这样就非常庞大了，实际意义不大，谁又会长期的去用一个旧版的OC呢？

有部分人有这个需求。
发现鼠标放上去文字会往右移动
![image](https://user-images.githubusercontent.com/11771112/140640099-90a38a7f-bae0-45c0-96e7-43992278c594.png)

**Comment by ic005k** [comment]
> 发现鼠标放上去文字会往右移动

这个一种触感视觉效果。
坦率地讲，OCAT的UI还有很大的提升空间，慢慢完善吧。

**Comment by ic005k** [comment]
> 加个开关兼顾正式版和开发版更新？

这不是简单的加个开关的问题，它涉及到底层逻辑和数据库，你需要为每个版本做一个底层逻辑判断和数据库，这样就非常庞大了，实际意义不大，谁又会长期的去用一个旧版的OC呢？

**Comment by llity** [comment]
> > 发现鼠标放上去文字会往右移动
> 
> 这个一种触感视觉效果。 坦率地讲，OCAT的UI还有很大的提升空间，慢慢完善吧。

UI要狠狠的打磨。黑暗模式没这个动效？
![image](https://user-images.githubusercontent.com/11771112/140640674-e0515b62-5fdc-46a5-8253-319f5ba3d42d.png)

栏目居中？
![image](https://user-images.githubusercontent.com/11771112/140640699-f6f7947b-8e21-4829-818a-a23fd7d4fa97.png)

**Comment by llity** [comment]
> > 加个开关兼顾正式版和开发版更新？
> 
> 这不是简单的加个开关的问题，它涉及到底层逻辑和数据库，你需要为每个版本做一个底层逻辑判断和数据库，这样就非常庞大了，实际意义不大，谁又会长期的去用一个旧版的OC呢？

很多是用正式版，开发版更新频繁。不过OC现在更新的内容也不多。本地保存一份OC正式版用于同步？

**Comment by ic005k** [comment]
@llity 好的，我先记录下来。

**Comment by btwise** [comment]
开发版和稳定版还是有必要区分的，很多时候开发版会有问题，可能会回退一些功能，但不是每个人都是测试者，需要回到稳定版，没有必要再放置一个APP

**Comment by ic005k** [comment]
> 开发版和稳定版还是有必要区分的，很多时候开发版会有问题，可能会回退一些功能，但不是每个人都是测试者，需要回到稳定版，没有必要再放置一个APP，两者之间只是对一些选项的可用和不可用区别

OCAT目前没有这方面的打算，如果你有区分版本的需求，建议试试OCC（可通过网页搜索这个APP），它在这方面做得非常细致，记得有版本的区分。
感谢建议并欢迎提出更多的问题。
