### ISSUE TITLE
界面 label 显示不全的问题

### ISSUE THREAD

**Issue by cuteribs2** [ic005k/QtOpenCoreConfig#75]
![image](https://user-images.githubusercontent.com/85863433/141172334-a126b245-0014-43ae-aaee-606acbf7f9b4.png)
在 Win10 中很多选项最后几个字符都显示不完整, 望能修正. 

谢谢 😏

**Comment by ic005k** [comment]
收到。下个版本将修复它，感谢反馈。欢迎发现更多的问题或提供更多的建议。

**Comment by ic005k** [comment]
我查了下记录，这个问题似乎已经被修复过，我这边显示也是非常正常的。请问你目前使用的OCAT版本是多少？是最新版本吗？

**Comment by ic005k** [comment]
最新版对此又做了优化，请升级到最新版试试看。

**Comment by cuteribs2** [comment]
试了新版本, 确认问题已修复, 谢谢 👍
