### ISSUE TITLE
NVRAM预设

### ISSUE THREAD

**Issue by btwise** [ic005k/QtOpenCoreConfig#76]
对于NVRAM->4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14预设数据，UIScale应该丢弃了，它已经转移到了UEFI->OUTPUT！
对于NVRAM->7C436110-AB2A-4BBB-A880-FE41995C9F82,应该添加更多的启动参数预设数据，并加以功能提示，大多数人对MACOS的启动参数和OC的启动参数并不熟悉

**Comment by ic005k** [comment]
我个人可能没有太多时间来优化这些细节，所以“预设”这块的设计完全是开放性的，你们可以自行编辑它（在“编辑”菜单下面，用默认的plist编辑器打开它并添加或者是删除一些内容），这个预设文件位于数据库目录的“preset”。
如果你们愿意，也可以将编辑好的预设文件提交到这里，我可以放在OCAT的下个更新里面。
其实OCAT的很多功能都是开放性的，比如kext升级网址、数据库等等，就是为了让用户能自行修改或编辑。
后面我会逐一检查并开放更多的接口，方便大家自行编修数据。
感谢反馈并欢迎更多的建议。

**Comment by ic005k** [comment]
另外，kext的预设是根据数据库里面的kext的总数来自行生成的条目，也是完全开放性的设计。

**Comment by ic005k** [comment]
还有，OCAT的预制文件其实就是config.plist文件的精简版，编辑它是非常容易和熟悉的。

**Comment by btwise** [comment]
我说的预设并不是一次性全加到config里，而是使用菜单或其他方式供用户选择的内容

**Comment by ic005k** [comment]
我明白你的意思。
我的意思是将OCAT打造成一个完全开放式的结构，用户和用户之间可分享这些内容，而不是由我在程序中通过代码来自定这些内容，也就是说用户可用自行增强OCAT的功能，比如你上面所说的这些东西。
当然，OCAT需要做的事情还很多，慢慢完善吧，毕竟时间非常有限。

**Comment by ic005k** [comment]
> 对于NVRAM->4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14预设数据，UIScale应该丢弃了

我看了下，如果“UIScale”的值设为-1，则维持原来UIScale变量的设置，也就是说如果UIScale=-1，则NVRAM->4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14里面的UIScale值继续有效，而且我刚才通过了测试。
这个值，可能暂时还有它的作用，看后面OC的演进吧。
您是一个非常细致的人，赞。欢迎发现更多的问题，谢谢。
