### ISSUE TITLE
为何“同步OC”按钮灰色无法点击

### ISSUE THREAD

**Issue by insorasky** [ic005k/QtOpenCoreConfig#77]
0.7.5和0.7.6都试过了 目前版本是0.7.4
谢谢
![iShot2021-11-17 23 03 35](https://user-images.githubusercontent.com/68280231/142225888-82d1872d-3302-4953-a14c-96a12e647ed5.png)

**Comment by ic005k** [comment]
请检查下你EFI下面的OC各目录的完整性，这和OCAT的版本无关，OCAT会自动检查EFI下面各个目录的完整性，否则同步按钮是灰色的。
主要检查：
EFI/OC
EFI/BOOT
EFI/OC/Drivers
请核对下上面的目录结构是否完整？

**Comment by ic005k** [comment]
也就是说你打开的config.plist必须处于一个真实的OC环境中才可以进行同步。

**Comment by llity** [comment]
![image](https://user-images.githubusercontent.com/11771112/142715411-90cb267a-31a6-4354-ae50-8740bd8daa26.png)
怎么没有这个按钮，我发现点击右边，tab焦点丢失

**Comment by ic005k** [comment]
> 我发现点击右边，tab焦点丢失

是，一直都是这样的，它本身就是一个List。
记得你上次提过一个UI方案，我发现如果没有美工配合的话，是不太好实现的。
所以，如果你有更简单耐看的UI方案，可随时提出来。
我有时间会琢磨下UI的升级，但目前没有发现更好的方案或样式。

**Comment by insorasky** [comment]
我发现少了一个boot文件夹😂谢谢您了
