### ISSUE TITLE
Kext Update

### ISSUE THREAD

**Issue by dipakvz** [ic005k/QtOpenCoreConfig#78]
in Sync, Kext update section, XHCI-unsupported.kext and Airportitlwm.kext is showing grey, all other kext are showing green.

![Screenshot 2021-11-18 at 6 38 22 AM](https://user-images.githubusercontent.com/64690604/142332492-adb2c621-4f04-47d5-ac51-2f5a81fa6a00.png)
g

**Comment by ic005k** [comment]
> XHCI-unsupported.kext and Airportitlwm.kext is showing grey

Because you did not specify the upgrade URLs for these two kext, they are grayed out.
If these two kext do not have their own upgrade URLs, you can ignore them.
The upgrade URLs for kext are in the "Database" screen, and you can customize the official kext URLs.

**Comment by ic005k** [comment]
That is, so those that do not have a self-defined official kext URL will be grayed out to show the difference and have no other intention than that.

**Comment by dipakvz** [comment]
I have added upgrade URL for Airportitlwm.kext which is https://github.com/OpenIntelWireless/itlwm but not fetching detail of latest kext like all other kext.

I think it is due to multiple MacOS version release under Assets.

any solution ?

**Comment by ic005k** [comment]
When adding a kext URL, its kext name, please take the actual one used as the main one, as follows
Kext Name ：AirportItlwm.kext
Url: https://github.com/OpenIntelWireless/itlwm

However, there seems to be a problem that when the author of this kext publishes the kext, the name of the kext for all platforms is "AirportItlwm.kext", which will lead to the overwriting of the same name when it is automatically processed.

I have no experience with this kext, so I can only give you the above advice for your reference.

**Comment by ic005k** [comment]
![kext1](https://user-images.githubusercontent.com/25247437/147872274-ce3d146c-71f2-4cb8-90bb-cec80d1b2b23.png)

![kext2](https://user-images.githubusercontent.com/25247437/147872277-502a2198-ce1e-4e7d-b732-5bb79a08c07c.png)
