### ISSUE TITLE
同步有时候，会掉一下配置。

### ISSUE THREAD

**Issue by llity** [ic005k/QtOpenCoreConfig#81]
不知道多久BlessOverride的值掉了。之前DeviceProperties也掉过。
![image](https://user-images.githubusercontent.com/11771112/143861656-fa1b63ac-6356-455e-87b3-63f42b7aa210.png)

**Comment by ic005k** [comment]
收到，已纳入重点监测对象，感谢反馈。

**Comment by ic005k** [comment]
如果有空，请参与这个话题的讨论：https://github.com/ic005k/QtOpenCoreConfig/issues/82
谢谢。

**Comment by ic005k** [comment]
截止目前，还没发现有类似的现象，或许这个问题在某个版本中已被修复。
我对软件bug绝对是零容忍的，我会继续监测，同时欢迎发现更多问题或建议。
