### ISSUE TITLE
[Feature Request] MacOS Update Ideas

### ISSUE THREAD

**Issue by LucasMucGH** [ic005k/QtOpenCoreConfig#82]
Hello ic005k,

first of all I want to tell you that I appreciate your work and love how fast you update the App to match the current acidanthera master branch/dev builds. Keep it up!

Nevertheless I would love to submit my feedback and my opinion on how to improve the app and to make the user flow even more intuitive. Please keep in mind, that most recommendations are based on my opinion and therefore don't hesitate to ask why I proposed each change.

- Deactivate the `Open Recent` button when there are no recent files, by changing the image color to light grey (only applicable when in the toolbar)
- Explanation on the `Sync OC main program` feature inside the app
- Remove the `Show Tips` button (when right-clicking a quirk)
- Remove the `Copy text/qurik/...` button (when right-clicking a text/qurik/...) and instead allow selecting text by mouse
- When hovering over the buttons on the left side ("ACPI", "Booter", ...) the text and icon moves weirdly

Like I said, most of these are opinion based and if you want we can discuss each point individually. If you don't understand some of my ideas, don't hesitate to ask and I will provide further details.

Thank you and greetings from Munich,
Lucas

**Comment by ic005k** [comment]
It's great to receive such detailed suggestions and feedback from you. I'd like to invite @llity and @5T33Z0 to join this discussion, I'd like to hear their opinions, they have their own unique insights in UI details control and user interaction, and I've adopted many of the opinions they provided before.

**Comment by ic005k** [comment]
I will collect opinions and make improvements to the app accordingly. You are welcome to speak up, thank you.

**Comment by 5T33Z0** [comment]
- The OpenRecent button works fine for me. Removing it from the GUI is a mistake in my opinion. It's the most useful command in the toolbar. 
- About Quirks: instead of showing tool tips here, a preset menu would make more sense. Then you just add presets with quirks for each CPU family. I've listed most of them here: https://github.com/5T33Z0/OC-Little-Translated/tree/main/08_Quirks

**Comment by LucasMucGH** [comment]
- I would suggest the following: The app automatically opens the last edited config, if available. The Open Recent button is therefore mostly unnecessary (in macOS), because it is also presented in the macOS menu bar. This should be the expected behavior for every macOS user, because every app behaves like that (e.g.: XCode, ProperTree, TextEdit, …)
- Im not sure what you mean with ‚menu‘ instead of the tip, but I‘ve looked at your quirks table and think it should definitely be present somewhere in the app. Maybe there could be a picker, where you enter your Platform (Laptop/Desktop) and your CPU generation. And afterwards the quirks of the config would get changed appropriately (by using the information of your table).

**Comment by ic005k** [comment]
> * a preset menu would make more sense.

This is a good idea.
Because my free time is very limited.
Can you please tell me obviously how to preset?
For example.
ACPI section: first generation CPUs Which options to check, second generation CPUs which options to check, etc.
That way I can just focus on the implementation programmatically without the distraction of having to gather and organize this content. Thanks.

**Comment by ic005k** [comment]
@5T33Z0 
Sure, at the end of the text, I will sign your name.
"This content was compiled by 5T33Z0".

**Comment by 5T33Z0** [comment]
@ic005k Here's the list of Quirk presets. Somebody should counter-check it to verify.

[Quirks_List._v1.0md.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7633088/Quirks_List._v1.0md.zip)

**Comment by ic005k** [comment]
@5T33Z0 
Quirks' pre-selection feature is very useful, nice job.
More good ideas are welcome, thanks.

**Comment by 5T33Z0** [comment]
I Updated the document to v2. It contains quirks for High End Desktop PCs now.

**Comment by ic005k** [comment]
> I Updated the document to v2. It contains quirks for High End Desktop PCs now.

Okay, I'll get back to updating it.
OCAT uses a completely open interface, the preselection files are placed in the "database" directory of OCAT, and the preselection can be updated by updating 4 txt files in the "preset" directory. The update can be done very easily.

**Comment by 5T33Z0** [comment]
Okay, cool. Thanls

**Comment by ic005k** [comment]
> I think quirks should be pre-selected and not just set cursive…

This depends on the user's feedback. In most cases, we can help the user to choose, but we can't choose for them. That is, pre-selection cannot directly change the value of Quirks, otherwise, the user may resent it.
I will keep optimizing it later when I have enough time.
In the future, if you have free time, you can directly provide me with 4 txt files so I can put them on GitHub to complete the upgrade. Thanks.

**Comment by LucasMucGH** [comment]
Maybe a button in the menu bar, called „Apply quirk recommendations“ would be the way to keep the freedom of the user, but adding a auto-select feature.

**Comment by 5T33Z0** [comment]
Unnecessary intermediate step and unintuitive as well. Either the quirks are applied after choosing a preset or don't. But don't add more buttons where it's unnecessary. This is not the 80s where you kill any intuitive design with buttons on top of buttons. Everybody is free to unselect any quirks by themselves afterwards.

But bring back top Open and Recent Buttons to the toolbar.

**Comment by LucasMucGH** [comment]
Im sorry I didn't checked the current implementation, before I wrote my comment. I wrote it based on the information provided to my by this thread. I have now downloaded the latest release and checked it out.

Nevertheless I would still suggest to add a button for selecting the quirks. This button could be placed on the right side of the picker and with the text "Apply". It would be disabled (gray) when no Preselection is applied, but after selecting something from the picker it changes to be enabled (blue/black). This would make it easier to apply the changes instantaneously, but would not hurt the user interface.

In opposite to 5T33Z0 I really like the changes in the toolbar and i think it is now much more intuitive. I love (all) of the changes you made based on my opinion.

Regarding 5T33Z0 comment: Please keep in mind that this is only my opinion and I don't want to offed anyone. Design is a really controversial topic and it is normal that opinions are different; but you are right, adding a Button to the top bar would make it unintuitive and im sorry for not checking the current implementation before commenting something.

I also updated my initial issue and removed the already changed or fixed suggestions.
Last but not least I want to thank ic005k for his great work 5T33Z0 for providing the files for making the qurirk selection feature possible, keep it up!

**Comment by 5T33Z0** [comment]
I  have to open dozens of configs per day and I don't understand why there are no "open" and no "recent" buttons anymore. Nobody uses the backup button, but this is still there… I don't understand the reasoning behind it. And why is the toolbar pinned to the right now and not the left? Totally unusual and counter-intuitive…

Anyway, here are the quirks for 11th Gen Intel i5/i7/i9

**Prerequisites**:

Kernel > Emulate

**Cpuid1Data**:  EB060900000000000000000000000000
**Cpuid1Mask**: FFFFFFFF000000000000000000000000

**Booter**:

#### Intel 10th Gen Comet Lake and 11th Gen Rocket Lake (Dektop/Mobile/Nuc)
- AvoidRuntimeDefrag
- DevirtualiseMmio
- EnableSafeModeSlide
- ProtectUefiServices
- ProvideCustomSlide
- RebuildAppleMemoryMap
- SyncRuntimePermissions
- ProvideMaxSlide: 0

**Kernel**:

#### Intel 11th Gen Rocket Lake (Dektop/Mobile/Nuc)
- AppleXcpmCfgLock
- DisableIoMapper
- DisableLinkeditJettison
- DisableRtcChecksum
- PanicNoKextDump
- PowerTimeoutKernelPanic
- SetApfsTrimTimeout: -1
- XhciPortLimit

**UEFI**:

#### Intel 10th Gen Comet Lake and 11th Gen Rocket Lake (Dektop)
- EnableVectorAcceleration
- RequestBootVarRouting

#### Intel 10th Gen Comet Lake and 11th Gen Rocket Lake (Mobile/NUC)
- EnableVectorAcceleration
- ReleaseUsbOwnership
- RequestBootVarRouting

#### Intel 10th Gen Comet Lake and 11th Gen Rocket Lake (HP Desktop)
- EnableVectorAcceleration
- RequestBootVarRouting
- UnblockFsConnect

### Intel 10th Gen Comet Lake and 11th Gen Rocket Lake (HP Mobile/NUC)
- EnableVectorAcceleration
- ReleaseUsbOwnership
- RequestBootVarRouting
- UnblockFsConnect

**Comment by LucasMucGH** [comment]
> I don't understand why there are no "open" and no "recent" buttons anymore.

In my opinion the average user uses the „Open“ and „Open Recent“ Button nearly never, because he only configures OpenCore for his own PC/Laptop and therefore only has one plist (maybe 2-3 if he has a backup or test-plist‘s). Therefore these buttons are only used once when opening the Programm. And because the majority of people don’t switch between plist a lot it is only used once per session; so there is no need for it in the menu bar.

I also want to refer to other popular apps again, because nearly every native or python app for macOS uses the macOS menu bar. So as an macOS User it is really counterintuitive when the buttons are place somewhere else. I don’t see a reason to destroy the default macOS behavior, by having a button in the top bar (after all it is just one click difference).

> I have to open dozens of configs per day

I only think that in edge cases those buttons are really useful, like when writing a guide (and therefore creating plist‘s for every operating system) or when creating OpenCore Configrations for other people (friends, family or even selling them to strangers).

> Nobody uses the backup button, but this is still there…

i think this is a really useful button, nevertheless I would also suggest to remove it from the top bar.

> And why is the toolbar pinned to the right now and not the left? Totally unusual and counter-intuitive…

I really liked this change, but this is my personal opinion.

Anyway, I would like to thank you for your input and I think that discussions like this are really helpful. It makes it possible to get different input, discuss it and later implement the best version.

**Comment by 5T33Z0** [comment]
The issue has been resolved by implementing customization of the toolbar in the latest build. 

Thanks to @ic005k

**Comment by 5T33Z0** [comment]
I've noticed that numerical values for "ProvideMaxSlide" and "SetApfsTrimTimeOut" are not applied when selecting presets.

**Comment by LucasMucGH** [comment]
>The issue has been resolved by implementing customization of the toolbar in the latest build.
>
>Thanks to @ic005k

Yes indeed a very lovely solution. Thank you!

**Comment by ic005k** [comment]
@5T33Z0 

If you have free time, you can make a generic profile for each CPU type, e.g.
cpu1.plist
cpu2.plist
cpu3.plist
etc.
After that, put them into OCAT's configuration file database, and the user just needs to double-click an entry inside the configuration file database to automatically generate a complete EFI folder on the desktop.
This greatly improves the efficiency and speed of configuring OC EFI for everyone, and I'm sure the majority of users will be very grateful.

**Comment by 5T33Z0** [comment]
[BaseConfigs.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7651500/BaseConfigs.zip)

## Included Configs

### INTEL

#### High End Desktop
- **X299 Cascade Lake X/W**
	- HEDT_X299_Skylake-X/W_Cascade_Lake-X/W_Dell
	- HEDT_X299_Skylake-X/W_Cascade_Lake-X/W_HP
	- HEDT_X299_Skylake-X/W_Cascade_Lake-X/W
- **X99 Haswell-E and Broadwell-E**
	- HEDT_X99_Haswell-E_iMacPro1,1
	- HEDT_X99_Broadwell-E_iMacPro1,1
- **X79 Sandy Bridge-E and Ivy Bridge-E**
	- HEDT_X79_SandyBridge+IvyBridge-E_iMac6,1_Dell
	- HEDT_X79_SandyBridge+IvyBridge-E_iMac6,1_HP
	- HEDT_X79_SandyBridge+IvyBridge-E_iMac6,1
- **X59 Nehalem and Westmere**
	- HEDT_X59_Nehalem+Westmere_MacPro5,1_Dell
	- HEDT_X59_Nehalem+Westmere_MacPro5,1_HP
	- HEDT_X59_Nehalem+Westmere_MacPro5,1
	- HEDT_X59_Nehalem+Westmere_MacPro6,1_Dell
	- HEDT_X59_Nehalem+Westmere_MacPro6,1_HP
	- HEDT_X59_Nehalem+Westmere_MacPro6,1

#### Intel Core i5/i7/i9
- **11th Gen Rocket Lake**
 	- Desktop_11thGen_Rocket_Lake_iMacPro1,1
 	- Desktop_11thGen_Rocket_Lake_MacPro7,1
- **10th Gen Comet Lake**
	- Desktop_10thGen_Comet_Lake_iMac20,1
	- Desktop_10thGen_Comet_Lake_iMac20,2
- **8th and 9th Gen Coffee Lake**
	- Desktop_8th-9thGen_Coffee_Lake_iMac18,1
	- Desktop_8th-9thGen_Coffee_Lake_iMac18,3
	- Desktop_8th-9thGen_Coffee_Lake_iMac19,1
	- Desktop_8th-9thGen_Coffee_Lake_iMac19,1_Z390
	- Desktop_8th-9thGen_Coffee_Lake_iMac19,2
	- Desktop_8th-9thGen_Coffee_Lake_iMac19,2_Z390
- **7th Gen Kaby Lake**
	- Desktop_7thGen_Kaby_Lake_iMac18,1
	- Desktop_7thGen_Kaby_Lake_iMac18,3 
- **6th Gen Skylake**
	- Desktop_6thGen_Skylake_iMac17,1 
- **5th Gen Broadwell**
	- Desktop_5thGen_Broadwell_iMac16,2
	- Desktop_5thGen_Broadwell_iMac17,1
- **4th Gen Broadwell**
	- Desktop_4thGen_Haswell_iMac14,4
	- Desktop_4thGen_Haswell_iMac15,1 
- **3rd Gen Ivy Bridge**
	- Desktop_3rdGen_Ivy_Bridge_iMac13,1
	- Desktop_3rdGen_Ivy_Bridge_iMac13,2
	- Desktop_3rdGen_Ivy_Bridge_iMac14,4
	- Desktop_3rdGen_Ivy_Bridge_iMac15,1
	- Desktop_3rdGen_Ivy_Bridge_MacPro6,1 
- **2nd Gen Sandy Bridge**
	- Desktop_2ndGen_Sandy_Bridge_iMac12,2
	- Desktop_2ndGen_Sandy_Bridge_MacPro6,1
- **1st Gen Lynnfield and Clarkdale**:
	- Desktop_1stGen_Clarkdale_iMac11,2
	- Desktop_1stGen_Lynnfield_iMac11,1
	- Desktop_1stGen_Lynnfield_Clarkdale_MacPro6,1

### AMD

- **AMD Ryzen and Threadripper**
	- AMD_Ryzen_iMac14,2_Kepler+
	- AMD_Ryzen_iMacPro1,1_RX_Polaris
	- AMD_Ryzen_MacPro6,1_R5/R7R9
	- AMD_Ryzen_MacPro7,1_RX_Polaris
	- AMD_Threadripper_iMac14,2_Kepler+_A520+B550plist
	- AMD_Threadripper_iMac14,2_Kepler+
	- AMD_Threadripper_iMacPro1,1_RX_Polaris_A520+B550
	- AMD_Threadripper_iMacPro1,1_RX_Polaris
	- AMD_Threadripper_MacPro6,1_R5/R7/R9_A520+B550
	- AMD_Threadripper_MacPro6,1_R5/R7/R9
- **AMD Bulldozer and A-Series**
	- AMD_Bulldoze+Jaguar_iMacPro1,1_Polaris
	- AMD_Bulldoze+Jaguar_MacPro6,1_R5R7R9
	- AMD_Bulldoze+Jaguar_MacPro7,1_Polaris
	- AMD_Bulldoze+Jaguar_MacPro14,2_Kepler+ 

## References
- **OpenCore Install Guide:** https://dortania.github.io/OpenCore-Install-Guide
- **Base Configs**: https://github.com/luchina-gabriel?tab=repositories
- **Additional Files/Settings**: https://github.com/5T33Z0/OC-Little-Translated

**Comment by ic005k** [comment]
@ 5T33Z0

Nice work!
Back to you can package those missing AMD kext for me and I'll lay them out on GitHub, thanks.

**Comment by ic005k** [comment]
This time, OCAT's previously elaborate profile database finally came into play, after it had been sitting idle for a long time.

**Comment by 5T33Z0** [comment]
- https://github.com/acidanthera/bugtracker/files/3703498/AppleMCEReporterDisabler.kext.zip
- https://cdn.discordapp.com/attachments/566705665616117760/566728101292408877/XLNCUSBFix.kext.zip
- [SMCAMDProcessor](https://github.com/trulyspinach/SMCAMDProcessor/releases)
- One more SSDT for some other AMD config; https://github.com/dortania/Getting-Started-With-ACPI/blob/master/extra-files/compiled/SSDT-CPUR.aml

**Comment by 5T33Z0** [comment]
@ic005k Creating EFIs for Intel CPUs crashes the app a lot of times.

**Comment by ic005k** [comment]
@5T33Z0 

One small suggestion.
Back please change the "/" in some of the file names to "-" or other characters, otherwise it will not be recognized under Windows.
For details, please see.

https://github.com/ic005k/QtOpenCoreConfig/actions/runs/1537738534

**Comment by 5T33Z0** [comment]
Ahh, ok. I removed the the `/`. Latest Version. https://github.com/5T33Z0/OC-Little-Translated/blob/main/F_Desktop_EFIs/_BaseConfigs.zip?raw=true

**Comment by LucasMucGH** [comment]
It would be very cool, if there could be a (re)create vault button or maybe even if the app would recreate the vault automatically after saving.

**Comment by 5T33Z0** [comment]
@ic005k Is it possible to add a "Comment" column to to Config File list so I can some descriptions?

Something like this maybe?
![ConfigLIstComments](https://user-images.githubusercontent.com/76865553/144754553-09e1a0f9-0e58-4c0e-bc80-bf4d88c15324.png)

Or a dedicated section with a summary or similar.

Thanks.

**Comment by ic005k** [comment]
> vault

At the moment I have no experience of using this and have never tried "vault", can you tell me how to do this?
Alternatively, you could just tell me the exact steps.

**Comment by 5T33Z0** [comment]
Thanks for adding the "comments" feature. Is there a file where the info is stored stored, so I can share it with you once I am done adding all the descriptions? Thanks.

**Comment by ic005k** [comment]
> Is there a file where the info is stored

It is automatically stored in the plist file "#ConfigComment".
If the plist file does not have this "#ConfigComment" field, OCAT will automatically create it when the database interface is closed.
Alternatively you can use any third party plist editor to add this "#ConfigComment".


[AMD_Bulldoze+Jaguar_MacPro14,2_Kepler+.plist.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7659681/AMD_Bulldoze%2BJaguar_MacPro14.2_Kepler%2B.plist.zip)

**Comment by LucasMucGH** [comment]
> > vault
> 
> At the moment I have no experience of using this and have never tried "vault", can you tell me how to do this? Alternatively, you could just tell me the exact steps.


Here is an explanation of vaulting: https://dortania.github.io/OpenCore-Post-Install/universal/security/vault.html

But i will provide a detailed description:

A button (maybe in the menu bar, or even automatically on save), which is disabled when `Misc -> Security -> Vault` is set to `"Optional"`.

Otherwise it can be pressed and it will perform the following action; it runs the `sign.command` file, which is bundled with `OpenCorePkg -> Utilities -> Create Vault`.

As far as I know, you can’t tell this command which EFI to sign, but I’m not sure. It automatically closes the EFI, which is in the same directory tree.

**Comment by LucasMucGH** [comment]
I’m sorry, I just saw on your already added the feature.

**Comment by ic005k** [comment]
> I just saw on your already added the feature.

I don't know if this is the case, please confirm, does it work?

**Comment by LucasMucGH** [comment]
I will check it later today, I’m currently not at home.

**Comment by 5T33Z0** [comment]
@ic005k: For the next release, lease delete the existing base configs and readme and replace them with the files in this zip: https://github.com/5T33Z0/OC-Little-Translated/blob/main/F_Desktop_EFIs/_BaseConfigs.zip?raw=true

The first 2 configs contain a message because additional steps are necessary after the EFI folders are generated:

![Bildschirmfoto](https://user-images.githubusercontent.com/76865553/144874214-a124db46-0b57-402a-94f0-16f984aefec1.png)

Thanks

**Comment by 5T33Z0** [comment]
Updated Kernel-Quirks.txt
- Added High End Desktop, 
- Added 1st Gen Intel Core family, 
- Added "Core" to 1st - 11th gen Intel Core CPUs.

https://github.com/5T33Z0/OC-Little-Translated/blob/main/F_Desktop_EFIs/preset/Kernel-Quirks.txt

Added the quirks templates to my repo which makes it easier to update them in the future:

https://github.com/5T33Z0/OC-Little-Translated/blob/main/F_Desktop_EFIs/preset/

**Comment by LucasMucGH** [comment]
Update the original post to only contain the left over suggestions.
