### ISSUE TITLE
Drivers不放置OpenCanopy和主题，OC程序同步列表仍存在该项并提示更新

### ISSUE THREAD

**Issue by jdjxk** [ic005k/QtOpenCoreConfig#85]

**Comment by ic005k** [comment]
你是一个很细心的人，赞。
这个是必须的，带有强制性的，不管你驱动列表里面是否有这个文件，它都会出现在同步窗口中。
如果你不想同步它，可以将它勾掉即可。

后面的版本我可能会做些调整，可能会去掉这个文件，请关注OCAT的后续版本。

**Comment by jdjxk** [comment]
了解了，感谢！
