### ISSUE TITLE
Platform macPro7.1 with Custom memory activated

### ISSUE THREAD

**Issue by fabiosun** [ic005k/QtOpenCoreConfig#86]
A bug I think in my system
![1343235460_Screenshot2021-12-07at12_30_41PM png 3f46f4d06c07441a249db72c7c65dbad](https://user-images.githubusercontent.com/6358373/145025387-48eda989-973b-4621-9509-627b47b42865.png)
this above is my platform info in config.plist before using OCAT (latest available by now)

After syncing my config with OCAT I have this:

![1643824961_Screenshot2021-12-07at12_33_00PM png 062cc02db72824692dc95ebc12b08ee8](https://user-images.githubusercontent.com/6358373/145025531-7b0d7bda-c971-4296-942f-3413ccc2ea0c.png)

And system does not start anymore...
putting back memory tab all is fine again

**Comment by ic005k** [comment]
Please select "Keep data such as "Datahub".
Perhaps this function needs improvement.
If there is data in the user's memory customization, OCAT will automatically save this memory data.

**Comment by ic005k** [comment]
The "Keep data such as "Datahub"" feature was also suggested by a previous user. I think it needs to be improved.
Thanks for the feedback and I welcome any further questions or suggestions.

**Comment by fabiosun** [comment]
thank you for your fast answer and help
using that flag helps to maintain my memory tab, but it adds many un useful stuff for me as you can see in outlined blu in picture below
<img width="589" alt="Screenshot 2021-12-07 at 1 54 36 PM" src="https://user-images.githubusercontent.com/6358373/145032929-28f15da1-7a91-4e96-9490-f340b82501ef.png">

**Comment by fabiosun** [comment]
all not useful adding is with empty values (so it could not be a problem)

**Comment by ic005k** [comment]
On this point, OCAT has been updated, please upgrade to the latest version.

**Comment by fabiosun** [comment]
I am using this
<img width="298" alt="Screenshot 2021-12-07 at 2 06 19 PM" src="https://user-images.githubusercontent.com/6358373/145034622-d97a16eb-8859-44df-b6b2-04a22cfda1cb.png">

Unuseful thing added  but now system starts well and memory section is there as my original config.plist
thank you again

**Comment by ic005k** [comment]
> Unuseful thing added

At this point, you can uncheck the box "Keep data such as "Datahub" and the useless stuff will disappear automatically.

**Comment by fabiosun** [comment]
ok I will try by now :)
Thank you

**Comment by fabiosun** [comment]
> > Unuseful thing added
> 
> At this point, you can uncheck the box "Keep data such as "Datahub" and the useless stuff will disappear automatically.

confirmed :)
