### ISSUE TITLE
Separating development and stable versions

### ISSUE THREAD

**Issue by vit9696** [ic005k/QtOpenCoreConfig#87]
Hey,

After some testing, we discovered that there is some difficulty with OCAT release channel separation, which can be improved by more aligning it with what we do for OpenCore/Acidanthera releases. Currently the situation is like this:

1. If I want to use OCAT with a stable version of OpenCore 0.7.5 I should download OCAT 202111xx and stay with it.
2. If I want to use OpenCore 0.7.6, then I download OCAT 202200xx and stay with it.
3. If I want to use OpenCore from master (i.e. 0.7.7), then I download whatever latest OCAT version exists.

This makes good sense to me, but there is a difficulty in the usability part. It is uneasy to find the right version of OCAT for the latest stable version of OpenCore. To fix that, I believe you should use GitHub [pre-releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository):

1. Latest OCAT release targets latest OpenCore release
2. Latest OCAT pre-release targets latest OpenCore pre-release
3. Whenever OpenCore gets a new (monthly) release you edit your latest pre-release and make it release.

For the autoupdater the following changes need to be made:

1. Ask the user explicitly which OpenCore does he want: _stable_ or _development_?
2. Show the update channel/OpenCore version in the title-bar: e.g. OC 0.7.7 [DEV] or OC 0.7.6 [STABLE].
3. Optionally change the updater to choose the latest OCAT based on the update channel. GitHub API has `prerelease` field (see https://api.github.com/repos/ic005k/QtOpenCoreConfig/releases), letting you grab the latest version for either channel.

(3) might require some effort to implement, so a quick change would be to disable auto-updates for stable versions before the feature lands.

Thanks,
Vit

**Comment by ic005k** [comment]
Your advice and feedback has given me some enlightenment and is much appreciated. Any further questions or suggestions are welcome.

**Comment by btwise** [comment]
It is perfectly possible to combine the release and development versions and switch them by using the preferences  . The development version only adds or removes a few options from the previous release and does not require much work
