### ISSUE TITLE
Threadripper (TRX40) database support

### ISSUE THREAD

**Issue by fabiosun** [ic005k/QtOpenCoreConfig#88]
First of all thank you for your efforts in this useful app-

I would like to ask how you have achieved EFi available in your database section for thread ripper CPU

They are quite wrong
if you have time take a look here:
https://www.macos86.it/topic/3307-trx40-bare-metal-vanilla-patches-yes-it-worksbutis-proxmox-better/#comments
In this thread are available different EFI for different motherboards and CPU

If I may, I would prioritize explaining that for example for threadripper CPUs there is no need to use kernel patches 14/15 (FIX patches) and also the kext section is quite wrong, also quirks could be better and a particular attention should be on MMIO part and initial 3 CPU kernel patches (they need some adjustment because are CPU and motherboard related)

AMD is quite unique as a platform, and not having direct support from the OpenCore developers, it becomes difficult to get it up and running if incorrect information is received.
thanks again for your wonderful work

**Comment by ic005k** [comment]
Thank you very much for pointing out the problem.
Please author @5T33Z0 to answer your question, thank you.

**Comment by 5T33Z0** [comment]
@fabiosun Hi. Thanks for the info. The config used for AMD Ryzen/Threadripper is based on this: https://github.com/luchina-gabriel/BASE-EFI-AMD-RYZEN-THREADRIPPER 

Since I don't have an AMD system, I cannot test AMD configs so I have to rely on info that's available. Can you attach an AMD config which is known working so I can adjust the settings? I can't download the ones listed in the thread, since I am not a member of this forum.

**Comment by fabiosun** [comment]
@5T33Z0 the site you referred to is very generic and not particularly calibrated on CPU threadripper
Threadripper cpu refer to two different types of sockets and chipsets (x399 and TRX40 the latest ones)
And it is not possible to have a generic (and above all working) EFI
if we use patches, kext and quirks also valid for Ryzen CPU model as X570 or lower chipset compatible

As regards in particular the platform that I have known for some time, namely TRX40, it still needs different functionalities.
The calculation and activation of the MMIO whitelist (which is functional and dependent on various parameters such as Bios version, manufacturers and occupied slots) is fundamental, to then arrive at the definition of specific kext for network cards or patches to be applied for models supported like the Aquantia

If possible, I recommend that you subscribe to the recommended forum, which is the best resource you can find on the web
just one message is enough to download everything
Having said that, I am attaching my config
valid for MSI Trx40 pro, CPU 3970x, Monterey 12.x with this BIOS configuration:
Above 4g on
Resize bar on
Uefi Hon
6900xt GPU
first, third and fourth slot occupied with:
GPU
PCIE Nvme card
Ethernet fenvi wifi / bt card
[config.plist.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7691837/config.plist.zip)

Pay attention.
MMIO whitelist is for this motherboard and configuration

Unfortunately the speech is too long (not complex but long) to be addressed in a github issue :)

attached config for trx40 has only 2 kexts mandatory to have audio or GPU working (Lilu and VirtualSMC)
Ethernet is seen out of box (wifi bt pciexpress one)
Aquantia need a patch and i21x ethernet is problematic in Monterey with available kexts )

**Comment by 5T33Z0** [comment]
Thanks for sharing your config and the explanations. If it is not possible to create a working EFI for AMD based on a config.plist template, my suggestions are the following:

1. Remove the AMD templates from OCAT (makes no sense to have it there if it generates unusable EFIs.
2. I think you Fabiosun should create a Report with the necessary changes for the Dortania Guide fro AMD Threadripper: https://dortania.github.io/OpenCore-Install-Guide/CONTRIBUTING.html#contributing-via-issues

Greetings 5T33Z0
