### ISSUE TITLE
[Feature Request] Dependent settings support

### ISSUE THREAD

**Issue by junaedahmed** [ic005k/QtOpenCoreConfig#9]
When UpdateSMBIOSMode is set as custom then kernel quirk CustomSMBIOSGuid should automatically made on with a note about it. This kind of auto settings could be very helpfull.

**Comment by ic005k** [comment]
Good idea, I will implement it in the next version, thanks for suggestions!

**Comment by ic005k** [comment]
This feature has been implemented, please download the latest version.
