### ISSUE TITLE
反馈两个问题

### ISSUE THREAD

**Issue by 778280151** [ic005k/QtOpenCoreConfig#90]
1.kernel -》add了里面kext的中文注释会导致  oc验证报 Comment contains illegal character! 这个都是注释了,感觉可以忽略这种
2.机型信息里面希望可以简单配置,直接一键生成   对应机型的 序列码  rom 提供来自网卡  mac

**Comment by ic005k** [comment]
首先感谢反馈。
1.这个问题我还真解决不了，因为这是OC判断的，而不是OCAT判断的，所以你可能需要向OC的开发团队提供这个建议。
2.这是个bug，下个版本将修复它，这些按钮被隐藏了。
欢迎更多的问题或建议。

**Comment by ic005k** [comment]
> rom 提供来自网卡 mac

目前的rom是随机生成的，能否详细说下为什么要取自网卡的mac呢？
其实我并不了解rom这个东西，上次 @vit9696 说可以生成一个，所以我就按着随机数生成了一个。
如果你对rom这个很了解，可以告诉我怎么做才是最正确的。
谢谢。

**Comment by 778280151** [comment]
> 

嗯嗯,感谢老哥的快速回复😁,主要是因为我发现rom这里不填写mac会影响facetime和短信好像接力也会有点问题

**Comment by ic005k** [comment]
> 不填写mac会影响facetime和短信好像接力也会有点问题

你回头可以试下，如果填写别的值，比如用OCAT生成一个ROM，看是否有影响。
