### ISSUE TITLE
关于新UI的一点小建议

### ISSUE THREAD

**Issue by k2y1982** [ic005k/QtOpenCoreConfig#91]
![1](https://user-images.githubusercontent.com/5109711/145955942-f08b4073-542d-40bc-b349-064192a2f4ae.png)
我知道它原本的作用，< >，但如果是把它放在右下角的侧面，或许 ˄ ˅ 会更好明白一点。

**Comment by ic005k** [comment]
好的，这只是暂时的，后面可能还会继续优化的。

另外，˄ ˅比较小，貌似是非标键盘字符，担心在各个系统上的显示问题。
最好是用小图标，但我目前时间不太够，后面再慢慢处理。

感谢反馈，同时欢迎更多的建议或问题。

**Comment by ic005k** [comment]
其实我个人是建议使用快捷键，这些都可以通过快捷键来实现，非常便利，但有部分用户反映不方便，所以又做了重新设计，加了个侧边栏。
