### ISSUE TITLE
Buttons for upd/down, add/delete missing in a lot of Sections

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/QtOpenCoreConfig#94]
No Buttons for up/down, add/delete missing in:

- Booter > MmioWhitelist
- Booter > Patch
- Misc > Bless Override
- Misc > Entries
- Misc > Tools
- NVRAM > Add,
- NVRAM > Delete
- NVRAM > LegacySchema
- UEFI > Drivers
- UEFI > Reserved Memory

**Comment by ic005k** [comment]
These buttons have been added and I will continue to improve them later when I have free time, thanks for the feedback.
More questions or suggestions are welcome.

**Comment by 5T33Z0** [comment]
Thanks for your continues support of power users!
