### ISSUE TITLE
ACPI patch was broken when updating by OCAT

### ISSUE THREAD

**Issue by roddy20** [ic005k/QtOpenCoreConfig#95]
![Снимок экрана 2021-12-15 в 23 43 13](https://user-images.githubusercontent.com/5681302/146270675-747c1a1d-22b3-4d5a-870a-29d3ac89cc10.png)

correct mask was fffafe, now 3f3f3f

**Comment by roddy20** [comment]
[config.plist 2.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7723113/config.plist.2.zip)
working config.plist

**Comment by roddy20** [comment]
[config.plist.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7723268/config.plist.zip)
broken config plist

**Comment by roddy20** [comment]
![Снимок экрана 2021-12-16 в 0 53 54](https://user-images.githubusercontent.com/5681302/146277855-f5f1ec7b-7b6f-4063-9164-6c8445c1a011.png)

**Comment by ic005k** [comment]
Thank you very much for finding the bug.
The issue has been fixed.
Any further questions or suggestions are welcome.
