### ISSUE TITLE
您好，能否默认选中当前引导分区磁盘呢

### ISSUE THREAD

**Issue by imotoboy** [ic005k/QtOpenCoreConfig#96]
<img width="1168" alt="截屏2021-12-16 下午8 03 12" src="https://user-images.githubusercontent.com/54018634/146368756-720ebf44-33ae-46f2-b6ea-b905d6a89106.png">

**Comment by ic005k** [comment]
自动识别本次引导由哪个ESP分区完成，这个目前暂时没时间研究。
不过，新版的OCAT增加了自动记忆上次挂载的ESP分区，异曲同工。
欢迎更多的问题或建议，感谢反馈。

**Comment by imotoboy** [comment]
谢谢
