### ISSUE TITLE
关于仿冒GPU

### ISSUE THREAD

**Issue by sun969735725** [ic005k/QtOpenCoreConfig#98]
请问大佬我的笔记本是i5-1135G7+MX350，GPU方面独显和核显哪个更容易仿冒（目前好像没有NVIDIA仿冒为AMD的方法）？

**Comment by ic005k** [comment]
这个我还真没实战经验，11代核显目前貌似无解，只能用独显了。
如果是笔记本的话，貌似整个都无解，因为笔记本没法用内置独显。
仅供参考，你也可搜索下相关内容。
