### ISSUE TITLE
关于打开 config.plist 右键键盘，能修复吗

### ISSUE THREAD

**Issue by iaihc** [ic005k/QtOpenCoreConfig#99]
关于打开 config.plist 右键键盘，能修复吗，显示配置工具版本号

**Comment by ic005k** [comment]
抱歉，没太明白，能否具体一些？谢谢。

**Comment by iaihc** [comment]
请你看看，当打开文件config的时候，右键新版本，不知道从哪个版本开始，这里就不正常了，不能像下面的这个 20211127这个0.7.5这样显示了，希望能改成下面一样的。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ic005k/QtOpenCoreConfig"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 中午12:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ic005k/QtOpenCoreConfig] 关于打开 config.plist 右键键盘，能修复吗 (Issue #99)





 
抱歉，没太明白，能否具体一些？谢谢。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ic005k** [comment]
明白。请升级到最新版，已添加。
欢迎更多的问题或建议，感谢反馈。

**Comment by iaihc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ic005k/QtOpenCoreConfig"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 中午1:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ic005k/QtOpenCoreConfig] 关于打开 config.plist 右键键盘，能修复吗 (Issue #99)





 
明白。请升级到最新版，已添加。
 欢迎更多的问题或建议，感谢反馈。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;




已经更新了，但很不协调，因为右键后如下图：






有点吹毛求次了，因为像下面这个&nbsp;协调一些，毕竟要照顾老版本吧。

**Comment by ic005k** [comment]
其实老版本的OCAT的版本信息是非常不规范的，当时设计时由于时间的关系，非常潦草。
目前的版本信息是非常规范的，不过你也不用担心，OCAT的迭代非常敏捷，过不了几天，你将看到的都是新版本的版本信息。
有任何问题，请随时留言。

**Comment by iaihc** [comment]
亲爱的辛苦的设计人员，如果很规范，那么，我希望你能帮助我们这些用户，把OC075和OC074两个版本，分别把右键打开规范下，因为我是安装用户，经常使用这些工具，我需要一个美观的右键菜单，也算是个人强迫症吧。把OC0.7.5至少右键也改下
我不希望右键太长，你现在的202200051这个版本的右键，提示太长了。和苹果其它的一些工具很不协调。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月20日(星期一) 下午5:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ic005k/QtOpenCoreConfig] 关于打开 config.plist 右键键盘，能修复吗 (Issue #99)





 
其实老版本的OCAT的版本信息是非常不规范的，当时设计时由于时间的关系，非常潦草。
 目前的版本信息是非常规范的，不过你也不用担心，OCAT的迭代非常敏捷，过不了几天，你将看到的都是新版本的版本信息。
 有任何问题，请随时留言。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ic005k** [comment]
我会尽量去调整它，请关注软件的后续升级。
